from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, ClassVar, Generic, TypeVar, overload
import CodeWalker
import SharpDX

T = TypeVar("T")
T1 = TypeVar("T1")
T2 = TypeVar("T2")
T3 = TypeVar("T3")
T4 = TypeVar("T4")

class BitUtil:
    @staticmethod
    def ClearBit(value: int, bit: int) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def IsBitSet(value: int, bit: int) -> bool: ...
    @staticmethod
    def RotateLeft(value: int, count: int) -> int: ...
    @staticmethod
    def RotateRight(value: int, count: int) -> int: ...
    @staticmethod
    def SetBit(value: int, bit: int) -> int: ...
    def ToString(self) -> str: ...
    @staticmethod
    def UpdateBit(value: int, bit: int, flag: bool) -> int: ...

class BoundingBoxMath:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def Transform(b: SharpDX.BoundingBox, position: SharpDX.Vector3, orientation: SharpDX.Quaternion, scale: SharpDX.Vector3) -> SharpDX.BoundingBox: ...
    @overload
    @staticmethod
    def Transform(b: SharpDX.BoundingBox, mat: SharpDX.Matrix) -> SharpDX.BoundingBox: ...

class BoundingCapsule:
    PointA: SharpDX.Vector3
    PointB: SharpDX.Vector3
    Radius: float
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class BoundingCapsuleMath:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    @staticmethod
    def Intersects(r: SharpDX.Ray, capsule: BoundingCapsule, dist: float) -> bool: ...
    @overload
    @staticmethod
    def Intersects(sph: SharpDX.BoundingSphere, capsule: BoundingCapsule, norm: SharpDX.Vector3) -> bool: ...
    @staticmethod
    def Normal(c: BoundingCapsule, position: SharpDX.Vector3) -> SharpDX.Vector3: ...
    def ToString(self) -> str: ...

class BoundingCylinder:
    PointA: SharpDX.Vector3
    PointB: SharpDX.Vector3
    Radius: float
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class BoundingCylinderMath:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def Intersects(r: SharpDX.Ray, cylinder: BoundingCylinder, dist: float, norm: SharpDX.Vector3) -> bool: ...
    def ToString(self) -> str: ...

class Cache(Generic[T1, T2]):
    Count: int
    MaxMemoryUsage: int
    CurrentMemoryUsage: int
    CacheTime: float
    CurrentTime: Any
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, maxMemoryUsage: int, cacheTime: float) -> None: ...
    def BeginFrame(self) -> None: ...
    def CanAdd(self) -> bool: ...
    def Clear(self) -> None: ...
    def Compact(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Remove(self, key: TKey) -> None: ...
    def ToString(self) -> str: ...
    def TryAdd(self, key: TKey, item: TVal) -> bool: ...
    def TryGet(self, key: TKey) -> TVal: ...

class Cacheable(Generic[T]):
    Key: TKey
    LastUseTime: Any
    MemoryUsage: int
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class FbxAsciiReader:
    MaxArrayLength: int
    def __init__(self, stream: Any, errorLevel: FbxErrorLevel = ...) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Read(self) -> FbxDocument: ...
    def ReadNode(self) -> FbxNode: ...
    def ToString(self) -> str: ...

class FbxAsciiWriter:
    MaxLineLength: int
    def __init__(self, stream: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def Write(self, document: FbxDocument) -> None: ...

class FbxBinary:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def IsBinary(stream: Any) -> bool: ...
    def ToString(self) -> str: ...

class FbxBinaryReader:
    def __init__(self, stream: Any, errorLevel: FbxErrorLevel = ...) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Read(self) -> FbxDocument: ...
    def ReadNode(self) -> FbxNode: ...
    def ToString(self) -> str: ...

class FbxBinaryWriter:
    CompressionThreshold: int
    def __init__(self, stream: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def Write(self, document: FbxDocument) -> None: ...

class FbxConverter:
    InvertTexcoordV: bool
    def __init__(self) -> None: ...
    def ConvertToYdr(self, name: str, fbxdata: list[int]) -> CodeWalker.GameFiles.YdrFile: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class FbxDeflateWithChecksum:
    Checksum: int
    BaseStream: Any
    CanRead: bool
    CanWrite: bool
    CanSeek: bool
    Length: int
    Position: int
    CanTimeout: bool
    ReadTimeout: int
    WriteTimeout: int
    @overload
    def __init__(self, stream: Any, mode: Any) -> None: ...
    @overload
    def __init__(self, stream: Any, mode: Any, leaveOpen: bool) -> None: ...
    def BeginRead(self, buffer: list[int], offset: int, count: int, asyncCallback: Any, asyncState: Any) -> Any: ...
    def BeginWrite(self, buffer: list[int], offset: int, count: int, asyncCallback: Any, asyncState: Any) -> Any: ...
    def Close(self) -> None: ...
    @overload
    def CopyTo(self, destination: Any, bufferSize: int) -> None: ...
    @overload
    def CopyTo(self, destination: Any) -> None: ...
    @overload
    def CopyToAsync(self, destination: Any, bufferSize: int, cancellationToken: Any) -> Any: ...
    @overload
    def CopyToAsync(self, destination: Any) -> Any: ...
    @overload
    def CopyToAsync(self, destination: Any, bufferSize: int) -> Any: ...
    @overload
    def CopyToAsync(self, destination: Any, cancellationToken: Any) -> Any: ...
    def Dispose(self) -> None: ...
    def DisposeAsync(self) -> Any: ...
    def EndRead(self, asyncResult: Any) -> int: ...
    def EndWrite(self, asyncResult: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def Flush(self) -> None: ...
    @overload
    def FlushAsync(self, cancellationToken: Any) -> Any: ...
    @overload
    def FlushAsync(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    @overload
    def Read(self, array: list[int], offset: int, count: int) -> int: ...
    @overload
    def Read(self, buffer: Any) -> int: ...
    @overload
    def ReadAsync(self, buffer: list[int], offset: int, count: int, cancellationToken: Any) -> Any: ...
    @overload
    def ReadAsync(self, buffer: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    def ReadAsync(self, buffer: list[int], offset: int, count: int) -> Any: ...
    def ReadAtLeast(self, buffer: Any, minimumBytes: int, throwOnEndOfStream: bool = ...) -> int: ...
    def ReadAtLeastAsync(self, buffer: Any, minimumBytes: int, throwOnEndOfStream: bool = ..., cancellationToken: Any = ...) -> Any: ...
    def ReadByte(self) -> int: ...
    @overload
    def ReadExactly(self, buffer: Any) -> None: ...
    @overload
    def ReadExactly(self, buffer: list[int], offset: int, count: int) -> None: ...
    @overload
    def ReadExactlyAsync(self, buffer: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    def ReadExactlyAsync(self, buffer: list[int], offset: int, count: int, cancellationToken: Any = ...) -> Any: ...
    def ResetChecksum(self) -> None: ...
    def Seek(self, offset: int, origin: Any) -> int: ...
    def SetLength(self, value: int) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Write(self, array: list[int], offset: int, count: int) -> None: ...
    @overload
    def Write(self, buffer: Any) -> None: ...
    @overload
    def WriteAsync(self, buffer: list[int], offset: int, count: int, cancellationToken: Any) -> Any: ...
    @overload
    def WriteAsync(self, buffer: Any, cancellationToken: Any) -> Any: ...
    @overload
    def WriteAsync(self, buffer: list[int], offset: int, count: int) -> Any: ...
    def WriteByte(self, value: int) -> None: ...

class FbxDocument:
    Version: FbxVersion
    Nodes: list[FbxNode]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetRelative(self, path: str) -> FbxNode: ...
    def GetSceneNodes(self) -> list[FbxNode]: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class FbxErrorLevel(IntEnum):
    Permissive = 0
    Checked = 1
    Strict = 2

class FbxException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self, position: int, message: str) -> None: ...
    @overload
    def __init__(self, line: int, column: int, message: str) -> None: ...
    @overload
    def __init__(self, nodePath: Any, propertyID: int, message: str) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class FbxIO:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def Read(data: list[int]) -> FbxDocument: ...
    @staticmethod
    def ReadAscii(path: str) -> FbxDocument: ...
    @staticmethod
    def ReadBinary(path: str) -> FbxDocument: ...
    def ToString(self) -> str: ...
    @staticmethod
    def WriteAscii(document: FbxDocument, path: str) -> None: ...
    @staticmethod
    def WriteBinary(document: FbxDocument, path: str) -> None: ...

class FbxModel:
    Name: str
    Node: FbxNode
    Model: CodeWalker.GameFiles.DrawableModel
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class FbxNode:
    Name: str
    Properties: list[Any]
    Connections: list[FbxNode]
    Value: Any
    IsEmpty: bool
    Nodes: list[FbxNode]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetRelative(self, path: str) -> FbxNode: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class FbxNodeList:
    Nodes: list[FbxNode]
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetRelative(self, path: str) -> FbxNode: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class FbxPolygon:
    Vertices: list[FbxVertex]
    Materials: list[FbxNode]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class FbxVersion(IntEnum):
    v6_0 = 6000
    v6_1 = 6100
    v7_0 = 7000
    v7_1 = 7100
    v7_2 = 7200
    v7_3 = 7300
    v7_4 = 7400

class FbxVertex:
    Position: SharpDX.Vector3
    Normals: list[SharpDX.Vector3]
    Binormals: list[SharpDX.Vector3]
    Tangents: list[SharpDX.Vector3]
    Texcoords: list[SharpDX.Vector2]
    Colours: list[SharpDX.Vector4]
    Bytes: list[int]
    def __init__(self) -> None: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def Equals(self, other: FbxVertex) -> bool: ...
    def GenVertexBytes(self, decl: CodeWalker.GameFiles.VertexDeclaration) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class FloatUtil:
    @staticmethod
    def Clamp(f: float, min: float, max: float) -> float: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def GetColourString(v: SharpDX.Color, d: str = ...) -> str: ...
    @staticmethod
    def GetHalf2String(v: SharpDX.Half2, d: str = ...) -> str: ...
    @staticmethod
    def GetHalf4String(v: SharpDX.Half4, d: str = ...) -> str: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetQuaternionXmlString(q: SharpDX.Quaternion) -> str: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def GetVector2String(v: SharpDX.Vector2, d: str = ...) -> str: ...
    @staticmethod
    def GetVector2XmlString(v: SharpDX.Vector2) -> str: ...
    @staticmethod
    def GetVector3String(v: SharpDX.Vector3, d: str = ...) -> str: ...
    @staticmethod
    def GetVector3StringFormat(v: SharpDX.Vector3, format: str) -> str: ...
    @staticmethod
    def GetVector3XmlString(v: SharpDX.Vector3) -> str: ...
    @staticmethod
    def GetVector4String(v: SharpDX.Vector4, d: str = ...) -> str: ...
    @staticmethod
    def GetVector4XmlString(v: SharpDX.Vector4) -> str: ...
    @staticmethod
    def Parse(s: str) -> float: ...
    @staticmethod
    def ParseVector2String(s: str) -> SharpDX.Vector2: ...
    @staticmethod
    def ParseVector3String(s: str) -> SharpDX.Vector3: ...
    @staticmethod
    def ParseVector4String(s: str) -> SharpDX.Vector4: ...
    @staticmethod
    def Saturate(f: float) -> float: ...
    @overload
    @staticmethod
    def ToString(f: float) -> str: ...
    @overload
    def ToString(self) -> str: ...
    @staticmethod
    def TryParse(s: str, f: float) -> bool: ...

class LineMath:
    @staticmethod
    def DistanceFieldTest(s: SharpDX.Vector2, p1: SharpDX.Vector2, p2: SharpDX.Vector2, winding: int) -> float: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def PointRayDist(p: SharpDX.Vector3, ro: SharpDX.Vector3, rd: SharpDX.Vector3) -> float: ...
    @overload
    @staticmethod
    def PointSegmentDistance(v: SharpDX.Vector3, a: SharpDX.Vector3, b: SharpDX.Vector3) -> float: ...
    @overload
    @staticmethod
    def PointSegmentDistance(v: SharpDX.Vector2, a: SharpDX.Vector2, b: SharpDX.Vector2) -> float: ...
    @staticmethod
    def PointSegmentNormal(v: SharpDX.Vector3, a: SharpDX.Vector3, b: SharpDX.Vector3) -> SharpDX.Vector3: ...
    def ToString(self) -> str: ...

class MatrixExtensions:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    @staticmethod
    def Multiply(m: SharpDX.Matrix, v: SharpDX.Vector3) -> SharpDX.Vector3: ...
    @overload
    @staticmethod
    def Multiply(m: SharpDX.Matrix, v: SharpDX.Vector4) -> SharpDX.Vector4: ...
    @staticmethod
    def MultiplyRot(m: SharpDX.Matrix, v: SharpDX.Vector3) -> SharpDX.Vector3: ...
    @staticmethod
    def MultiplyW(m: SharpDX.Matrix, v: SharpDX.Vector3) -> SharpDX.Vector3: ...
    @staticmethod
    def ToQuaternion(m: SharpDX.Matrix) -> SharpDX.Quaternion: ...
    def ToString(self) -> str: ...

class PathUtil:
    AppPath: ClassVar[str]
    WorkPath: ClassVar[str]
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def GetFilePath(appRelativePath: str) -> str: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def ReadAllBytes(appRelativePath: str) -> list[int]: ...
    def ToString(self) -> str: ...

class QuaternionExtension:
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def FastLerp(a: SharpDX.Quaternion, b: SharpDX.Quaternion, v: float) -> SharpDX.Quaternion: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def Multiply(a: SharpDX.Quaternion, b: SharpDX.Vector3) -> SharpDX.Vector3: ...
    @staticmethod
    def ToMatrix(q: SharpDX.Quaternion) -> SharpDX.Matrix: ...
    def ToString(self) -> str: ...
    @staticmethod
    def ToVector4(q: SharpDX.Quaternion) -> SharpDX.Vector4: ...

class TextUtil:
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def GetBytesReadable(i: int) -> str: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def GetUTF8Text(bytes: list[int]) -> str: ...
    def ToString(self) -> str: ...

class TriangleBVH:
    Triangles: list[TriangleBVHItem]
    Node1: TriangleBVHNode
    Node2: TriangleBVHNode
    Box: SharpDX.BoundingBox
    def __init__(self, tris: list[TriangleBVHItem], depth: int = ...) -> None: ...
    def Build(self, tris: list[TriangleBVHItem], depth: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def RayIntersect(self, ray: SharpDX.Ray, hitdist: float) -> TriangleBVHItem: ...
    def ToString(self) -> str: ...

class TriangleBVHItem:
    Corner1: SharpDX.Vector3
    Corner2: SharpDX.Vector3
    Corner3: SharpDX.Vector3
    Box: SharpDX.BoundingBox
    Center: SharpDX.Vector3
    Orientation: SharpDX.Quaternion
    Scale: SharpDX.Vector3
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def UpdateBox(self) -> None: ...

class TriangleBVHNode:
    Triangles: list[TriangleBVHItem]
    Node1: TriangleBVHNode
    Node2: TriangleBVHNode
    Box: SharpDX.BoundingBox
    def __init__(self) -> None: ...
    def Build(self, tris: list[TriangleBVHItem], depth: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def RayIntersect(self, ray: SharpDX.Ray, hitdist: float) -> TriangleBVHItem: ...
    def ToString(self) -> str: ...

class TriangleMath:
    @staticmethod
    def Area(v1: SharpDX.Vector3, v2: SharpDX.Vector3, v3: SharpDX.Vector3) -> float: ...
    @staticmethod
    def AreaPart(v1: SharpDX.Vector3, v2: SharpDX.Vector3, v3: SharpDX.Vector3, angle: float) -> float: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class Vector2I:
    X: int
    Y: int
    @overload
    def __init__(self, x: int, y: int) -> None: ...
    @overload
    def __init__(self, v: SharpDX.Vector2) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class Vectors:
    @overload
    @staticmethod
    def Abs(v: SharpDX.Vector3) -> SharpDX.Vector3: ...
    @overload
    @staticmethod
    def Abs(v: SharpDX.Vector4) -> SharpDX.Vector4: ...
    @overload
    @staticmethod
    def Ceiling(v: SharpDX.Vector3) -> SharpDX.Vector3: ...
    @overload
    @staticmethod
    def Ceiling(v: SharpDX.Vector4) -> SharpDX.Vector4: ...
    @staticmethod
    def CompareTo(a: SharpDX.Vector3, b: SharpDX.Vector3) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    @overload
    @staticmethod
    def Floor(v: SharpDX.Vector3) -> SharpDX.Vector3: ...
    @overload
    @staticmethod
    def Floor(v: SharpDX.Vector4) -> SharpDX.Vector4: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetPerpVec(n: SharpDX.Vector3) -> SharpDX.Vector3: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def Round(v: SharpDX.Vector3) -> SharpDX.Vector3: ...
    @staticmethod
    def ToQuaternion(v: SharpDX.Vector4) -> SharpDX.Quaternion: ...
    def ToString(self) -> str: ...
    @staticmethod
    def XYZ(v: SharpDX.Vector4) -> SharpDX.Vector3: ...

class Xml:
    @staticmethod
    def AddChild(doc: Any, node: Any, name: str) -> Any: ...
    @staticmethod
    def AddChildWithAttribute(doc: Any, node: Any, name: str, attributeName: str, attributeValue: str) -> Any: ...
    @staticmethod
    def AddChildWithInnerText(doc: Any, node: Any, name: str, innerText: str) -> Any: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def GetBoolAttribute(node: Any, attribute: str) -> bool: ...
    @staticmethod
    def GetChild(element: Any, name: str) -> Any: ...
    @staticmethod
    def GetChildBoolAttribute(node: Any, name: str, attribute: str = ...) -> bool: ...
    @staticmethod
    def GetChildBoolInnerText(node: Any, name: str) -> bool: ...
    @staticmethod
    def GetChildEnumInnerText(node: Any, name: str) -> T: ...
    @staticmethod
    def GetChildFloatAttribute(node: Any, name: str, attribute: str = ...) -> float: ...
    @staticmethod
    def GetChildFloatInnerText(node: Any, name: str) -> float: ...
    @staticmethod
    def GetChildInnerText(node: Any, name: str) -> str: ...
    @staticmethod
    def GetChildIntAttribute(node: Any, name: str, attribute: str = ...) -> int: ...
    @staticmethod
    def GetChildIntInnerText(node: Any, name: str) -> int: ...
    @staticmethod
    def GetChildMatrix(node: Any, name: str) -> SharpDX.Matrix: ...
    @staticmethod
    def GetChildRawByteArray(node: Any, name: str, fromBase: int = ...) -> list[int]: ...
    @staticmethod
    def GetChildRawByteArrayNullable(node: Any, name: str, fromBase: int = ...) -> list[int]: ...
    @staticmethod
    def GetChildRawFloatArray(node: Any, name: str) -> list[float]: ...
    @staticmethod
    def GetChildRawFloatArrayNullable(node: Any, name: str) -> list[float]: ...
    @staticmethod
    def GetChildRawIntArray(node: Any, name: str) -> list[int]: ...
    @staticmethod
    def GetChildRawIntArrayNullable(node: Any, name: str) -> list[int]: ...
    @staticmethod
    def GetChildRawUintArray(node: Any, name: str) -> list[int]: ...
    @staticmethod
    def GetChildRawUintArrayNullable(node: Any, name: str) -> list[int]: ...
    @staticmethod
    def GetChildRawUshortArray(node: Any, name: str) -> list[int]: ...
    @staticmethod
    def GetChildRawUshortArrayNullable(node: Any, name: str) -> list[int]: ...
    @staticmethod
    def GetChildRawVector2Array(node: Any, name: str) -> list[SharpDX.Vector2]: ...
    @staticmethod
    def GetChildRawVector3Array(node: Any, name: str) -> list[SharpDX.Vector3]: ...
    @staticmethod
    def GetChildRawVector3ArrayNullable(node: Any, name: str) -> list[SharpDX.Vector3]: ...
    @staticmethod
    def GetChildRawVector4Array(node: Any, name: str) -> list[SharpDX.Vector4]: ...
    @staticmethod
    def GetChildRawVector4ArrayNullable(node: Any, name: str) -> list[SharpDX.Vector4]: ...
    @staticmethod
    def GetChildStringAttribute(node: Any, name: str, attribute: str = ...) -> str: ...
    @staticmethod
    def GetChildUIntAttribute(node: Any, name: str, attribute: str = ...) -> int: ...
    @staticmethod
    def GetChildULongAttribute(node: Any, name: str, attribute: str = ...) -> int: ...
    @staticmethod
    def GetChildVector2Attributes(node: Any, name: str, x: str = ..., y: str = ...) -> SharpDX.Vector2: ...
    @staticmethod
    def GetChildVector3Attributes(node: Any, name: str, x: str = ..., y: str = ..., z: str = ...) -> SharpDX.Vector3: ...
    @staticmethod
    def GetChildVector4Attributes(node: Any, name: str, x: str = ..., y: str = ..., z: str = ..., w: str = ...) -> SharpDX.Vector4: ...
    @staticmethod
    def GetEnumValue(val: str) -> T: ...
    @staticmethod
    def GetFloatAttribute(node: Any, attribute: str) -> float: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetIntAttribute(node: Any, attribute: str) -> int: ...
    @staticmethod
    def GetMatrix(node: Any) -> SharpDX.Matrix: ...
    @staticmethod
    def GetRawByteArray(node: Any, fromBase: int = ...) -> list[int]: ...
    @staticmethod
    def GetRawFloatArray(node: Any) -> list[float]: ...
    @staticmethod
    def GetRawIntArray(node: Any) -> list[int]: ...
    @staticmethod
    def GetRawUintArray(node: Any) -> list[int]: ...
    @staticmethod
    def GetRawUshortArray(node: Any) -> list[int]: ...
    @staticmethod
    def GetRawVector2Array(node: Any) -> list[SharpDX.Vector2]: ...
    @staticmethod
    def GetRawVector3Array(node: Any) -> list[SharpDX.Vector3]: ...
    @staticmethod
    def GetRawVector4Array(node: Any) -> list[SharpDX.Vector4]: ...
    @staticmethod
    def GetStringAttribute(node: Any, attribute: str) -> str: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def GetUIntAttribute(node: Any, attribute: str) -> int: ...
    @staticmethod
    def GetULongAttribute(node: Any, attribute: str) -> int: ...
    def ToString(self) -> str: ...

from . import Core
from . import GameFiles
from . import Utils
from . import World