from __future__ import annotations
from typing import Any, ClassVar, TypeVar, overload
import CodeWalker
import SharpDX

T = TypeVar("T")

class AmbientModel:
    Name: str
    NameLower: str
    Probability: float
    VariationsType: str
    Variations: AmbientModelVariation
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Load(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class AmbientModelSet:
    Name: str
    NameLower: str
    NameHash: CodeWalker.GameFiles.MetaHash
    Models: list[AmbientModel]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Load(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class AmbientModelVariation:
    Type: str
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Load(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class AudioPlacement:
    Name: str
    NameHash: CodeWalker.GameFiles.MetaHash
    RelFile: CodeWalker.GameFiles.RelFile
    AmbientZone: CodeWalker.GameFiles.Dat151AmbientZone
    AmbientRule: CodeWalker.GameFiles.Dat151AmbientRule
    StaticEmitter: CodeWalker.GameFiles.Dat151StaticEmitter
    Shape: CodeWalker.GameFiles.Dat151ZoneShape
    ShortTypeName: str
    FullTypeName: str
    InnerPos: SharpDX.Vector3
    InnerMin: SharpDX.Vector3
    InnerMax: SharpDX.Vector3
    InnerRadius: float
    InnerOri: SharpDX.Quaternion
    OuterPos: SharpDX.Vector3
    OuterMin: SharpDX.Vector3
    OuterMax: SharpDX.Vector3
    OuterRadius: float
    OuterOri: SharpDX.Quaternion
    Position: SharpDX.Vector3
    HitboxMin: SharpDX.Vector3
    HitboxMax: SharpDX.Vector3
    Orientation: SharpDX.Quaternion
    OrientationInv: SharpDX.Quaternion
    HitSphereRad: float
    @overload
    def __init__(self, rel: CodeWalker.GameFiles.RelFile, zone: CodeWalker.GameFiles.Dat151AmbientZone) -> None: ...
    @overload
    def __init__(self, rel: CodeWalker.GameFiles.RelFile, rule: CodeWalker.GameFiles.Dat151AmbientRule) -> None: ...
    @overload
    def __init__(self, rel: CodeWalker.GameFiles.RelFile, emitter: CodeWalker.GameFiles.Dat151StaticEmitter) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetNameString(self) -> str: ...
    def GetType(self) -> Any: ...
    def SetOrientation(self, ori: SharpDX.Quaternion) -> None: ...
    def SetPosition(self, pos: SharpDX.Vector3) -> None: ...
    def ToString(self) -> str: ...
    def UpdateFromAmbientRule(self) -> None: ...
    def UpdateFromAmbientZone(self) -> None: ...
    def UpdateFromStaticEmitter(self) -> None: ...

class AudioZones:
    Inited: bool
    GameFileCache: CodeWalker.GameFiles.GameFileCache
    PlacementsDict: dict[CodeWalker.GameFiles.RelFile, list[AudioPlacement]]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def FindPlacement(self, relfile: CodeWalker.GameFiles.RelFile, reldata: CodeWalker.GameFiles.Dat151RelData) -> AudioPlacement: ...
    def GetHashCode(self) -> int: ...
    def GetPlacements(self, relfiles: list[CodeWalker.GameFiles.RelFile], placements: list[AudioPlacement]) -> None: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any) -> None: ...
    def ToString(self) -> str: ...

class BaseWaterQuad:
    xmlNodeIndex: int
    minX: float
    maxX: float
    minY: float
    maxY: float
    z: float | None
    BSCenter: SharpDX.Vector3
    BSRadius: float
    def CalcBS(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any, index: int) -> None: ...
    def ToString(self) -> str: ...

class Camera:
    TargetRotation: SharpDX.Vector3
    CurrentRotation: SharpDX.Vector3
    Smoothness: float
    Sensitivity: float
    TargetDistance: float
    CurrentDistance: float
    ZoomCurrentTime: float
    ZoomTargetTime: float
    ZoomVelocity: float
    ZoomSpeed: float
    Width: float
    Height: float
    FieldOfView: float
    FieldOfViewFactor: float
    AspectRatio: float
    ZNear: float
    ZFar: float
    FollowEntity: Entity
    LocalLookAt: SharpDX.Vector3
    VOffset: float
    UpdateProj: bool
    IsMapView: bool
    IsOrthographic: bool
    OrthographicSize: float
    OrthographicTargetSize: float
    ProjMatrix: SharpDX.Matrix
    Position: SharpDX.Vector3
    UpDirection: SharpDX.Vector3
    ViewDirection: SharpDX.Vector3
    ViewQuaternion: SharpDX.Quaternion
    ViewInvQuaternion: SharpDX.Quaternion
    ViewMatrix: SharpDX.Matrix
    ViewInvMatrix: SharpDX.Matrix
    ViewProjMatrix: SharpDX.Matrix
    ViewProjInvMatrix: SharpDX.Matrix
    ViewFrustum: Frustum
    MouseRayNear: SharpDX.Vector3
    MouseRayFar: SharpDX.Vector3
    MouseRay: SharpDX.Ray
    def __init__(self, smoothness: float, sensitivity: float, fov: float) -> None: ...
    def ControllerRotate(self, x: float, y: float, elapsed: float) -> None: ...
    def ControllerZoom(self, z: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def MouseRotate(self, x: int, y: int) -> None: ...
    def MouseZoom(self, z: int) -> None: ...
    def OnWindowResize(self, w: int, h: int) -> None: ...
    def SetFollowEntity(self, e: Entity) -> None: ...
    def SetMousePosition(self, x: int, y: int) -> None: ...
    def ToString(self) -> str: ...
    def Update(self, elapsed: float) -> None: ...

class CloudAnimOverrides:
    UVOffset1: SharpDX.Vector2
    UVOffset2: SharpDX.Vector2
    UVOffset3: SharpDX.Vector2
    RescaleUV1: SharpDX.Vector2
    RescaleUV2: SharpDX.Vector2
    RescaleUV3: SharpDX.Vector2
    cloudLayerAnimScale1: SharpDX.Vector2
    cloudLayerAnimScale2: SharpDX.Vector2
    cloudLayerAnimScale3: SharpDX.Vector2
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class CloudAnimSetting:
    Name: str
    DisplayName: str
    MinValue: float
    MaxValue: float
    DefaultValue: float
    CurrentValue: float
    def __init__(self, name: str, displayname: str, minval: float, maxval: float, defaultval: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class CloudHatFrag:
    Position: SharpDX.Vector3
    Rotation: SharpDX.Vector3
    Scale: SharpDX.Vector3
    Name: str
    Layers: list[CloudHatFragLayer]
    TransitionAlphaRange: float
    TransitionMidPoint: float
    Enabled: bool
    AngularVelocity: SharpDX.Vector3
    AnimBlendWeights: SharpDX.Vector3
    UVVelocity: list[SharpDX.Vector2]
    AnimMode: list[int]
    ShowLayer: list[bool]
    EnableAnimations: bool
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, xml: Any) -> None: ...
    def ToString(self) -> str: ...

class CloudHatFragLayer:
    Filename: str
    CostFactor: float
    RotationScale: float
    CamPositionScalerAdjust: float
    TransitionInTimePercent: float
    TransitionOutTimePercent: float
    TransitionInDelayPercent: float
    TransitionOutDelayPercent: float
    HeightTigger: float
    HeightFadeRange: float
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, xml: Any) -> None: ...
    def ToString(self) -> str: ...

class CloudHatManager:
    CloudHatFrags: list[CloudHatFrag]
    DesiredTransitionTimeSec: float
    CamPositionScaler: SharpDX.Vector3
    AltitudeScrollScaler: float
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def FindFrag(self, name: str) -> CloudHatFrag: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, xml: Any) -> None: ...
    def ToString(self) -> str: ...

class CloudSettingsMap:
    KeyframeTimes: list[float]
    SettingsMap: dict[str, CloudSettingsMapItem]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, xml: Any) -> None: ...
    def ToString(self) -> str: ...

class CloudSettingsMapCloudList:
    Probability: list[int]
    Bits: list[int]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, xml: Any) -> None: ...
    def ToString(self) -> str: ...

class CloudSettingsMapItem:
    Name: str
    CloudList: CloudSettingsMapCloudList
    CloudColor: CloudSettingsMapKeyData
    CloudLightColor: CloudSettingsMapKeyData
    CloudAmbientColor: CloudSettingsMapKeyData
    CloudSkyColor: CloudSettingsMapKeyData
    CloudBounceColor: CloudSettingsMapKeyData
    CloudEastColor: CloudSettingsMapKeyData
    CloudWestColor: CloudSettingsMapKeyData
    CloudScaleFillColors: CloudSettingsMapKeyData
    CloudDensityShift_Scale_ScatteringConst_Scale: CloudSettingsMapKeyData
    CloudPiercingLightPower_Strength_NormalStrength_Thickness: CloudSettingsMapKeyData
    CloudScaleDiffuseFillAmbient_WrapAmount: CloudSettingsMapKeyData
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, xml: Any) -> None: ...
    def ToString(self) -> str: ...

class CloudSettingsMapKeyData:
    numKeyEntries: int
    keyEntryData: dict[float, SharpDX.Vector4]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, xml: Any) -> None: ...
    def ToString(self) -> str: ...

class Clouds:
    AnimSettings: dict[str, CloudAnimSetting]
    Inited: bool
    Weather: Weather
    Timecycle: Timecycle
    AnimOverrides: CloudAnimOverrides
    HatManager: CloudHatManager
    SettingsMap: CloudSettingsMap
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any, weather: Weather) -> None: ...
    def ToString(self) -> str: ...
    def Update(self, elapsed: float) -> None: ...

class ConditionalAnimsGroup:
    OuterXml: str
    Name: str
    NameLower: str
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Load(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class Entity:
    Space: Space
    EntityDef: CodeWalker.GameFiles.YmapEntityDef
    Radius: float
    Center: SharpDX.Vector3
    Position: SharpDX.Vector3
    Orientation: SharpDX.Quaternion
    OrientationInv: SharpDX.Quaternion
    Mass: float
    MomentOfInertia: SharpDX.Matrix
    Momentum: SharpDX.Vector3
    Velocity: SharpDX.Vector3
    AngularMomentum: SharpDX.Vector3
    AngularVelocity: SharpDX.Vector3
    WasColliding: bool
    EnableCollisions: bool
    Enabled: bool
    Lifetime: float
    Age: float
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def PreUpdate(self, elapsed: float) -> None: ...
    def ToString(self) -> str: ...

class Frustum:
    Planes: list[SharpDX.Plane]
    Position: SharpDX.Vector3
    def __init__(self) -> None: ...
    def ContainsAABBNoClip(self, cen: SharpDX.Vector3, e: SharpDX.Vector3) -> bool: ...
    def ContainsAABBNoClipNoOpt(self, bmin: SharpDX.Vector3, bmax: SharpDX.Vector3) -> bool: ...
    def ContainsAABBNoFrontClipNoOpt(self, bmin: SharpDX.Vector3, bmax: SharpDX.Vector3) -> bool: ...
    def ContainsSphereNoClipNoOpt(self, c: SharpDX.Vector3, r: float) -> bool: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def Update(self, vp: SharpDX.Matrix) -> None: ...

class Heightmaps:
    Inited: bool
    GameFileCache: CodeWalker.GameFiles.GameFileCache
    HeightmapFiles: list[CodeWalker.GameFiles.HeightmapFile]
    NodePositions: list[SharpDX.Vector4]
    TriangleVerts: list[CodeWalker.GameFiles.EditorVertex]
    def __init__(self) -> None: ...
    def BuildVertices(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetNodePositions(self) -> list[SharpDX.Vector4]: ...
    def GetPathVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetTriangleVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any) -> None: ...
    def ToString(self) -> str: ...

class Ped:
    Name: str
    NameHash: CodeWalker.GameFiles.MetaHash
    InitData: CodeWalker.GameFiles.CPedModelInfo__InitData
    Ydd: CodeWalker.GameFiles.YddFile
    Ytd: CodeWalker.GameFiles.YtdFile
    Yld: CodeWalker.GameFiles.YldFile
    Ycd: CodeWalker.GameFiles.YcdFile
    Yed: CodeWalker.GameFiles.YedFile
    Yft: CodeWalker.GameFiles.YftFile
    Ymt: CodeWalker.GameFiles.PedFile
    DrawableFilesDict: dict[CodeWalker.GameFiles.MetaHash, CodeWalker.GameFiles.RpfFileEntry]
    TextureFilesDict: dict[CodeWalker.GameFiles.MetaHash, CodeWalker.GameFiles.RpfFileEntry]
    ClothFilesDict: dict[CodeWalker.GameFiles.MetaHash, CodeWalker.GameFiles.RpfFileEntry]
    DrawableFiles: list[CodeWalker.GameFiles.RpfFileEntry]
    TextureFiles: list[CodeWalker.GameFiles.RpfFileEntry]
    ClothFiles: list[CodeWalker.GameFiles.RpfFileEntry]
    AnimClip: CodeWalker.GameFiles.ClipMapEntry
    Expression: CodeWalker.GameFiles.Expression
    DrawableNames: list[str]
    Drawables: list[CodeWalker.GameFiles.Drawable]
    Textures: list[CodeWalker.GameFiles.Texture]
    Expressions: list[CodeWalker.GameFiles.Expression]
    Clothes: list[CodeWalker.GameFiles.ClothInstance]
    EnableRootMotion: bool
    Skeleton: CodeWalker.GameFiles.Skeleton
    Position: SharpDX.Vector3
    Rotation: SharpDX.Quaternion
    RenderEntity: CodeWalker.GameFiles.YmapEntityDef
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def Init(self, name: str, gfc: CodeWalker.GameFiles.GameFileCache) -> None: ...
    @overload
    def Init(self, pedhash: CodeWalker.GameFiles.MetaHash, gfc: CodeWalker.GameFiles.GameFileCache) -> None: ...
    def LoadDefaultComponents(self, gfc: CodeWalker.GameFiles.GameFileCache) -> None: ...
    @overload
    def SetComponentDrawable(self, index: int, name: str, tex: str, gfc: CodeWalker.GameFiles.GameFileCache) -> None: ...
    @overload
    def SetComponentDrawable(self, index: int, drawbl: int, alt: int, tex: int, gfc: CodeWalker.GameFiles.GameFileCache) -> None: ...
    def ToString(self) -> str: ...
    def UpdateEntity(self) -> None: ...

class PedEntity:
    ControlMovement: SharpDX.Vector2
    ControlJump: bool
    ControlBoost: bool
    ForwardVec: SharpDX.Vector3
    CameraOrientation: SharpDX.Quaternion
    CameraEntity: Entity
    OnGround: bool
    Space: Space
    EntityDef: CodeWalker.GameFiles.YmapEntityDef
    Radius: float
    Center: SharpDX.Vector3
    Position: SharpDX.Vector3
    Orientation: SharpDX.Quaternion
    OrientationInv: SharpDX.Quaternion
    Mass: float
    MomentOfInertia: SharpDX.Matrix
    Momentum: SharpDX.Vector3
    Velocity: SharpDX.Vector3
    AngularMomentum: SharpDX.Vector3
    AngularVelocity: SharpDX.Vector3
    WasColliding: bool
    EnableCollisions: bool
    Enabled: bool
    Lifetime: float
    Age: float
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def PreUpdate(self, elapsed: float) -> None: ...
    def ToString(self) -> str: ...

class PopZone:
    NameLabel: str
    Name: str
    Boxes: list[PopZoneBox]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class PopZoneBox:
    ID: str
    Box: SharpDX.BoundingBox
    NameLabel: str
    UnkVal: float
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, iplline: str) -> None: ...
    def ToString(self) -> str: ...

class PopZones:
    Inited: bool
    GameFileCache: CodeWalker.GameFiles.GameFileCache
    Groups: dict[str, PopZone]
    TriangleVerts: list[CodeWalker.GameFiles.EditorVertex]
    def __init__(self) -> None: ...
    def BuildVertices(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetNodePositions(self) -> list[SharpDX.Vector4]: ...
    def GetPathVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetTriangleVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any) -> None: ...
    def ToString(self) -> str: ...

class ScenarioNode:
    Ymt: CodeWalker.GameFiles.YmtFile
    Region: CodeWalker.GameFiles.MCScenarioPointRegion
    MyPoint: CodeWalker.GameFiles.MCScenarioPoint
    LoadSavePoint: CodeWalker.GameFiles.MCExtensionDefSpawnPoint
    Cluster: CodeWalker.GameFiles.MCScenarioPointCluster
    ClusterMyPoint: CodeWalker.GameFiles.MCScenarioPoint
    ClusterLoadSavePoint: CodeWalker.GameFiles.MCExtensionDefSpawnPoint
    Entity: CodeWalker.GameFiles.MCScenarioEntityOverride
    EntityPoint: CodeWalker.GameFiles.MCExtensionDefSpawnPoint
    ChainingNode: CodeWalker.GameFiles.MCScenarioChainingNode
    Position: SharpDX.Vector3
    Orientation: SharpDX.Quaternion
    ShortTypeName: str
    FullTypeName: str
    MedTypeName: str
    StringText: str
    def __init__(self, ymt: CodeWalker.GameFiles.YmtFile) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def SetOrientation(self, orientation: SharpDX.Quaternion) -> None: ...
    def SetPosition(self, position: SharpDX.Vector3) -> None: ...
    def ToString(self) -> str: ...

class ScenarioRegion:
    PathVerts: list[CodeWalker.GameFiles.EditorVertex]
    TriangleVerts: list[CodeWalker.GameFiles.EditorVertex]
    NodePositions: list[SharpDX.Vector4]
    Ymt: CodeWalker.GameFiles.YmtFile
    Region: CodeWalker.GameFiles.MCScenarioPointRegion
    Nodes: list[ScenarioNode]
    BVH: CodeWalker.GameFiles.PathBVH
    Loaded: bool
    def __init__(self) -> None: ...
    def AddNode(self, copy: ScenarioNode = ...) -> ScenarioNode: ...
    def BuildBVH(self) -> None: ...
    def BuildNodes(self) -> None: ...
    def BuildVertices(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetNodePositions(self) -> list[SharpDX.Vector4]: ...
    def GetPathVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetTriangleVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetType(self) -> Any: ...
    def Load(self, ymt: CodeWalker.GameFiles.YmtFile) -> None: ...
    def LoadTypes(self) -> None: ...
    def RebuildAccelGrid(self) -> None: ...
    def RebuildChains(self) -> None: ...
    def RebuildLookUps(self) -> None: ...
    def RemoveChain(self, chain: CodeWalker.GameFiles.MCScenarioChain, delpoints: bool) -> bool: ...
    def RemoveCluster(self, cluster: CodeWalker.GameFiles.MCScenarioPointCluster, delpoints: bool) -> bool: ...
    def RemoveEntity(self, entity: CodeWalker.GameFiles.MCScenarioEntityOverride) -> bool: ...
    def RemoveNode(self, node: ScenarioNode) -> bool: ...
    def Save(self) -> list[int]: ...
    def ToString(self) -> str: ...

class ScenarioType:
    OuterXml: str
    Name: str
    NameLower: str
    NameHash: CodeWalker.GameFiles.MetaHash
    IsVehicle: bool
    VehicleModelSet: str
    VehicleModelSetHash: CodeWalker.GameFiles.MetaHash
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Load(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class ScenarioTypeGroup:
    OuterXml: str
    Name: str
    NameLower: str
    NameHash: CodeWalker.GameFiles.MetaHash
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Load(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class ScenarioTypePlayAnims:
    OuterXml: str
    Name: str
    NameLower: str
    NameHash: CodeWalker.GameFiles.MetaHash
    IsVehicle: bool
    VehicleModelSet: str
    VehicleModelSetHash: CodeWalker.GameFiles.MetaHash
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Load(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class ScenarioTypeRef:
    Name: str
    NameLower: str
    NameHash: CodeWalker.GameFiles.MetaHash
    IsVehicle: bool
    VehicleModelSet: str
    VehicleModelSetHash: CodeWalker.GameFiles.MetaHash
    IsGroup: bool
    Type: ScenarioType
    Group: ScenarioTypeGroup
    @overload
    def __init__(self, type: ScenarioType) -> None: ...
    @overload
    def __init__(self, group: ScenarioTypeGroup) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ScenarioTypes:
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetAnimGroup(self, hash: int) -> ConditionalAnimsGroup: ...
    def GetAnimGroups(self) -> list[ConditionalAnimsGroup]: ...
    def GetHashCode(self) -> int: ...
    def GetPedModelSet(self, hash: int) -> AmbientModelSet: ...
    def GetPedModelSets(self) -> list[AmbientModelSet]: ...
    def GetPropSet(self, hash: int) -> AmbientModelSet: ...
    def GetPropSets(self) -> list[AmbientModelSet]: ...
    def GetScenarioType(self, hash: int) -> ScenarioType: ...
    def GetScenarioTypeGroup(self, hash: int) -> ScenarioTypeGroup: ...
    def GetScenarioTypeGroups(self) -> list[ScenarioTypeGroup]: ...
    def GetScenarioTypeRef(self, hash: int) -> ScenarioTypeRef: ...
    def GetScenarioTypeRefs(self) -> list[ScenarioTypeRef]: ...
    def GetScenarioTypes(self) -> list[ScenarioType]: ...
    def GetType(self) -> Any: ...
    def GetVehicleModelSet(self, hash: int) -> AmbientModelSet: ...
    def GetVehicleModelSets(self) -> list[AmbientModelSet]: ...
    def Load(self, gfc: CodeWalker.GameFiles.GameFileCache) -> None: ...
    def ToString(self) -> str: ...

class Scenarios:
    Timecycle: Timecycle
    GameFileCache: CodeWalker.GameFiles.GameFileCache
    ScenarioTypes: ClassVar[ScenarioTypes]
    ScenarioRegions: list[CodeWalker.GameFiles.YmtFile]
    Inited: bool
    def __init__(self) -> None: ...
    @staticmethod
    def EnsureScenarioTypes(gfc: CodeWalker.GameFiles.GameFileCache) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any, timecycle: Timecycle) -> None: ...
    def ToString(self) -> str: ...

class Space:
    TemporaryEntities: Any
    PersistentEntities: Any
    EnabledEntities: list[Entity]
    MapDataStore: SpaceMapDataStore
    BoundsStore: SpaceBoundsStore
    Inited: bool
    NodeGrid: SpaceNodeGrid
    NavGrid: SpaceNavGrid
    Collisions: list[SpaceEntityCollision]
    def __init__(self) -> None: ...
    def AddPersistentEntity(self, e: Entity) -> None: ...
    def AddTemporaryEntity(self, e: Entity) -> None: ...
    def BuildYndData(self, ynd: CodeWalker.GameFiles.YndFile, tverts: list[CodeWalker.GameFiles.EditorVertex] = ..., tlinks: list[CodeWalker.GameFiles.YndLink] = ..., nlinks: list[CodeWalker.GameFiles.YndLink] = ...) -> None: ...
    def BuildYndJuncs(self, ynd: CodeWalker.GameFiles.YndFile) -> None: ...
    def BuildYndLinks(self, ynd: CodeWalker.GameFiles.YndFile, tlinks: list[CodeWalker.GameFiles.YndLink] = ..., nlinks: list[CodeWalker.GameFiles.YndLink] = ...) -> None: ...
    def BuildYndVerts(self, ynd: CodeWalker.GameFiles.YndFile, selectedNodes: list[CodeWalker.GameFiles.YndNode], tverts: list[CodeWalker.GameFiles.EditorVertex] = ...) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def FindFirstCollision(self, e: Entity, elapsed: float) -> SpaceEntityCollision: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def GetVisibleBounds(self, cam: Camera, gridrange: int, layers: list[bool], boundslist: list[CodeWalker.GameFiles.BoundsStoreItem]) -> None: ...
    def GetVisibleYmaps(self, cam: Camera, hour: int, weather: CodeWalker.GameFiles.MetaHash, ymaps: dict[CodeWalker.GameFiles.MetaHash, CodeWalker.GameFiles.YmapFile]) -> None: ...
    def GetVisibleYnds(self, cam: Camera, ynds: list[CodeWalker.GameFiles.YndFile]) -> None: ...
    def GetVisibleYnvs(self, cam: Camera, gridrange: int, ynvs: list[CodeWalker.GameFiles.YnvFile]) -> None: ...
    def GetYndFilesThatDependOnYndFile(self, file: CodeWalker.GameFiles.YndFile) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any) -> None: ...
    def MoveYndArea(self, ynd: CodeWalker.GameFiles.YndFile, desiredX: int, desiredY: int) -> None: ...
    def PatchYndFile(self, ynd: CodeWalker.GameFiles.YndFile) -> None: ...
    def RayIntersect(self, ray: SharpDX.Ray, maxdist: float = ..., layers: list[bool] = ...) -> SpaceRayIntersectResult: ...
    def RayIntersectEntity(self, ray: SharpDX.Ray, ent: CodeWalker.GameFiles.YmapEntityDef, maxdist: float = ...) -> SpaceRayIntersectResult: ...
    def RayIntersectInterior(self, ray: SharpDX.Ray, mlo: CodeWalker.GameFiles.YmapEntityDef, maxdist: float = ...) -> SpaceRayIntersectResult: ...
    def RecalculateAllYndIndices(self) -> None: ...
    def RemovePersistentEntity(self, e: Entity) -> None: ...
    def SphereIntersect(self, sph: SharpDX.BoundingSphere, layers: list[bool] = ...) -> SpaceSphereIntersectResult: ...
    def SphereIntersectEntity(self, sph: SharpDX.BoundingSphere, ent: CodeWalker.GameFiles.YmapEntityDef) -> SpaceSphereIntersectResult: ...
    def SphereIntersectInterior(self, sph: SharpDX.BoundingSphere, mlo: CodeWalker.GameFiles.YmapEntityDef) -> SpaceSphereIntersectResult: ...
    def ToString(self) -> str: ...
    def Update(self, elapsed: float) -> None: ...

class SpaceBoundsKey:
    Name: CodeWalker.GameFiles.MetaHash
    Position: SharpDX.Vector3
    def __init__(self, name: CodeWalker.GameFiles.MetaHash, position: SharpDX.Vector3) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class SpaceBoundsStore:
    RootNode: SpaceBoundsStoreNode
    SplitThreshold: int
    VisibleItems: list[CodeWalker.GameFiles.BoundsStoreItem]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    @overload
    def GetItems(self, min: SharpDX.Vector3, max: SharpDX.Vector3, layers: list[bool] = ...) -> list[CodeWalker.GameFiles.BoundsStoreItem]: ...
    @overload
    def GetItems(self, ray: SharpDX.Ray, layers: list[bool] = ...) -> list[CodeWalker.GameFiles.BoundsStoreItem]: ...
    def GetType(self) -> Any: ...
    def Init(self, items: list[CodeWalker.GameFiles.BoundsStoreItem]) -> None: ...
    def ToString(self) -> str: ...

class SpaceBoundsStoreNode:
    Owner: SpaceBoundsStore
    Children: list[SpaceBoundsStoreNode]
    Items: list[CodeWalker.GameFiles.BoundsStoreItem]
    BBMin: SharpDX.Vector3
    BBMax: SharpDX.Vector3
    Depth: int
    def __init__(self) -> None: ...
    def Add(self, item: CodeWalker.GameFiles.BoundsStoreItem) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    @overload
    def GetItems(self, min: SharpDX.Vector3, max: SharpDX.Vector3, items: list[CodeWalker.GameFiles.BoundsStoreItem], layers: list[bool] = ...) -> None: ...
    @overload
    def GetItems(self, ray: SharpDX.Ray, items: list[CodeWalker.GameFiles.BoundsStoreItem], layers: list[bool] = ...) -> None: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def TrySplit(self, threshold: int) -> None: ...

class SpaceEntityCollision:
    Entity: Entity
    Entity2: Entity
    SphereHit: SpaceSphereIntersectResult
    PrePos: SharpDX.Vector3
    PreT: float
    HitT: float
    HitPos: SharpDX.Vector3
    HitRot: SharpDX.Quaternion
    HitVel: SharpDX.Vector3
    HitAngVel: SharpDX.Vector3
    HitNumber: int
    Hit: bool
    HitVelDir: SharpDX.Vector3
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class SpaceMapDataStore:
    RootNode: SpaceMapDataStoreNode
    SplitThreshold: int
    VisibleItems: list[CodeWalker.GameFiles.MapDataStoreNode]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    @overload
    def GetItems(self, p: SharpDX.Vector3) -> list[CodeWalker.GameFiles.MapDataStoreNode]: ...
    @overload
    def GetItems(self, min: SharpDX.Vector3, max: SharpDX.Vector3) -> list[CodeWalker.GameFiles.MapDataStoreNode]: ...
    @overload
    def GetItems(self, ray: SharpDX.Ray) -> list[CodeWalker.GameFiles.MapDataStoreNode]: ...
    def GetType(self) -> Any: ...
    def Init(self, rootnodes: list[CodeWalker.GameFiles.MapDataStoreNode]) -> None: ...
    def ToString(self) -> str: ...

class SpaceMapDataStoreNode:
    Owner: SpaceMapDataStore
    Children: list[SpaceMapDataStoreNode]
    Items: list[CodeWalker.GameFiles.MapDataStoreNode]
    BBMin: SharpDX.Vector3
    BBMax: SharpDX.Vector3
    Depth: int
    def __init__(self) -> None: ...
    def Add(self, item: CodeWalker.GameFiles.MapDataStoreNode) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    @overload
    def GetItems(self, p: SharpDX.Vector3, items: list[CodeWalker.GameFiles.MapDataStoreNode]) -> None: ...
    @overload
    def GetItems(self, min: SharpDX.Vector3, max: SharpDX.Vector3, items: list[CodeWalker.GameFiles.MapDataStoreNode]) -> None: ...
    @overload
    def GetItems(self, ray: SharpDX.Ray, items: list[CodeWalker.GameFiles.MapDataStoreNode]) -> None: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def TrySplit(self, threshold: int) -> None: ...

class SpaceNavGrid:
    Cells: list[SpaceNavGridCell]
    CellSize: float
    CellSizeInv: float
    CellCountX: int
    CellCountY: int
    CornerX: float
    CornerY: float
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetCell(self, id: int) -> SpaceNavGridCell: ...
    @overload
    def GetCell(self, g: CodeWalker.Vector2I) -> SpaceNavGridCell: ...
    @overload
    def GetCell(self, p: SharpDX.Vector3) -> SpaceNavGridCell: ...
    def GetCellMax(self, cell: SpaceNavGridCell) -> SharpDX.Vector3: ...
    def GetCellMin(self, cell: SpaceNavGridCell) -> SharpDX.Vector3: ...
    def GetCellPos(self, p: SharpDX.Vector3) -> CodeWalker.Vector2I: ...
    def GetCellRel(self, p: SharpDX.Vector3) -> SharpDX.Vector3: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class SpaceNavGridCell:
    X: int
    Y: int
    ID: int
    FileX: int
    FileY: int
    YnvEntry: CodeWalker.GameFiles.RpfResourceFileEntry
    Ynv: CodeWalker.GameFiles.YnvFile
    def __init__(self, x: int, y: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class SpaceNodeGrid:
    Cells: list[SpaceNodeGridCell]
    CellSize: float
    CellSizeInv: float
    CellCountX: int
    CellCountY: int
    CornerX: float
    CornerY: float
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetCell(self, id: int) -> SpaceNodeGridCell: ...
    def GetCellForPosition(self, position: SharpDX.Vector3) -> SpaceNodeGridCell: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def GetYndNode(self, areaid: int, nodeid: int) -> CodeWalker.GameFiles.YndNode: ...
    def ToString(self) -> str: ...
    def UpdateYnd(self, ynd: CodeWalker.GameFiles.YndFile) -> None: ...

class SpaceNodeGridCell:
    X: int
    Y: int
    ID: int
    Ynd: CodeWalker.GameFiles.YndFile
    def __init__(self, x: int, y: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class SpaceRayIntersectResult:
    Hit: bool
    HitDist: float
    HitVertex: CodeWalker.GameFiles.BoundVertexRef
    HitPolygon: CodeWalker.GameFiles.BoundPolygon
    HitBounds: CodeWalker.GameFiles.Bounds
    HitYbn: CodeWalker.GameFiles.YbnFile
    HitEntity: CodeWalker.GameFiles.YmapEntityDef
    Position: SharpDX.Vector3
    Normal: SharpDX.Vector3
    TestedNodeCount: int
    TestedPolyCount: int
    TestComplete: bool
    Material: CodeWalker.GameFiles.BoundMaterial_s
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def TryUpdate(self, r: SpaceRayIntersectResult) -> None: ...

class SpaceSphereIntersectResult:
    Hit: bool
    HitDist: float
    HitPolygon: CodeWalker.GameFiles.BoundPolygon
    Position: SharpDX.Vector3
    Normal: SharpDX.Vector3
    TestedNodeCount: int
    TestedPolyCount: int
    TestComplete: bool
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def TryUpdate(self, r: SpaceSphereIntersectResult) -> None: ...

class Timecycle:
    sun_roll: float
    sun_yaw: float
    moon_roll: float
    moon_wobble_freq: float
    moon_wobble_amp: float
    moon_wobble_offset: float
    Samples: list[TimecycleSample]
    Regions: list[str]
    CurrentHour: float
    CurrentSampleIndex: int
    CurrentSampleBlend: float
    NextSampleBlend: float
    CurrentSunDirection: SharpDX.Vector3
    CurrentMoonDirection: SharpDX.Vector3
    IsNightTime: bool
    Inited: bool
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any) -> None: ...
    def SetTime(self, hour: float) -> None: ...
    def ToString(self) -> str: ...

class TimecycleMod:
    name: str
    nameHash: int
    numMods: int
    userFlags: int
    Values: list[TimecycleModValue]
    Dict: dict[str, TimecycleModValue]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class TimecycleModValue:
    name: str
    value1: float
    value2: float
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class TimecycleMods:
    Dict: dict[int, TimecycleMod]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any) -> None: ...
    def ToString(self) -> str: ...

class TimecycleSample:
    name: str
    hour: float
    duration: float
    uw_tc_mod: str
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class TrainTrack:
    filename: str
    trainConfigName: str
    isPingPongTrack: bool
    stopsAtStations: bool
    MPstopsAtStations: bool
    speed: float
    brakingDist: float
    Nodes: list[TrainTrackNode]
    NodeCount: int
    StationCount: int
    LinkedVerts: list[CodeWalker.GameFiles.EditorVertex]
    NodePositions: list[SharpDX.Vector4]
    BVH: CodeWalker.GameFiles.PathBVH
    NodesString: str
    RpfFileEntry: CodeWalker.GameFiles.RpfFileEntry
    Name: str
    FilePath: str
    HasChanged: bool
    Loaded: bool
    def __init__(self) -> None: ...
    def AddNode(self, afternode: TrainTrackNode = ...) -> TrainTrackNode: ...
    def BuildBVH(self) -> None: ...
    def BuildVertices(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetNodePositions(self) -> list[SharpDX.Vector4]: ...
    def GetPathVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetTriangleVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetType(self) -> Any: ...
    @overload
    def Load(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, node: Any) -> None: ...
    @overload
    def Load(self, data: list[int]) -> None: ...
    @overload
    def Load(self, trackstr: str) -> None: ...
    def RemoveNode(self, node: TrainTrackNode) -> bool: ...
    def Save(self) -> list[int]: ...
    def SetNameFromFilename(self) -> None: ...
    def ToString(self) -> str: ...
    def UpdateBvhForNode(self, node: TrainTrackNode) -> None: ...

class TrainTrackNode:
    Position: SharpDX.Vector3
    NodeType: int
    Track: TrainTrack
    Index: int
    Links: list[TrainTrackNode]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetColour(self) -> int: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def SetPosition(self, pos: SharpDX.Vector3) -> None: ...
    def ToString(self) -> str: ...

class Trains:
    TrainTracks: list[TrainTrack]
    Inited: bool
    GameFileCache: CodeWalker.GameFiles.GameFileCache
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any) -> None: ...
    def ToString(self) -> str: ...

class Vehicle:
    Name: str
    NameHash: CodeWalker.GameFiles.MetaHash
    ModelHash: CodeWalker.GameFiles.MetaHash
    InitData: CodeWalker.GameFiles.VehicleInitData
    Yft: CodeWalker.GameFiles.YftFile
    ConvRoofDict: CodeWalker.GameFiles.YcdFile
    ConvRoofClip: CodeWalker.GameFiles.ClipMapEntry
    DisplayMake: str
    DisplayName: str
    Position: SharpDX.Vector3
    Rotation: SharpDX.Quaternion
    RenderEntity: CodeWalker.GameFiles.YmapEntityDef
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, name: str, gfc: CodeWalker.GameFiles.GameFileCache, hidef: bool = ...) -> None: ...
    def ToString(self) -> str: ...
    def UpdateEntity(self) -> None: ...

class Water:
    Inited: bool
    GameFileCache: CodeWalker.GameFiles.GameFileCache
    WaterQuads: list[WaterQuad]
    CalmingQuads: list[WaterCalmingQuad]
    WaveQuads: list[WaterWaveQuad]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def GetVisibleQuads(self, camera: Camera, allQuads: list[T]) -> list[T]: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any) -> None: ...
    def ToString(self) -> str: ...

class WaterCalmingQuad:
    fDampening: float
    xmlNodeIndex: int
    minX: float
    maxX: float
    minY: float
    maxY: float
    z: float | None
    BSCenter: SharpDX.Vector3
    BSRadius: float
    def __init__(self) -> None: ...
    def CalcBS(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any, index: int) -> None: ...
    def ToString(self) -> str: ...

class WaterQuad:
    Type: int
    IsInvisible: bool
    HasLimitedDepth: bool
    a1: float
    a2: float
    a3: float
    a4: float
    NoStencil: bool
    xmlNodeIndex: int
    minX: float
    maxX: float
    minY: float
    maxY: float
    z: float | None
    BSCenter: SharpDX.Vector3
    BSRadius: float
    def __init__(self) -> None: ...
    def CalcBS(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any, index: int) -> None: ...
    def ToString(self) -> str: ...

class WaterWaveQuad:
    Amplitude: float
    XDirection: float
    YDirection: float
    WaveOrientation: SharpDX.Quaternion
    xmlNodeIndex: int
    minX: float
    maxX: float
    minY: float
    maxY: float
    z: float | None
    BSCenter: SharpDX.Vector3
    BSRadius: float
    def __init__(self) -> None: ...
    def CalcBS(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any, index: int) -> None: ...
    def ToString(self) -> str: ...

class Watermaps:
    Inited: bool
    GameFileCache: CodeWalker.GameFiles.GameFileCache
    WatermapFiles: list[CodeWalker.GameFiles.WatermapFile]
    NodePositions: list[SharpDX.Vector4]
    TriangleVerts: list[CodeWalker.GameFiles.EditorVertex]
    def __init__(self) -> None: ...
    def BuildVertices(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetNodePositions(self) -> list[SharpDX.Vector4]: ...
    def GetPathVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetTriangleVertices(self) -> list[CodeWalker.GameFiles.EditorVertex]: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any) -> None: ...
    def ToString(self) -> str: ...

class Weapon:
    Name: str
    NameHash: CodeWalker.GameFiles.MetaHash
    ModelHash: CodeWalker.GameFiles.MetaHash
    Ydr: CodeWalker.GameFiles.YdrFile
    Drawable: CodeWalker.GameFiles.Drawable
    Position: SharpDX.Vector3
    Rotation: SharpDX.Quaternion
    RenderEntity: CodeWalker.GameFiles.YmapEntityDef
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, name: str, gfc: CodeWalker.GameFiles.GameFileCache, hidef: bool = ...) -> None: ...
    def ToString(self) -> str: ...
    def UpdateEntity(self) -> None: ...

class Weather:
    WeatherGpuFx: dict[str, WeatherGpuFx]
    WeatherTypes: dict[str, WeatherType]
    WeatherCycles: list[WeatherCycle]
    CurrentValues: WeatherValues
    Inited: bool
    CurrentWeatherType: WeatherType
    NextWeatherType: WeatherType
    WeatherChangeTime: float
    CurrentWeatherChangeTime: float
    CurrentWeatherChangeBlend: float
    Region: str
    CurrentWeatherRegion: WeatherCycleKeyframeRegion
    NextWeatherRegion: WeatherCycleKeyframeRegion
    Timecycle: Timecycle
    TimecycleMods: TimecycleMods
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetDynamicRGB(self, rname: str, gname: str, bname: str) -> SharpDX.Vector3: ...
    def GetDynamicRGBA(self, rname: str, gname: str, bname: str, aname: str) -> SharpDX.Vector4: ...
    def GetDynamicValue(self, name: str) -> float: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, updateStatus: Any, timecycle: Timecycle) -> None: ...
    def SetNextWeather(self, name: str) -> None: ...
    def ToString(self) -> str: ...
    def Update(self, elapsed: float) -> None: ...

class WeatherCycle:
    CycleName: str
    TimeMult: float
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class WeatherCycleKeyframeData:
    Name: str
    RegionCount: int
    Regions: dict[str, WeatherCycleKeyframeRegion]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class WeatherCycleKeyframeDataEntry:
    Name: str
    Values: list[float]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class WeatherCycleKeyframeRegion:
    Name: str
    Data: dict[str, WeatherCycleKeyframeDataEntry]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetCurrentValue(self, name: str, sample: int, curblend: float) -> float: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class WeatherGpuFx:
    Name: str
    SystemType: str
    diffuseName: str
    distortionTexture: str
    diffuseSplashName: str
    driveType: str
    windInfluence: float
    gravity: float
    emitterSettingsName: str
    renderSettingsName: str
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Init(self, node: Any) -> None: ...
    def ToString(self) -> str: ...

class WeatherType:
    NameHash: CodeWalker.GameFiles.MetaHash
    Name: str
    Sun: float
    Cloud: float
    WindMin: float
    WindMax: float
    Rain: float
    Snow: float
    SnowMist: float
    Fog: float
    RippleBumpiness: float
    RippleMinBumpiness: float
    RippleMaxBumpiness: float
    RippleBumpinessWindScale: float
    RippleScale: float
    RippleSpeed: float
    RippleVelocityTransfer: float
    OceanBumpiness: float
    DeepOceanScale: float
    OceanNoiseMinAmplitude: float
    OceanWaveAmplitude: float
    ShoreWaveAmplitude: float
    OceanWaveWindScale: float
    ShoreWaveWindScale: float
    OceanWaveMinAmplitude: float
    ShoreWaveMinAmplitude: float
    OceanWaveMaxAmplitude: float
    ShoreWaveMaxAmplitude: float
    OceanFoamIntensity: float
    OceanFoamScale: float
    RippleDisturb: float
    Lightning: float
    Sandstorm: float
    OldSettingName: str
    DropSettingName: str
    MistSettingName: str
    GroundSettingName: str
    TimeCycleFilename: str
    CloudSettingsName: str
    TimeCycleData: WeatherCycleKeyframeData
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetRegion(self, name: str) -> WeatherCycleKeyframeRegion: ...
    def GetType(self) -> Any: ...
    def Init(self, gameFileCache: CodeWalker.GameFiles.GameFileCache, node: Any) -> None: ...
    def ToString(self) -> str: ...

class WeatherValues:
    sunDirection: SharpDX.Vector3
    moonDirection: SharpDX.Vector3
    skyZenithCol: SharpDX.Vector4
    skyZenithTransitionCol: SharpDX.Vector4
    skyZenithTransition: SharpDX.Vector4
    skyAzimuthEastCol: SharpDX.Vector4
    skyAzimuthWestCol: SharpDX.Vector4
    skyAzimuthTransitionCol: SharpDX.Vector4
    skyAzimuthTransition: float
    skyHdr: float
    skyPlane: SharpDX.Vector4
    skySunCol: SharpDX.Vector3
    skySunDiscCol: SharpDX.Vector3
    skySunDiscSize: float
    skySunHdr: float
    skySunMie: SharpDX.Vector3
    skySunInfluenceRadius: float
    skySunScatterInten: float
    skyMoonCol: SharpDX.Vector3
    skyMoonDiscSize: float
    skyMoonIten: float
    skyMoonInfluenceRadius: float
    skyMoonScatterInten: float
    skyStarsIten: float
    lightDirCol: SharpDX.Vector4
    lightDirAmbCol: SharpDX.Vector4
    lightDirAmbIntensityMult: float
    lightDirAmbBounce: float
    lightNaturalAmbDown: SharpDX.Vector4
    lightNaturalAmbUp: SharpDX.Vector4
    lightNaturalAmbUpIntensityMult: float
    lightArtificialIntDown: SharpDX.Vector4
    lightArtificialIntUp: SharpDX.Vector4
    lightArtificialExtDown: SharpDX.Vector4
    lightArtificialExtUp: SharpDX.Vector4
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def Update(self, w: Weather) -> None: ...
