from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload

class FolderBrowser:
    FosPickfolders: ClassVar[int]
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetSelectedPath(self) -> str: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
