schema_version = "1.0.0"
id = "gta_vicho_tools"
version = "1.0.0"
name = "Vicho's Tools"
tagline = "A collection of tools for GTA V modding"
maintainer = "MrVicho13 <vicho0202@gmail.com>"
type = "add-on"
website = "https://vichomodding.gitbook.io/"
tags = ["Animation", "Import-Export", "3D View", "Object", "Mesh", "Material"]
blender_version_min = "4.2.0"


license = ["SPDX:MIT",]

platforms = ["windows-x64",]

wheels = [
    "./wheels/pythonnet-3.0.3-py3-none-any.whl",
    "./wheels/clr_loader-0.2.6-py3-none-any.whl",
    "./wheels/pycparser-2.22-py3-none-any.whl",
    "./wheels/cffi-1.16.0-cp312-cp312-win_amd64.whl"
]

[permissions]
files = "Export Folders and Binary Files (.YTD and .YMAP) to disk"