schema_version = "1.0.0"
id = "gta_vicho_tools"
version = "1.0.1"
name = "Vicho's Tools"
tagline = "A collection of tools for GTA V modding ranging from Textures, Animations, YMAP(S) and more."
maintainer = "MrVicho13 <vicho0202@gmail.com>"
type = "add-on"
website = "https://vichomodding.gitbook.io/main/blender-stuff/recommended-add-ons/modding/vichos-tools"
tags = ["Animation", "Import-Export", "3D View", "Object", "Mesh", "Material"]
blender_version_min = "4.2.0"


license = ["SPDX:MIT",]

platforms = ["windows-x64",]

wheels = [
    "./wheels/cffi-1.17.1-cp311-cp311-win_amd64.whl",
    "./wheels/clr_loader-0.2.7.post0-py3-none-any.whl",
    "./wheels/pycparser-2.22-py3-none-any.whl",
    "./wheels/pythonnet-3.0.5-py3-none-any.whl"
]

[permissions]
files = "Export Folders and Binary Files (.YTD and .YMAP) to disk"