schema_version = "1.0.0"
id = "gta_vicho_tools"
version = "1.0.0"
name = "Vicho's Tools"
tagline = "A collection of tools for GTA V modding"
mantainer = "MrVicho13 <vicho0202@gmail.com>"
type = "add-on"
website = "https://vichomodding.gitbook.io/"
tags = ["Animation", "Import-Export", "3D View", "Object", "Mesh", "Material"]
blender_version_min = "4.2.0"


license = ["SPDX:MIT",]

platforms = ["windows-x64",]

wheels = [
    "./wheel/pythonnet-3.0.3-py3-none-any.whl",
]

[permissions]
files = "Export Folders and Binary Files (.YTD and .YMAP) to disk"