from typing import Iterable

class File:
    @staticmethod
    def Exists(path: str) -> bool: ...
    @staticmethod
    def ReadAllText(path: str) -> str: ...
    @staticmethod
    def WriteAllText(path: str, contents: str) -> None: ...
    @staticmethod
    def ReadAllBytes(path: str) -> bytes: ...
    @staticmethod
    def WriteAllBytes(path: str, bytes: bytes) -> None: ...
    @staticmethod
    def ReadLines(path: str) -> Iterable[str]: ...
    @staticmethod
    def Delete(path: str) -> None: ...
