from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload
import System

T = TypeVar("T")
TAntecedentResult = TypeVar("TAntecedentResult")
TArg1 = TypeVar("TArg1")
TArg2 = TypeVar("TArg2")
TArg3 = TypeVar("TArg3")
TNewResult = TypeVar("TNewResult")
TResult = TypeVar("TResult")

class ConcurrentExclusiveSchedulerPair:
    Completion: Task_
    ConcurrentScheduler: TaskScheduler
    ExclusiveScheduler: TaskScheduler
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, taskScheduler: TaskScheduler) -> None: ...
    @overload
    def __init__(self, taskScheduler: TaskScheduler, maxConcurrencyLevel: int) -> None: ...
    @overload
    def __init__(self, taskScheduler: TaskScheduler, maxConcurrencyLevel: int, maxItemsPerTask: int) -> None: ...
    def Complete(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ConfigureAwaitOptions(IntFlag):
    None_ = 0
    ContinueOnCapturedContext = 1
    SuppressThrowing = 2
    ForceYielding = 4

class Task_:
    Id: int
    CurrentId: ClassVar[int | None]
    Exception: Any
    Status: TaskStatus
    IsCanceled: bool
    IsCompleted: bool
    IsCompletedSuccessfully: bool
    CreationOptions: TaskCreationOptions
    AsyncState: Any
    Factory: ClassVar[TaskFactory_]
    CompletedTask: ClassVar[Task_]
    IsFaulted: bool
    @overload
    def __init__(self, action: Callable[..., None]) -> None: ...
    @overload
    def __init__(self, action: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def __init__(self, action: Callable[..., None], creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def __init__(self, action: Callable[..., None], cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def __init__(self, action: Callable[..., None], state: Any) -> None: ...
    @overload
    def __init__(self, action: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def __init__(self, action: Callable[..., None], state: Any, creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def __init__(self, action: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def ConfigureAwait(self, continueOnCapturedContext: bool) -> Any: ...
    @overload
    def ConfigureAwait(self, options: ConfigureAwaitOptions) -> Any: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None]) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any, continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    @staticmethod
    def Delay(delay: Any) -> Task_: ...
    @overload
    @staticmethod
    def Delay(delay: Any, timeProvider: Any) -> Task_: ...
    @overload
    @staticmethod
    def Delay(delay: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    @staticmethod
    def Delay(delay: Any, timeProvider: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    @staticmethod
    def Delay(millisecondsDelay: int) -> Task_: ...
    @overload
    @staticmethod
    def Delay(millisecondsDelay: int, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    @overload
    @staticmethod
    def FromCanceled(cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    @staticmethod
    def FromCanceled(cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    @staticmethod
    def FromException(exception: Any) -> Task_: ...
    @overload
    @staticmethod
    def FromException(exception: Any) -> Task[TResult]: ...
    @staticmethod
    def FromResult(result: TResult) -> Task[TResult]: ...
    def GetAwaiter(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    @staticmethod
    def Run(action: Callable[..., None]) -> Task_: ...
    @overload
    @staticmethod
    def Run(action: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    @staticmethod
    def Run(function: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    @staticmethod
    def Run(function: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    @staticmethod
    def Run(function: Callable[..., Task_]) -> Task_: ...
    @overload
    @staticmethod
    def Run(function: Callable[..., Task_], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    @staticmethod
    def Run(function: Callable[..., Task[TResult]]) -> Task[TResult]: ...
    @overload
    @staticmethod
    def Run(function: Callable[..., Task[TResult]], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def RunSynchronously(self) -> None: ...
    @overload
    def RunSynchronously(self, scheduler: TaskScheduler) -> None: ...
    @overload
    def Start(self) -> None: ...
    @overload
    def Start(self, scheduler: TaskScheduler) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Wait(self) -> None: ...
    @overload
    def Wait(self, timeout: Any) -> bool: ...
    @overload
    def Wait(self, timeout: Any, cancellationToken: System.Threading.CancellationToken) -> bool: ...
    @overload
    def Wait(self, cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def Wait(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def Wait(self, millisecondsTimeout: int, cancellationToken: System.Threading.CancellationToken) -> bool: ...
    @overload
    @staticmethod
    def WaitAll(tasks: list[Task_]) -> None: ...
    @overload
    @staticmethod
    def WaitAll(tasks: Any) -> None: ...
    @overload
    @staticmethod
    def WaitAll(tasks: list[Task_], timeout: Any) -> bool: ...
    @overload
    @staticmethod
    def WaitAll(tasks: list[Task_], millisecondsTimeout: int) -> bool: ...
    @overload
    @staticmethod
    def WaitAll(tasks: list[Task_], cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    @staticmethod
    def WaitAll(tasks: list[Task_], millisecondsTimeout: int, cancellationToken: System.Threading.CancellationToken) -> bool: ...
    @overload
    @staticmethod
    def WaitAll(tasks: System.Collections.Generic.IEnumerable[Task_], cancellationToken: System.Threading.CancellationToken = ...) -> None: ...
    @overload
    @staticmethod
    def WaitAny(tasks: list[Task_]) -> int: ...
    @overload
    @staticmethod
    def WaitAny(tasks: list[Task_], timeout: Any) -> int: ...
    @overload
    @staticmethod
    def WaitAny(tasks: list[Task_], cancellationToken: System.Threading.CancellationToken) -> int: ...
    @overload
    @staticmethod
    def WaitAny(tasks: list[Task_], millisecondsTimeout: int) -> int: ...
    @overload
    @staticmethod
    def WaitAny(tasks: list[Task_], millisecondsTimeout: int, cancellationToken: System.Threading.CancellationToken) -> int: ...
    @overload
    def WaitAsync(self, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def WaitAsync(self, timeout: Any) -> Task_: ...
    @overload
    def WaitAsync(self, timeout: Any, timeProvider: Any) -> Task_: ...
    @overload
    def WaitAsync(self, timeout: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def WaitAsync(self, timeout: Any, timeProvider: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    @staticmethod
    def WhenAll(tasks: System.Collections.Generic.IEnumerable[Task_]) -> Task_: ...
    @overload
    @staticmethod
    def WhenAll(tasks: list[Task_]) -> Task_: ...
    @overload
    @staticmethod
    def WhenAll(tasks: Any) -> Task_: ...
    @overload
    @staticmethod
    def WhenAll(tasks: System.Collections.Generic.IEnumerable[Task[TResult]]) -> Task[list[TResult]]: ...
    @overload
    @staticmethod
    def WhenAll(tasks: list[Task[TResult]]) -> Task[list[TResult]]: ...
    @overload
    @staticmethod
    def WhenAll(tasks: Any) -> Task[list[TResult]]: ...
    @overload
    @staticmethod
    def WhenAny(tasks: list[Task_]) -> Task[Task_]: ...
    @overload
    @staticmethod
    def WhenAny(tasks: Any) -> Task[Task_]: ...
    @overload
    @staticmethod
    def WhenAny(task1: Task_, task2: Task_) -> Task[Task_]: ...
    @overload
    @staticmethod
    def WhenAny(tasks: System.Collections.Generic.IEnumerable[Task_]) -> Task[Task_]: ...
    @overload
    @staticmethod
    def WhenAny(tasks: list[Task[TResult]]) -> Task[Task[TResult]]: ...
    @overload
    @staticmethod
    def WhenAny(tasks: Any) -> Task[Task[TResult]]: ...
    @overload
    @staticmethod
    def WhenAny(task1: Task[TResult], task2: Task[TResult]) -> Task[Task[TResult]]: ...
    @overload
    @staticmethod
    def WhenAny(tasks: System.Collections.Generic.IEnumerable[Task[TResult]]) -> Task[Task[TResult]]: ...
    @overload
    @staticmethod
    def WhenEach(tasks: list[Task_]) -> System.Collections.Generic.IAsyncEnumerable[Task_]: ...
    @overload
    @staticmethod
    def WhenEach(tasks: Any) -> System.Collections.Generic.IAsyncEnumerable[Task_]: ...
    @overload
    @staticmethod
    def WhenEach(tasks: System.Collections.Generic.IEnumerable[Task_]) -> System.Collections.Generic.IAsyncEnumerable[Task_]: ...
    @overload
    @staticmethod
    def WhenEach(tasks: list[Task[TResult]]) -> System.Collections.Generic.IAsyncEnumerable[Task[TResult]]: ...
    @overload
    @staticmethod
    def WhenEach(tasks: Any) -> System.Collections.Generic.IAsyncEnumerable[Task[TResult]]: ...
    @overload
    @staticmethod
    def WhenEach(tasks: System.Collections.Generic.IEnumerable[Task[TResult]]) -> System.Collections.Generic.IAsyncEnumerable[Task[TResult]]: ...
    @staticmethod
    def Yield() -> Any: ...

class TaskAsyncEnumerableExtensions:
    @overload
    @staticmethod
    def ConfigureAwait(source: Any, continueOnCapturedContext: bool) -> Any: ...
    @overload
    @staticmethod
    def ConfigureAwait(source: System.Collections.Generic.IAsyncEnumerable[T], continueOnCapturedContext: bool) -> Any: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def ToBlockingEnumerable(source: System.Collections.Generic.IAsyncEnumerable[T], cancellationToken: System.Threading.CancellationToken = ...) -> System.Collections.Generic.IEnumerable[T]: ...
    def ToString(self) -> str: ...
    @staticmethod
    def WithCancellation(source: System.Collections.Generic.IAsyncEnumerable[T], cancellationToken: System.Threading.CancellationToken) -> Any: ...

class TaskCanceledException:
    Task: Task_
    CancellationToken: System.Threading.CancellationToken
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any, token: System.Threading.CancellationToken) -> None: ...
    @overload
    def __init__(self, task: Task_) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class TaskCompletionSource_:
    Task: Task_
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def __init__(self, state: Any) -> None: ...
    @overload
    def __init__(self, state: Any, creationOptions: TaskCreationOptions) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def SetCanceled(self) -> None: ...
    @overload
    def SetCanceled(self, cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def SetException(self, exception: Any) -> None: ...
    @overload
    def SetException(self, exceptions: System.Collections.Generic.IEnumerable[Any]) -> None: ...
    def SetFromTask(self, completedTask: Task_) -> None: ...
    def SetResult(self) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def TrySetCanceled(self) -> bool: ...
    @overload
    def TrySetCanceled(self, cancellationToken: System.Threading.CancellationToken) -> bool: ...
    @overload
    def TrySetException(self, exception: Any) -> bool: ...
    @overload
    def TrySetException(self, exceptions: System.Collections.Generic.IEnumerable[Any]) -> bool: ...
    def TrySetFromTask(self, completedTask: Task_) -> bool: ...
    def TrySetResult(self) -> bool: ...

class TaskCompletionSource(Generic[TResult]):
    Task: Task[TResult]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def __init__(self, state: Any) -> None: ...
    @overload
    def __init__(self, state: Any, creationOptions: TaskCreationOptions) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def SetCanceled(self) -> None: ...
    @overload
    def SetCanceled(self, cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def SetException(self, exception: Any) -> None: ...
    @overload
    def SetException(self, exceptions: System.Collections.Generic.IEnumerable[Any]) -> None: ...
    def SetFromTask(self, completedTask: Task[TResult]) -> None: ...
    def SetResult(self, result: TResult) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def TrySetCanceled(self) -> bool: ...
    @overload
    def TrySetCanceled(self, cancellationToken: System.Threading.CancellationToken) -> bool: ...
    @overload
    def TrySetException(self, exception: Any) -> bool: ...
    @overload
    def TrySetException(self, exceptions: System.Collections.Generic.IEnumerable[Any]) -> bool: ...
    def TrySetFromTask(self, completedTask: Task[TResult]) -> bool: ...
    def TrySetResult(self, result: TResult) -> bool: ...

class TaskContinuationOptions(IntFlag):
    None_ = 0
    PreferFairness = 1
    LongRunning = 2
    AttachedToParent = 4
    DenyChildAttach = 8
    HideScheduler = 16
    LazyCancellation = 32
    RunContinuationsAsynchronously = 64
    NotOnRanToCompletion = 65536
    NotOnFaulted = 131072
    OnlyOnCanceled = 196608
    NotOnCanceled = 262144
    OnlyOnFaulted = 327680
    OnlyOnRanToCompletion = 393216
    ExecuteSynchronously = 524288

class TaskCreationOptions(IntFlag):
    None_ = 0
    PreferFairness = 1
    LongRunning = 2
    AttachedToParent = 4
    DenyChildAttach = 8
    HideScheduler = 16
    RunContinuationsAsynchronously = 64

class TaskExtensions:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def Unwrap(task: Task[Task_]) -> Task_: ...
    @overload
    @staticmethod
    def Unwrap(task: Task[Task[TResult]]) -> Task[TResult]: ...

class TaskFactory_:
    CancellationToken: System.Threading.CancellationToken
    Scheduler: TaskScheduler
    CreationOptions: TaskCreationOptions
    ContinuationOptions: TaskContinuationOptions
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def __init__(self, scheduler: TaskScheduler) -> None: ...
    @overload
    def __init__(self, creationOptions: TaskCreationOptions, continuationOptions: TaskContinuationOptions) -> None: ...
    @overload
    def __init__(self, cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> None: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationAction: Callable[..., None]) -> Task_: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationAction: Callable[..., None], continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationAction: Callable[..., None]) -> Task_: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationAction: Callable[..., None], continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationAction: Callable[..., None]) -> Task_: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationAction: Callable[..., None], continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationAction: Callable[..., None]) -> Task_: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationAction: Callable[..., None], continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def FromAsync(self, asyncResult: Any, endMethod: Callable[..., None]) -> Task_: ...
    @overload
    def FromAsync(self, asyncResult: Any, endMethod: Callable[..., None], creationOptions: TaskCreationOptions) -> Task_: ...
    @overload
    def FromAsync(self, asyncResult: Any, endMethod: Callable[..., None], creationOptions: TaskCreationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., None], state: Any) -> Task_: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., None], state: Any, creationOptions: TaskCreationOptions) -> Task_: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., None], arg1: TArg1, state: Any) -> Task_: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., None], arg1: TArg1, state: Any, creationOptions: TaskCreationOptions) -> Task_: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., None], arg1: TArg1, arg2: TArg2, state: Any) -> Task_: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., None], arg1: TArg1, arg2: TArg2, state: Any, creationOptions: TaskCreationOptions) -> Task_: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., None], arg1: TArg1, arg2: TArg2, arg3: TArg3, state: Any) -> Task_: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., None], arg1: TArg1, arg2: TArg2, arg3: TArg3, state: Any, creationOptions: TaskCreationOptions) -> Task_: ...
    @overload
    def FromAsync(self, asyncResult: Any, endMethod: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def FromAsync(self, asyncResult: Any, endMethod: Callable[..., TResult], creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def FromAsync(self, asyncResult: Any, endMethod: Callable[..., TResult], creationOptions: TaskCreationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], state: Any) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, state: Any) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, arg2: TArg2, state: Any) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, arg2: TArg2, state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, arg2: TArg2, arg3: TArg3, state: Any) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, arg2: TArg2, arg3: TArg3, state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def StartNew(self, action: Callable[..., None]) -> Task_: ...
    @overload
    def StartNew(self, action: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def StartNew(self, action: Callable[..., None], creationOptions: TaskCreationOptions) -> Task_: ...
    @overload
    def StartNew(self, action: Callable[..., None], cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def StartNew(self, action: Callable[..., None], state: Any) -> Task_: ...
    @overload
    def StartNew(self, action: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def StartNew(self, action: Callable[..., None], state: Any, creationOptions: TaskCreationOptions) -> Task_: ...
    @overload
    def StartNew(self, action: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def StartNew(self, function: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], state: Any) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    def ToString(self) -> str: ...

class TaskFactory(Generic[TResult]):
    CancellationToken: System.Threading.CancellationToken
    Scheduler: TaskScheduler
    CreationOptions: TaskCreationOptions
    ContinuationOptions: TaskContinuationOptions
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def __init__(self, scheduler: TaskScheduler) -> None: ...
    @overload
    def __init__(self, creationOptions: TaskCreationOptions, continuationOptions: TaskContinuationOptions) -> None: ...
    @overload
    def __init__(self, cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> None: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWhenAll(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task_], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWhenAny(self, tasks: list[Task[TAntecedentResult]], continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def FromAsync(self, asyncResult: Any, endMethod: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def FromAsync(self, asyncResult: Any, endMethod: Callable[..., TResult], creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def FromAsync(self, asyncResult: Any, endMethod: Callable[..., TResult], creationOptions: TaskCreationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], state: Any) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, state: Any) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, arg2: TArg2, state: Any) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, arg2: TArg2, state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, arg2: TArg2, arg3: TArg3, state: Any) -> Task[TResult]: ...
    @overload
    def FromAsync(self, beginMethod: Callable[..., Any], endMethod: Callable[..., TResult], arg1: TArg1, arg2: TArg2, arg3: TArg3, state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def StartNew(self, function: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], state: Any) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], state: Any, creationOptions: TaskCreationOptions) -> Task[TResult]: ...
    @overload
    def StartNew(self, function: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    def ToString(self) -> str: ...

class TaskScheduler:
    MaximumConcurrencyLevel: int
    Default: ClassVar[TaskScheduler]
    Current: ClassVar[TaskScheduler]
    Id: int
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def FromCurrentSynchronizationContext() -> TaskScheduler: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class TaskSchedulerException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, innerException: Any) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class TaskStatus(IntEnum):
    Created = 0
    WaitingForActivation = 1
    WaitingToRun = 2
    Running = 3
    WaitingForChildrenToComplete = 4
    RanToCompletion = 5
    Canceled = 6
    Faulted = 7

class TaskToAsyncResult:
    @staticmethod
    def Begin(task: Task_, callback: Callable[..., None], state: Any) -> Any: ...
    @overload
    @staticmethod
    def End(asyncResult: Any) -> None: ...
    @overload
    @staticmethod
    def End(asyncResult: Any) -> TResult: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def Unwrap(asyncResult: Any) -> Task_: ...
    @overload
    @staticmethod
    def Unwrap(asyncResult: Any) -> Task[TResult]: ...

class Task(Task_, Generic[TResult]):
    Result: TResult
    Factory: ClassVar[TaskFactory[TResult]]
    Id: int
    Exception: Any
    Status: TaskStatus
    IsCanceled: bool
    IsCompleted: bool
    IsCompletedSuccessfully: bool
    CreationOptions: TaskCreationOptions
    AsyncState: Any
    IsFaulted: bool
    @overload
    def __init__(self, function: Callable[..., TResult]) -> None: ...
    @overload
    def __init__(self, function: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def __init__(self, function: Callable[..., TResult], creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def __init__(self, function: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def __init__(self, function: Callable[..., TResult], state: Any) -> None: ...
    @overload
    def __init__(self, function: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def __init__(self, function: Callable[..., TResult], state: Any, creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def __init__(self, function: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken, creationOptions: TaskCreationOptions) -> None: ...
    @overload
    def ConfigureAwait(self, continueOnCapturedContext: bool) -> Any: ...
    @overload
    def ConfigureAwait(self, options: ConfigureAwaitOptions) -> Any: ...
    @overload
    def ConfigureAwait(self, continueOnCapturedContext: bool) -> Any: ...
    @overload
    def ConfigureAwait(self, options: ConfigureAwaitOptions) -> Any: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None]) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult]) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult], cancellationToken: System.Threading.CancellationToken) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult], scheduler: TaskScheduler) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult], continuationOptions: TaskContinuationOptions) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult], state: Any) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult], state: Any, cancellationToken: System.Threading.CancellationToken) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult], state: Any, scheduler: TaskScheduler) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult], state: Any, continuationOptions: TaskContinuationOptions) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TNewResult], state: Any, cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TNewResult]: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None]) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, continuationOptions: TaskContinuationOptions) -> Task_: ...
    @overload
    def ContinueWith(self, continuationAction: Callable[..., None], state: Any, cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task_: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult]) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any, scheduler: TaskScheduler) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any, continuationOptions: TaskContinuationOptions) -> Task[TResult]: ...
    @overload
    def ContinueWith(self, continuationFunction: Callable[..., TResult], state: Any, cancellationToken: System.Threading.CancellationToken, continuationOptions: TaskContinuationOptions, scheduler: TaskScheduler) -> Task[TResult]: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetAwaiter(self) -> Any: ...
    @overload
    def GetAwaiter(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def RunSynchronously(self) -> None: ...
    @overload
    def RunSynchronously(self, scheduler: TaskScheduler) -> None: ...
    @overload
    def Start(self) -> None: ...
    @overload
    def Start(self, scheduler: TaskScheduler) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Wait(self) -> None: ...
    @overload
    def Wait(self, timeout: Any) -> bool: ...
    @overload
    def Wait(self, timeout: Any, cancellationToken: System.Threading.CancellationToken) -> bool: ...
    @overload
    def Wait(self, cancellationToken: System.Threading.CancellationToken) -> None: ...
    @overload
    def Wait(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def Wait(self, millisecondsTimeout: int, cancellationToken: System.Threading.CancellationToken) -> bool: ...
    @overload
    def WaitAsync(self, cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def WaitAsync(self, timeout: Any) -> Task[TResult]: ...
    @overload
    def WaitAsync(self, timeout: Any, timeProvider: Any) -> Task[TResult]: ...
    @overload
    def WaitAsync(self, timeout: Any, cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def WaitAsync(self, timeout: Any, timeProvider: Any, cancellationToken: System.Threading.CancellationToken) -> Task[TResult]: ...
    @overload
    def WaitAsync(self, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def WaitAsync(self, timeout: Any) -> Task_: ...
    @overload
    def WaitAsync(self, timeout: Any, timeProvider: Any) -> Task_: ...
    @overload
    def WaitAsync(self, timeout: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...
    @overload
    def WaitAsync(self, timeout: Any, timeProvider: Any, cancellationToken: System.Threading.CancellationToken) -> Task_: ...

class UnobservedTaskExceptionEventArgs:
    Observed: bool
    Exception: Any
    def __init__(self, exception: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def SetObserved(self) -> None: ...
    def ToString(self) -> str: ...

class ValueTask_:
    CompletedTask: ClassVar[ValueTask_]
    IsCompleted: bool
    IsCompletedSuccessfully: bool
    IsFaulted: bool
    IsCanceled: bool
    @overload
    def __init__(self, task: Task_) -> None: ...
    @overload
    def __init__(self, source: System.Threading.Tasks.Sources.IValueTaskSource_, token: int) -> None: ...
    def AsTask(self) -> Task_: ...
    def ConfigureAwait(self, continueOnCapturedContext: bool) -> Any: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def Equals(self, other: ValueTask_) -> bool: ...
    @overload
    @staticmethod
    def FromCanceled(cancellationToken: System.Threading.CancellationToken) -> ValueTask_: ...
    @overload
    @staticmethod
    def FromCanceled(cancellationToken: System.Threading.CancellationToken) -> ValueTask[TResult]: ...
    @overload
    @staticmethod
    def FromException(exception: Any) -> ValueTask_: ...
    @overload
    @staticmethod
    def FromException(exception: Any) -> ValueTask[TResult]: ...
    @staticmethod
    def FromResult(result: TResult) -> ValueTask[TResult]: ...
    def GetAwaiter(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Preserve(self) -> ValueTask_: ...
    def ToString(self) -> str: ...

class ValueTask(Generic[TResult]):
    IsCompleted: bool
    IsCompletedSuccessfully: bool
    IsFaulted: bool
    IsCanceled: bool
    Result: TResult
    @overload
    def __init__(self, result: TResult) -> None: ...
    @overload
    def __init__(self, task: Task[TResult]) -> None: ...
    @overload
    def __init__(self, source: System.Threading.Tasks.Sources.IValueTaskSource[TResult], token: int) -> None: ...
    def AsTask(self) -> Task[TResult]: ...
    def ConfigureAwait(self, continueOnCapturedContext: bool) -> Any: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def Equals(self, other: ValueTask[TResult]) -> bool: ...
    def GetAwaiter(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Preserve(self) -> ValueTask[TResult]: ...
    def ToString(self) -> str: ...

from . import Sources