from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload

TResult = TypeVar("TResult")

class IValueTaskSource_:
    def GetResult(self, token: int) -> None: ...
    def GetStatus(self, token: int) -> ValueTaskSourceStatus: ...
    def OnCompleted(self, continuation: Callable[..., None], state: Any, token: int, flags: ValueTaskSourceOnCompletedFlags) -> None: ...

class IValueTaskSource(Generic[TResult]):
    def GetResult(self, token: int) -> TResult: ...
    def GetStatus(self, token: int) -> ValueTaskSourceStatus: ...
    def OnCompleted(self, continuation: Callable[..., None], state: Any, token: int, flags: ValueTaskSourceOnCompletedFlags) -> None: ...

class ManualResetValueTaskSourceCore(Generic[TResult]):
    RunContinuationsAsynchronously: bool
    Version: int
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetResult(self, token: int) -> TResult: ...
    def GetStatus(self, token: int) -> ValueTaskSourceStatus: ...
    def GetType(self) -> Any: ...
    def OnCompleted(self, continuation: Callable[..., None], state: Any, token: int, flags: ValueTaskSourceOnCompletedFlags) -> None: ...
    def Reset(self) -> None: ...
    def SetException(self, error: Any) -> None: ...
    def SetResult(self, result: TResult) -> None: ...
    def ToString(self) -> str: ...

class ValueTaskSourceOnCompletedFlags(IntFlag):
    None_ = 0
    UseSchedulingContext = 1
    FlowExecutionContext = 2

class ValueTaskSourceStatus(IntEnum):
    Pending = 0
    Succeeded = 1
    Faulted = 2
    Canceled = 3
