from __future__ import annotations
from typing import Any
import CodeWalker
import System

class Utils:
    @staticmethod
    def CollectTextures(d: CodeWalker.GameFiles.DrawableBase, textureSet: System.Collections.Generic.ISet[CodeWalker.GameFiles.Texture], textureMissing: System.Collections.Generic.ISet[str], gameFileCache: CodeWalker.GameFiles.GameFileCache) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    @staticmethod
    def WriteTexturesAsync(textures: System.Collections.Generic.IEnumerable[CodeWalker.GameFiles.Texture], outFolder: str, ct: System.Threading.CancellationToken = ...) -> System.Threading.Tasks.Task[Any]: ...
