from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload
import CodeWalker
import SharpDX

class BoundingBoxExtensions:
    @staticmethod
    def Center(bounds: SharpDX.BoundingBox) -> SharpDX.Vector3: ...
    @staticmethod
    def Encapsulate(box: SharpDX.BoundingBox, bounds: SharpDX.BoundingBox) -> SharpDX.BoundingBox: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def Expand(b: SharpDX.BoundingBox, amount: float) -> SharpDX.BoundingBox: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def Radius(box: SharpDX.BoundingBox) -> float: ...
    @staticmethod
    def Size(bounds: SharpDX.BoundingBox) -> SharpDX.Vector3: ...
    def ToString(self) -> str: ...

class Gen9Converter:
    InputFolder: str
    OutputFolder: str
    ProcessSubfolders: bool
    OverwriteExisting: bool
    CopyUnconverted: bool
    QuestionFunc: Callable[..., bool]
    ErrorAction: Callable[..., None]
    LogAction: Callable[..., None]
    ProgressAction: Callable[..., None]
    StartStopAction: Callable[..., None]
    def __init__(self) -> None: ...
    def Convert(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def RequiresConversion(rfe: CodeWalker.GameFiles.RpfResourceFileEntry) -> bool: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def TryConvert(data: list[int], fileType: str, copyunconverted: bool = ...) -> list[int]: ...
    @overload
    @staticmethod
    def TryConvert(data: list[int], fileType: str, log: Callable[..., None], relpath: str, copyunconverted: bool, converted: bool) -> list[int]: ...
