from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload
import TeximpNet

T = TypeVar("T")

BeginImageHandler = Callable[..., None]

EndImageHandler = Callable[..., None]

ErrorHandler = Callable[..., None]

class FreeImageLibrary(UnmanagedLibrary):
    Instance: ClassVar[FreeImageLibrary]
    IsLittleEndian: bool
    ColorOrder: TeximpNet.ColorOrder
    IsLibraryLoaded: bool
    DefaultLibraryName: str
    LibraryPath: str
    Resolver: UnmanagedLibraryResolver
    ThrowOnLoadFailure: bool
    def AdjustBrightness(self, bitmap: Any, percentage: float) -> bool: ...
    def AdjustContrast(self, bitmap: Any, percentage: float) -> bool: ...
    def AdjustGamma(self, bitmap: Any, gamma: float) -> bool: ...
    @overload
    def Allocate(self, width: int, height: int, bpp: int) -> Any: ...
    @overload
    def Allocate(self, width: int, height: int, bpp: int, red_mask: int, green_mask: int, blue_mask: int) -> Any: ...
    def AllocateT(self, imageType: TeximpNet.ImageType, width: int, height: int, bpp: int, red_mask: int, green_mask: int, blue_mask: int) -> Any: ...
    def Clone(self, bitmap: Any) -> Any: ...
    def ConvertFromRawBitsEx(self, copySource: bool, data: Any, imageType: TeximpNet.ImageType, width: int, height: int, pitch: int, bpp: int, redMask: int, greenMask: int, blueMask: int, topDown: bool) -> Any: ...
    def ConvertTo16Bits555(self, bitmap: Any) -> Any: ...
    def ConvertTo16Bits565(self, bitmap: Any) -> Any: ...
    def ConvertTo24Bits(self, bitmap: Any) -> Any: ...
    def ConvertTo32Bits(self, bitmap: Any) -> Any: ...
    def ConvertTo4Bits(self, bitmap: Any) -> Any: ...
    def ConvertTo8Bits(self, bitmap: Any) -> Any: ...
    def ConvertToFloat(self, bitmap: Any) -> Any: ...
    def ConvertToGreyscale(self, bitmap: Any) -> Any: ...
    def ConvertToRGB16(self, bitmap: Any) -> Any: ...
    def ConvertToRGBA16(self, bitmap: Any) -> Any: ...
    def ConvertToRGBAF(self, bitmap: Any) -> Any: ...
    def ConvertToRGBF(self, bitmap: Any) -> Any: ...
    def ConvertToStandardType(self, src: Any, scaleLinearly: bool) -> Any: ...
    def ConvertToType(self, src: Any, dstType: TeximpNet.ImageType, scaleLinearly: bool) -> Any: ...
    def ConvertToUINT16(self, bitmap: Any) -> Any: ...
    def Copy(self, bitmap: Any, left: int, top: int, right: int, bottom: int) -> Any: ...
    def Equals(self, obj: Any) -> bool: ...
    def FlipHorizontal(self, bitmap: Any) -> bool: ...
    def FlipVertical(self, bitmap: Any) -> bool: ...
    def FreeLibrary(self) -> bool: ...
    def GetBitsPerPixel(self, bitmap: Any) -> int: ...
    def GetBlueMask(self, bitmap: Any) -> int: ...
    def GetCopyrightMessage(self) -> str: ...
    def GetData(self, bitmap: Any) -> Any: ...
    def GetFileTypeFromFile(self, filename: str) -> TeximpNet.ImageFormat: ...
    def GetFileTypeFromStream(self, stream: Any) -> TeximpNet.ImageFormat: ...
    def GetFunction(self, funcName: str) -> T: ...
    def GetGreenMask(self, bitmap: Any) -> int: ...
    def GetHashCode(self) -> int: ...
    def GetHeight(self, bitmap: Any) -> int: ...
    def GetImageColorType(self, bitmap: Any) -> TeximpNet.ImageColorType: ...
    def GetImageType(self, bitmap: Any) -> TeximpNet.ImageType: ...
    def GetPalette(self, bitmap: Any) -> Any: ...
    def GetPaletteColorCount(self, bitmap: Any) -> int: ...
    def GetPitch(self, bitmap: Any) -> int: ...
    def GetRedMask(self, bitmap: Any) -> int: ...
    def GetScanLine(self, bitmap: Any, scanline: int) -> Any: ...
    def GetType(self) -> Any: ...
    def GetVersion(self) -> str: ...
    def GetWidth(self, bitmap: Any) -> int: ...
    def HasPixels(self, bitmap: Any) -> bool: ...
    def Invert(self, bitmap: Any) -> bool: ...
    def IsTransparent(self, bitmap: Any) -> bool: ...
    def LoadFromFile(self, filename: str, flags: TeximpNet.ImageLoadFlags = ...) -> Any: ...
    def LoadFromStream(self, stream: Any, flags: TeximpNet.ImageLoadFlags = ...) -> Any: ...
    @overload
    def LoadLibrary(self) -> bool: ...
    @overload
    def LoadLibrary(self, lib32Path: str, lib64Path: str) -> bool: ...
    @overload
    def LoadLibrary(self, libPath: str) -> bool: ...
    def Paste(self, dstBitmap: Any, srcBitmap: Any, left: int, top: int, alpha: int) -> bool: ...
    def PreMultiplyWithAlpha(self, bitmap: Any) -> bool: ...
    def Rescale(self, bitmap: Any, dst_width: int, dst_height: int, filter: TeximpNet.ImageFilter) -> Any: ...
    def Rotate(self, bitmap: Any, angle: float) -> Any: ...
    def SaveToFile(self, format: TeximpNet.ImageFormat, bitmap: Any, filename: str, flags: TeximpNet.ImageSaveFlags = ...) -> bool: ...
    def SaveToStream(self, format: TeximpNet.ImageFormat, bitmap: Any, stream: Any, flags: TeximpNet.ImageSaveFlags = ...) -> bool: ...
    def SwapColors(self, bitmap: Any, colorToReplace: TeximpNet.RGBAQuad, colorToReplaceWith: TeximpNet.RGBAQuad, ignoreAlpha: bool) -> int: ...
    def ToString(self) -> str: ...
    def Unload(self, bitmap: Any) -> None: ...

class NvTextureToolsLibrary(UnmanagedLibrary):
    Instance: ClassVar[NvTextureToolsLibrary]
    IsLibraryLoaded: bool
    DefaultLibraryName: str
    LibraryPath: str
    Resolver: UnmanagedLibraryResolver
    ThrowOnLoadFailure: bool
    def CreateCompressionOptions(self) -> Any: ...
    def CreateCompressor(self) -> Any: ...
    def CreateInputOptions(self) -> Any: ...
    def CreateOutputOptions(self) -> Any: ...
    def DestroyCompressionOptions(self, compressOptions: Any) -> None: ...
    def DestroyCompressor(self, compressor: Any) -> None: ...
    def DestroyInputOptions(self, inputOptions: Any) -> None: ...
    def DestroyOutputOptions(self, outputOptions: Any) -> None: ...
    def EnableCudaAcceleration(self, compressor: Any, value: bool) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def EstimateSize(self, compressor: Any, inputOptions: Any, compressionOptions: Any) -> int: ...
    def FreeLibrary(self) -> bool: ...
    def GetErrorString(self, error: TeximpNet.Compression.CompressorError) -> str: ...
    def GetFunction(self, funcName: str) -> T: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def GetVersion(self) -> int: ...
    def IsCudaAccelerationEnabled(self, compressor: Any) -> bool: ...
    @overload
    def LoadLibrary(self) -> bool: ...
    @overload
    def LoadLibrary(self, lib32Path: str, lib64Path: str) -> bool: ...
    @overload
    def LoadLibrary(self, libPath: str) -> bool: ...
    def Process(self, compressor: Any, inputOptions: Any, compressionOptions: Any, outputOptions: Any) -> bool: ...
    def ResetInputOptionsTextureLayout(self, inputOptions: Any) -> None: ...
    def SetCompressionOptionsColorWeights(self, compressOptions: Any, red: float, green: float, blue: float, alpha: float) -> None: ...
    def SetCompressionOptionsFormat(self, compressOptions: Any, format: TeximpNet.Compression.CompressionFormat) -> None: ...
    def SetCompressionOptionsPixelFormat(self, compressOptions: Any, bitsPerPixel: int, red_mask: int, green_mask: int, blue_mask: int, alpha_mask: int) -> None: ...
    def SetCompressionOptionsQuality(self, compressOptions: Any, quality: TeximpNet.Compression.CompressionQuality) -> None: ...
    def SetCompressionOptionsQuantization(self, compressOptions: Any, colorDithering: bool, alphaDithering: bool, binaryAlpha: bool, alphaThreshold: int) -> None: ...
    def SetInputOptionsAlphaMode(self, inputOptions: Any, alphaMode: TeximpNet.Compression.AlphaMode) -> None: ...
    def SetInputOptionsConvertToNormalMap(self, inputOptions: Any, convertToNormalMap: bool) -> None: ...
    def SetInputOptionsFormat(self, inputOptions: Any, pixelFormat: TeximpNet.Compression.InputFormat) -> None: ...
    def SetInputOptionsGamma(self, inputOptions: Any, inputGamma: float, outputGamma: float) -> None: ...
    def SetInputOptionsHeightEvaluation(self, inputOptions: Any, redScale: float, greenScale: float, blueScale: float, alphaScale: float) -> None: ...
    def SetInputOptionsKaiserParameters(self, inputOptions: Any, width: float, alpha: float, stretch: float) -> None: ...
    def SetInputOptionsMaxExtents(self, inputOptions: Any, dimensions: int) -> None: ...
    def SetInputOptionsMipmapData(self, inputOptions: Any, data: Any, width: int, height: int, depth: int, face: int, mipmap: int) -> bool: ...
    def SetInputOptionsMipmapFilter(self, inputOptions: Any, filter: TeximpNet.Compression.MipmapFilter) -> None: ...
    def SetInputOptionsMipmapGeneration(self, inputOptions: Any, isEnabled: bool, maxLevel: int) -> None: ...
    def SetInputOptionsNormalFilter(self, inputOptions: Any, small: float, medium: float, big: float, large: float) -> None: ...
    def SetInputOptionsNormalMap(self, inputOptions: Any, isNormalMap: bool) -> None: ...
    def SetInputOptionsNormalizeMipmaps(self, inputOptions: Any, normalize: bool) -> None: ...
    def SetInputOptionsRoundMode(self, inputOptions: Any, roundMode: TeximpNet.Compression.RoundMode) -> None: ...
    def SetInputOptionsTextureLayout(self, inputOptions: Any, type: TeximpNet.Compression.TextureType, width: int, height: int, depth: int, arraySize: int) -> None: ...
    def SetInputOptionsWrapMode(self, inputOptions: Any, wrapMode: TeximpNet.Compression.WrapMode) -> None: ...
    def SetOutputOptionsContainer(self, outputOptions: Any, format: TeximpNet.Compression.OutputFileFormat) -> None: ...
    def SetOutputOptionsErrorHandler(self, outputOptions: Any, errorHandlerCallback: Any) -> None: ...
    def SetOutputOptionsFileName(self, outputOptions: Any, filename: str) -> None: ...
    def SetOutputOptionsOutputHandler(self, outputOptions: Any, beginImageHandlerCallback: Any, outputHandlerCallback: Any, endImageHandlerCallback: Any) -> None: ...
    def SetOutputOptionsOutputHeader(self, outputOptions: Any, value: bool) -> None: ...
    def SetOutputOptionsSrgbFlag(self, outputOptions: Any, value: bool) -> None: ...
    def ToString(self) -> str: ...

OutputHandler = Callable[..., bool]

class Platform(IntEnum):
    Windows = 0
    Linux = 1
    Mac = 2

class UnmanagedFunctionNameAttribute:
    UnmanagedFunctionName: str
    TypeId: Any
    def __init__(self, unmanagedFunctionName: str) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def IsDefaultAttribute(self) -> bool: ...
    def Match(self, obj: Any) -> bool: ...
    def ToString(self) -> str: ...

class UnmanagedLibrary:
    IsLibraryLoaded: bool
    DefaultLibraryName: str
    LibraryPath: str
    Resolver: UnmanagedLibraryResolver
    ThrowOnLoadFailure: bool
    Is64Bit: ClassVar[bool]
    def Equals(self, obj: Any) -> bool: ...
    def FreeLibrary(self) -> bool: ...
    def GetFunction(self, funcName: str) -> T: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetPlatform() -> Platform: ...
    def GetType(self) -> Any: ...
    @overload
    def LoadLibrary(self) -> bool: ...
    @overload
    def LoadLibrary(self, lib32Path: str, lib64Path: str) -> bool: ...
    @overload
    def LoadLibrary(self, libPath: str) -> bool: ...
    def ToString(self) -> str: ...

class UnmanagedLibraryResolver:
    Platform: Platform
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ResolveLibraryPath(self, libName: str) -> str: ...
    def SetFallbackLibraryNames(self, fallbackLibNames: list[str]) -> None: ...
    def SetFallbackLibraryNames32(self, fallbackLibNames: list[str]) -> None: ...
    def SetFallbackLibraryNames64(self, fallbackLibNames: list[str]) -> None: ...
    def SetOverrideLibraryName(self, overrideName: str) -> None: ...
    def SetOverrideLibraryName32(self, overrideName: str) -> None: ...
    def SetOverrideLibraryName64(self, overrideName: str) -> None: ...
    def SetProbingPaths(self, probingPaths: list[str]) -> None: ...
    def SetProbingPaths32(self, probingPaths: list[str]) -> None: ...
    def SetProbingPaths64(self, probingPaths: list[str]) -> None: ...
    def ToString(self) -> str: ...
