from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload
import CodeWalker
import SharpDX
import System

class YndBuilder:
    def __init__(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class YnvBuilder:
    PolyList: System.Collections.Generic.List[CodeWalker.GameFiles.YnvPoly]
    VehicleName: str
    def __init__(self) -> None: ...
    def AddPoly(self, verts: list[SharpDX.Vector3]) -> CodeWalker.GameFiles.YnvPoly: ...
    def Build(self, forVehicle: bool) -> System.Collections.Generic.List[CodeWalker.GameFiles.YnvFile]: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
