from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload
import System

T = TypeVar("T")

class ConcurrentQueue(Generic[T]):
    IsEmpty: bool
    Count: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, collection: System.Collections.Generic.IEnumerable[T]) -> None: ...
    def Clear(self) -> None: ...
    def CopyTo(self, array: list[T], index: int) -> None: ...
    def Enqueue(self, item: T) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetEnumerator(self) -> System.Collections.Generic.IEnumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToArray(self) -> list[T]: ...
    def ToString(self) -> str: ...
    def TryDequeue(self, result: T) -> bool: ...
    def TryPeek(self, result: T) -> bool: ...

class IProducerConsumerCollection(Generic[T]):
    def CopyTo(self, array: list[T], index: int) -> None: ...
    def ToArray(self) -> list[T]: ...
    def TryAdd(self, item: T) -> bool: ...
    def TryTake(self, item: T) -> bool: ...
