from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload
import System

T = TypeVar("T")
TAlternate = TypeVar("TAlternate")
TAlternateKey = TypeVar("TAlternateKey")
TElement = TypeVar("TElement")
TKey = TypeVar("TKey")
TOutput = TypeVar("TOutput")
TPriority = TypeVar("TPriority")
TValue = TypeVar("TValue")

class ByteEqualityComparer(EqualityComparer[int]):
    def __init__(self) -> None: ...
    @overload
    def Equals(self, x: int, y: int) -> bool: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetHashCode(self, b: int) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class CollectionExtensions:
    @staticmethod
    def AddRange(list: List[T], source: Any) -> None: ...
    @overload
    @staticmethod
    def AsReadOnly(list: IList[T]) -> System.Collections.ObjectModel.ReadOnlyCollection[T]: ...
    @overload
    @staticmethod
    def AsReadOnly(set: ISet[T]) -> System.Collections.ObjectModel.ReadOnlySet[T]: ...
    @overload
    @staticmethod
    def AsReadOnly(dictionary: IDictionary[TKey, TValue]) -> System.Collections.ObjectModel.ReadOnlyDictionary[TKey, TValue]: ...
    @staticmethod
    def CopyTo(list: List[T], destination: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    @staticmethod
    def GetValueOrDefault(dictionary: IReadOnlyDictionary[TKey, TValue], key: TKey) -> TValue: ...
    @overload
    @staticmethod
    def GetValueOrDefault(dictionary: IReadOnlyDictionary[TKey, TValue], key: TKey, defaultValue: TValue) -> TValue: ...
    @staticmethod
    def InsertRange(list: List[T], index: int, source: Any) -> None: ...
    @staticmethod
    def Remove(dictionary: IDictionary[TKey, TValue], key: TKey, value: TValue) -> bool: ...
    def ToString(self) -> str: ...
    @staticmethod
    def TryAdd(dictionary: IDictionary[TKey, TValue], key: TKey, value: TValue) -> bool: ...

class Comparer(Generic[T]):
    Default: ClassVar[Comparer[T]]
    def Compare(self, x: T, y: T) -> int: ...
    @staticmethod
    def Create(comparison: Callable[..., int]) -> Comparer[T]: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class Dictionary(Generic[TKey, TValue]):
    Comparer: IEqualityComparer[TKey]
    Count: int
    Capacity: int
    Keys: Dictionary.KeyCollection[TKey, TValue]
    Values: Dictionary.ValueCollection[TKey, TValue]
    @overload
    def __getitem__(self, index: TKey) -> TValue: ...
    def __setitem__(self, index: TKey, value: TValue) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, capacity: int) -> None: ...
    @overload
    def __init__(self, comparer: IEqualityComparer[TKey]) -> None: ...
    @overload
    def __init__(self, capacity: int, comparer: IEqualityComparer[TKey]) -> None: ...
    @overload
    def __init__(self, dictionary: IDictionary[TKey, TValue]) -> None: ...
    @overload
    def __init__(self, dictionary: IDictionary[TKey, TValue], comparer: IEqualityComparer[TKey]) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[KeyValuePair[TKey, TValue]]) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[KeyValuePair[TKey, TValue]], comparer: IEqualityComparer[TKey]) -> None: ...
    def Add(self, key: TKey, value: TValue) -> None: ...
    def Clear(self) -> None: ...
    def ContainsKey(self, key: TKey) -> bool: ...
    def ContainsValue(self, value: TValue) -> bool: ...
    def EnsureCapacity(self, capacity: int) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetAlternateLookup(self) -> Dictionary.AlternateLookup[TKey, TValue, TAlternateKey]: ...
    def GetEnumerator(self) -> Dictionary.Enumerator[TKey, TValue]: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    def GetType(self) -> Any: ...
    def OnDeserialization(self, sender: Any) -> None: ...
    @overload
    def Remove(self, key: TKey) -> bool: ...
    @overload
    def Remove(self, key: TKey, value: TValue) -> bool: ...
    def ToString(self) -> str: ...
    @overload
    def TrimExcess(self) -> None: ...
    @overload
    def TrimExcess(self, capacity: int) -> None: ...
    def TryAdd(self, key: TKey, value: TValue) -> bool: ...
    def TryGetAlternateLookup(self, lookup: Dictionary.AlternateLookup[TKey, TValue, TAlternateKey]) -> bool: ...
    def TryGetValue(self, key: TKey, value: TValue) -> bool: ...

    class AlternateLookup(Generic[TKey, TValue, TAlternateKey]):
        Dictionary: Dictionary[TKey, TValue]
        @overload
        def __getitem__(self, index: TAlternateKey) -> TValue: ...
        def __setitem__(self, index: TAlternateKey, value: TValue) -> None: ...
        def ContainsKey(self, key: TAlternateKey) -> bool: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        @overload
        def Remove(self, key: TAlternateKey) -> bool: ...
        @overload
        def Remove(self, key: TAlternateKey, actualKey: TKey, value: TValue) -> bool: ...
        def ToString(self) -> str: ...
        def TryAdd(self, key: TAlternateKey, value: TValue) -> bool: ...
        @overload
        def TryGetValue(self, key: TAlternateKey, value: TValue) -> bool: ...
        @overload
        def TryGetValue(self, key: TAlternateKey, actualKey: TKey, value: TValue) -> bool: ...

    class Enumerator(Generic[TKey, TValue]):
        Current: KeyValuePair[TKey, TValue]
        def Dispose(self) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def MoveNext(self) -> bool: ...
        def ToString(self) -> str: ...

    class KeyCollection(Generic[TKey, TValue]):
        Count: int
        def __init__(self, dictionary: Dictionary[TKey, TValue]) -> None: ...
        def Contains(self, item: TKey) -> bool: ...
        def CopyTo(self, array: list[TKey], index: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> Dictionary.KeyCollection.Enumerator[TKey, TValue]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

        class Enumerator(Generic[TKey, TValue]):
            Current: TKey
            def Dispose(self) -> None: ...
            def Equals(self, obj: Any) -> bool: ...
            def GetHashCode(self) -> int: ...
            def GetType(self) -> Any: ...
            def MoveNext(self) -> bool: ...
            def ToString(self) -> str: ...

    class ValueCollection(Generic[TKey, TValue]):
        Count: int
        def __init__(self, dictionary: Dictionary[TKey, TValue]) -> None: ...
        def CopyTo(self, array: list[TValue], index: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> Dictionary.ValueCollection.Enumerator[TKey, TValue]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

        class Enumerator(Generic[TKey, TValue]):
            Current: TValue
            def Dispose(self) -> None: ...
            def Equals(self, obj: Any) -> bool: ...
            def GetHashCode(self) -> int: ...
            def GetType(self) -> Any: ...
            def MoveNext(self) -> bool: ...
            def ToString(self) -> str: ...

class EnumEqualityComparer(EqualityComparer[T], Generic[T]):
    def __init__(self) -> None: ...
    @overload
    def Equals(self, x: T, y: T) -> bool: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetHashCode(self, obj: T) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class EqualityComparer(Generic[T]):
    Default: ClassVar[EqualityComparer[T]]
    @staticmethod
    def Create(equals: Callable[..., bool], getHashCode: Callable[..., int] = ...) -> EqualityComparer[T]: ...
    @overload
    def Equals(self, x: T, y: T) -> bool: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetHashCode(self, obj: T) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class GenericComparer(Comparer[T], Generic[T]):
    def __init__(self) -> None: ...
    def Compare(self, x: T, y: T) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class GenericEqualityComparer(EqualityComparer[T], Generic[T]):
    def __init__(self) -> None: ...
    @overload
    def Equals(self, x: T, y: T) -> bool: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetHashCode(self, obj: T) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class HashSet(Generic[T]):
    Count: int
    Capacity: int
    Comparer: IEqualityComparer[T]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, comparer: IEqualityComparer[T]) -> None: ...
    @overload
    def __init__(self, capacity: int) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[T]) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[T], comparer: IEqualityComparer[T]) -> None: ...
    @overload
    def __init__(self, capacity: int, comparer: IEqualityComparer[T]) -> None: ...
    def Add(self, item: T) -> bool: ...
    def Clear(self) -> None: ...
    def Contains(self, item: T) -> bool: ...
    @overload
    def CopyTo(self, array: list[T]) -> None: ...
    @overload
    def CopyTo(self, array: list[T], arrayIndex: int) -> None: ...
    @overload
    def CopyTo(self, array: list[T], arrayIndex: int, count: int) -> None: ...
    @staticmethod
    def CreateSetComparer() -> IEqualityComparer[HashSet[T]]: ...
    def EnsureCapacity(self, capacity: int) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def ExceptWith(self, other: IEnumerable[T]) -> None: ...
    def GetAlternateLookup(self) -> HashSet.AlternateLookup[T, TAlternate]: ...
    def GetEnumerator(self) -> HashSet.Enumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    def GetType(self) -> Any: ...
    def IntersectWith(self, other: IEnumerable[T]) -> None: ...
    def IsProperSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsProperSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def OnDeserialization(self, sender: Any) -> None: ...
    def Overlaps(self, other: IEnumerable[T]) -> bool: ...
    def Remove(self, item: T) -> bool: ...
    def RemoveWhere(self, match: Callable[..., bool]) -> int: ...
    def SetEquals(self, other: IEnumerable[T]) -> bool: ...
    def SymmetricExceptWith(self, other: IEnumerable[T]) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def TrimExcess(self) -> None: ...
    @overload
    def TrimExcess(self, capacity: int) -> None: ...
    def TryGetAlternateLookup(self, lookup: HashSet.AlternateLookup[T, TAlternate]) -> bool: ...
    def TryGetValue(self, equalValue: T, actualValue: T) -> bool: ...
    def UnionWith(self, other: IEnumerable[T]) -> None: ...

    class AlternateLookup(Generic[T, TAlternate]):
        Set: HashSet[T]
        def Add(self, item: TAlternate) -> bool: ...
        def Contains(self, item: TAlternate) -> bool: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def Remove(self, item: TAlternate) -> bool: ...
        def ToString(self) -> str: ...
        def TryGetValue(self, equalValue: TAlternate, actualValue: T) -> bool: ...

    class Enumerator(Generic[T]):
        Current: T
        def Dispose(self) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def MoveNext(self) -> bool: ...
        def ToString(self) -> str: ...

class IAlternateEqualityComparer(Generic[TAlternate, T]):
    def Create(self, alternate: TAlternate) -> T: ...
    def Equals(self, alternate: TAlternate, other: T) -> bool: ...
    def GetHashCode(self, alternate: TAlternate) -> int: ...

class IAsyncEnumerable(Generic[T]):
    def GetAsyncEnumerator(self, cancellationToken: System.Threading.CancellationToken = ...) -> IAsyncEnumerator[T]: ...

class IAsyncEnumerator(Generic[T]):
    Current: T
    def MoveNextAsync(self) -> System.Threading.Tasks.ValueTask[bool]: ...

class ICollection(Generic[T]):
    Count: int
    IsReadOnly: bool
    def Add(self, item: T) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: T) -> bool: ...
    def CopyTo(self, array: list[T], arrayIndex: int) -> None: ...
    def Remove(self, item: T) -> bool: ...

class IComparer(Generic[T]):
    def Compare(self, x: T, y: T) -> int: ...

class IDictionary(Generic[TKey, TValue]):
    @overload
    def __getitem__(self, index: TKey) -> TValue: ...
    def __setitem__(self, index: TKey, value: TValue) -> None: ...
    Keys: ICollection[TKey]
    Values: ICollection[TValue]
    def Add(self, key: TKey, value: TValue) -> None: ...
    def ContainsKey(self, key: TKey) -> bool: ...
    def Remove(self, key: TKey) -> bool: ...
    def TryGetValue(self, key: TKey, value: TValue) -> bool: ...

class IEnumerable(Generic[T]):
    def GetEnumerator(self) -> IEnumerator[T]: ...

class IEnumerator(Generic[T]):
    Current: T

class IEqualityComparer(Generic[T]):
    def Equals(self, x: T, y: T) -> bool: ...
    def GetHashCode(self, obj: T) -> int: ...

class IList(Generic[T]):
    @overload
    def __getitem__(self, index: int) -> T: ...
    def __setitem__(self, index: int, value: T) -> None: ...
    def IndexOf(self, item: T) -> int: ...
    def Insert(self, index: int, item: T) -> None: ...
    def RemoveAt(self, index: int) -> None: ...

class IReadOnlyCollection(Generic[T]):
    Count: int

class IReadOnlyDictionary(Generic[TKey, TValue]):
    @overload
    def __getitem__(self, index: TKey) -> TValue: ...
    Keys: IEnumerable[TKey]
    Values: IEnumerable[TValue]
    def ContainsKey(self, key: TKey) -> bool: ...
    def TryGetValue(self, key: TKey, value: TValue) -> bool: ...

class IReadOnlyList(Generic[T]):
    @overload
    def __getitem__(self, index: int) -> T: ...

class IReadOnlySet(Generic[T]):
    def Contains(self, item: T) -> bool: ...
    def IsProperSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsProperSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def Overlaps(self, other: IEnumerable[T]) -> bool: ...
    def SetEquals(self, other: IEnumerable[T]) -> bool: ...

class ISet(Generic[T]):
    def Add(self, item: T) -> bool: ...
    def ExceptWith(self, other: IEnumerable[T]) -> None: ...
    def IntersectWith(self, other: IEnumerable[T]) -> None: ...
    def IsProperSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsProperSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def Overlaps(self, other: IEnumerable[T]) -> bool: ...
    def SetEquals(self, other: IEnumerable[T]) -> bool: ...
    def SymmetricExceptWith(self, other: IEnumerable[T]) -> None: ...
    def UnionWith(self, other: IEnumerable[T]) -> None: ...

class KeyNotFoundException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class KeyValuePair_:
    @staticmethod
    def Create(key: TKey, value: TValue) -> KeyValuePair[TKey, TValue]: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class KeyValuePair(Generic[TKey, TValue]):
    Key: TKey
    Value: TValue
    def __init__(self, key: TKey, value: TValue) -> None: ...
    def Deconstruct(self, key: TKey, value: TValue) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class LinkedListNode(Generic[T]):
    List: LinkedList[T]
    Next: LinkedListNode[T]
    Previous: LinkedListNode[T]
    Value: T
    ValueRef: T
    def __init__(self, value: T) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class LinkedList(Generic[T]):
    Count: int
    First: LinkedListNode[T]
    Last: LinkedListNode[T]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[T]) -> None: ...
    @overload
    def AddAfter(self, node: LinkedListNode[T], value: T) -> LinkedListNode[T]: ...
    @overload
    def AddAfter(self, node: LinkedListNode[T], newNode: LinkedListNode[T]) -> None: ...
    @overload
    def AddBefore(self, node: LinkedListNode[T], value: T) -> LinkedListNode[T]: ...
    @overload
    def AddBefore(self, node: LinkedListNode[T], newNode: LinkedListNode[T]) -> None: ...
    @overload
    def AddFirst(self, value: T) -> LinkedListNode[T]: ...
    @overload
    def AddFirst(self, node: LinkedListNode[T]) -> None: ...
    @overload
    def AddLast(self, value: T) -> LinkedListNode[T]: ...
    @overload
    def AddLast(self, node: LinkedListNode[T]) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, value: T) -> bool: ...
    def CopyTo(self, array: list[T], index: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def Find(self, value: T) -> LinkedListNode[T]: ...
    def FindLast(self, value: T) -> LinkedListNode[T]: ...
    def GetEnumerator(self) -> LinkedList.Enumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    def GetType(self) -> Any: ...
    def OnDeserialization(self, sender: Any) -> None: ...
    @overload
    def Remove(self, value: T) -> bool: ...
    @overload
    def Remove(self, node: LinkedListNode[T]) -> None: ...
    def RemoveFirst(self) -> None: ...
    def RemoveLast(self) -> None: ...
    def ToString(self) -> str: ...

    class Enumerator(Generic[T]):
        Current: T
        def Dispose(self) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def MoveNext(self) -> bool: ...
        def ToString(self) -> str: ...

class List(Generic[T]):
    Capacity: int
    Count: int
    @overload
    def __getitem__(self, index: int) -> T: ...
    def __setitem__(self, index: int, value: T) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, capacity: int) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[T]) -> None: ...
    def Add(self, item: T) -> None: ...
    def AddRange(self, collection: IEnumerable[T]) -> None: ...
    def AsReadOnly(self) -> System.Collections.ObjectModel.ReadOnlyCollection[T]: ...
    @overload
    def BinarySearch(self, index: int, count: int, item: T, comparer: IComparer[T]) -> int: ...
    @overload
    def BinarySearch(self, item: T) -> int: ...
    @overload
    def BinarySearch(self, item: T, comparer: IComparer[T]) -> int: ...
    def Clear(self) -> None: ...
    def Contains(self, item: T) -> bool: ...
    def ConvertAll(self, converter: Callable[..., TOutput]) -> List[TOutput]: ...
    @overload
    def CopyTo(self, array: list[T]) -> None: ...
    @overload
    def CopyTo(self, index: int, array: list[T], arrayIndex: int, count: int) -> None: ...
    @overload
    def CopyTo(self, array: list[T], arrayIndex: int) -> None: ...
    def EnsureCapacity(self, capacity: int) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def Exists(self, match: Callable[..., bool]) -> bool: ...
    def Find(self, match: Callable[..., bool]) -> T: ...
    def FindAll(self, match: Callable[..., bool]) -> List[T]: ...
    @overload
    def FindIndex(self, match: Callable[..., bool]) -> int: ...
    @overload
    def FindIndex(self, startIndex: int, match: Callable[..., bool]) -> int: ...
    @overload
    def FindIndex(self, startIndex: int, count: int, match: Callable[..., bool]) -> int: ...
    def FindLast(self, match: Callable[..., bool]) -> T: ...
    @overload
    def FindLastIndex(self, match: Callable[..., bool]) -> int: ...
    @overload
    def FindLastIndex(self, startIndex: int, match: Callable[..., bool]) -> int: ...
    @overload
    def FindLastIndex(self, startIndex: int, count: int, match: Callable[..., bool]) -> int: ...
    def ForEach(self, action: Callable[..., None]) -> None: ...
    def GetEnumerator(self) -> List.Enumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetRange(self, index: int, count: int) -> List[T]: ...
    def GetType(self) -> Any: ...
    @overload
    def IndexOf(self, item: T) -> int: ...
    @overload
    def IndexOf(self, item: T, index: int) -> int: ...
    @overload
    def IndexOf(self, item: T, index: int, count: int) -> int: ...
    def Insert(self, index: int, item: T) -> None: ...
    def InsertRange(self, index: int, collection: IEnumerable[T]) -> None: ...
    @overload
    def LastIndexOf(self, item: T) -> int: ...
    @overload
    def LastIndexOf(self, item: T, index: int) -> int: ...
    @overload
    def LastIndexOf(self, item: T, index: int, count: int) -> int: ...
    def Remove(self, item: T) -> bool: ...
    def RemoveAll(self, match: Callable[..., bool]) -> int: ...
    def RemoveAt(self, index: int) -> None: ...
    def RemoveRange(self, index: int, count: int) -> None: ...
    @overload
    def Reverse(self) -> None: ...
    @overload
    def Reverse(self, index: int, count: int) -> None: ...
    def Slice(self, start: int, length: int) -> List[T]: ...
    @overload
    def Sort(self) -> None: ...
    @overload
    def Sort(self, comparer: IComparer[T]) -> None: ...
    @overload
    def Sort(self, index: int, count: int, comparer: IComparer[T]) -> None: ...
    @overload
    def Sort(self, comparison: Callable[..., int]) -> None: ...
    def ToArray(self) -> list[T]: ...
    def ToString(self) -> str: ...
    def TrimExcess(self) -> None: ...
    def TrueForAll(self, match: Callable[..., bool]) -> bool: ...

    class Enumerator(Generic[T]):
        Current: T
        def Dispose(self) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def MoveNext(self) -> bool: ...
        def ToString(self) -> str: ...

class NonRandomizedStringEqualityComparer:
    @overload
    def Equals(self, x: str, y: str) -> bool: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetHashCode(self, obj: str) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetStringComparer(comparer: Any) -> IEqualityComparer[str]: ...
    def GetType(self) -> Any: ...
    def GetUnderlyingEqualityComparer(self) -> IEqualityComparer[str]: ...
    def ToString(self) -> str: ...

class NullableComparer(Comparer[T | None], Generic[T]):
    def __init__(self) -> None: ...
    def Compare(self, x: T | None, y: T | None) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class NullableEqualityComparer(EqualityComparer[T | None], Generic[T]):
    def __init__(self) -> None: ...
    @overload
    def Equals(self, x: T | None, y: T | None) -> bool: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetHashCode(self, obj: T | None) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ObjectComparer(Comparer[T], Generic[T]):
    def __init__(self) -> None: ...
    def Compare(self, x: T, y: T) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ObjectEqualityComparer(EqualityComparer[T], Generic[T]):
    def __init__(self) -> None: ...
    @overload
    def Equals(self, x: T, y: T) -> bool: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetHashCode(self, obj: T) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class OrderedDictionary(Generic[TKey, TValue]):
    Capacity: int
    Comparer: IEqualityComparer[TKey]
    Count: int
    Keys: OrderedDictionary.KeyCollection[TKey, TValue]
    Values: OrderedDictionary.ValueCollection[TKey, TValue]
    @overload
    def __getitem__(self, index: TKey) -> TValue: ...
    def __setitem__(self, index: TKey, value: TValue) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, capacity: int) -> None: ...
    @overload
    def __init__(self, comparer: IEqualityComparer[TKey]) -> None: ...
    @overload
    def __init__(self, capacity: int, comparer: IEqualityComparer[TKey]) -> None: ...
    @overload
    def __init__(self, dictionary: IDictionary[TKey, TValue]) -> None: ...
    @overload
    def __init__(self, dictionary: IDictionary[TKey, TValue], comparer: IEqualityComparer[TKey]) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[KeyValuePair[TKey, TValue]]) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[KeyValuePair[TKey, TValue]], comparer: IEqualityComparer[TKey]) -> None: ...
    def Add(self, key: TKey, value: TValue) -> None: ...
    def Clear(self) -> None: ...
    def ContainsKey(self, key: TKey) -> bool: ...
    def ContainsValue(self, value: TValue) -> bool: ...
    def EnsureCapacity(self, capacity: int) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetAt(self, index: int) -> KeyValuePair[TKey, TValue]: ...
    def GetEnumerator(self) -> OrderedDictionary.Enumerator[TKey, TValue]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def IndexOf(self, key: TKey) -> int: ...
    def Insert(self, index: int, key: TKey, value: TValue) -> None: ...
    @overload
    def Remove(self, key: TKey) -> bool: ...
    @overload
    def Remove(self, key: TKey, value: TValue) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    @overload
    def SetAt(self, index: int, value: TValue) -> None: ...
    @overload
    def SetAt(self, index: int, key: TKey, value: TValue) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def TrimExcess(self) -> None: ...
    @overload
    def TrimExcess(self, capacity: int) -> None: ...
    @overload
    def TryAdd(self, key: TKey, value: TValue) -> bool: ...
    @overload
    def TryAdd(self, key: TKey, value: TValue, index: int) -> bool: ...
    @overload
    def TryGetValue(self, key: TKey, value: TValue) -> bool: ...
    @overload
    def TryGetValue(self, key: TKey, value: TValue, index: int) -> bool: ...

    class Enumerator(Generic[TKey, TValue]):
        Current: KeyValuePair[TKey, TValue]
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def MoveNext(self) -> bool: ...
        def ToString(self) -> str: ...

    class KeyCollection(Generic[TKey, TValue]):
        Count: int
        def Contains(self, key: TKey) -> bool: ...
        def CopyTo(self, array: list[TKey], arrayIndex: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> OrderedDictionary.KeyCollection.Enumerator[TKey, TValue]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

        class Enumerator(Generic[TKey, TValue]):
            Current: TKey
            def Equals(self, obj: Any) -> bool: ...
            def GetHashCode(self) -> int: ...
            def GetType(self) -> Any: ...
            def MoveNext(self) -> bool: ...
            def ToString(self) -> str: ...

    class ValueCollection(Generic[TKey, TValue]):
        Count: int
        def CopyTo(self, array: list[TValue], arrayIndex: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> OrderedDictionary.ValueCollection.Enumerator[TKey, TValue]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

        class Enumerator(Generic[TKey, TValue]):
            Current: TValue
            def Equals(self, obj: Any) -> bool: ...
            def GetHashCode(self) -> int: ...
            def GetType(self) -> Any: ...
            def MoveNext(self) -> bool: ...
            def ToString(self) -> str: ...

class PriorityQueue(Generic[TElement, TPriority]):
    Count: int
    Capacity: int
    Comparer: IComparer[TPriority]
    UnorderedItems: PriorityQueue.UnorderedItemsCollection[TElement, TPriority]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, initialCapacity: int) -> None: ...
    @overload
    def __init__(self, comparer: IComparer[TPriority]) -> None: ...
    @overload
    def __init__(self, initialCapacity: int, comparer: IComparer[TPriority]) -> None: ...
    @overload
    def __init__(self, items: IEnumerable[Any]) -> None: ...
    @overload
    def __init__(self, items: IEnumerable[Any], comparer: IComparer[TPriority]) -> None: ...
    def Clear(self) -> None: ...
    def Dequeue(self) -> TElement: ...
    def DequeueEnqueue(self, element: TElement, priority: TPriority) -> TElement: ...
    def Enqueue(self, element: TElement, priority: TPriority) -> None: ...
    def EnqueueDequeue(self, element: TElement, priority: TPriority) -> TElement: ...
    @overload
    def EnqueueRange(self, items: IEnumerable[Any]) -> None: ...
    @overload
    def EnqueueRange(self, elements: IEnumerable[TElement], priority: TPriority) -> None: ...
    def EnsureCapacity(self, capacity: int) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Peek(self) -> TElement: ...
    def Remove(self, element: TElement, removedElement: TElement, priority: TPriority, equalityComparer: IEqualityComparer[TElement] = ...) -> bool: ...
    def ToString(self) -> str: ...
    def TrimExcess(self) -> None: ...
    def TryDequeue(self, element: TElement, priority: TPriority) -> bool: ...
    def TryPeek(self, element: TElement, priority: TPriority) -> bool: ...

    class UnorderedItemsCollection(Generic[TElement, TPriority]):
        Count: int
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> PriorityQueue.UnorderedItemsCollection.Enumerator[TElement, TPriority]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

        class Enumerator(Generic[TElement, TPriority]):
            Current: Any
            def Dispose(self) -> None: ...
            def Equals(self, obj: Any) -> bool: ...
            def GetHashCode(self) -> int: ...
            def GetType(self) -> Any: ...
            def MoveNext(self) -> bool: ...
            def ToString(self) -> str: ...

class Queue(Generic[T]):
    Count: int
    Capacity: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, capacity: int) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[T]) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: T) -> bool: ...
    def CopyTo(self, array: list[T], arrayIndex: int) -> None: ...
    def Dequeue(self) -> T: ...
    def Enqueue(self, item: T) -> None: ...
    def EnsureCapacity(self, capacity: int) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetEnumerator(self) -> Queue.Enumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Peek(self) -> T: ...
    def ToArray(self) -> list[T]: ...
    def ToString(self) -> str: ...
    @overload
    def TrimExcess(self) -> None: ...
    @overload
    def TrimExcess(self, capacity: int) -> None: ...
    def TryDequeue(self, result: T) -> bool: ...
    def TryPeek(self, result: T) -> bool: ...

    class Enumerator(Generic[T]):
        Current: T
        def Dispose(self) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def MoveNext(self) -> bool: ...
        def ToString(self) -> str: ...

class ReferenceEqualityComparer:
    Instance: ClassVar[ReferenceEqualityComparer]
    @overload
    def Equals(self, x: Any, y: Any) -> bool: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def GetHashCode(self, obj: Any) -> int: ...
    @overload
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class SortedDictionary(Generic[TKey, TValue]):
    @overload
    def __getitem__(self, index: TKey) -> TValue: ...
    def __setitem__(self, index: TKey, value: TValue) -> None: ...
    Count: int
    Comparer: IComparer[TKey]
    Keys: SortedDictionary.KeyCollection[TKey, TValue]
    Values: SortedDictionary.ValueCollection[TKey, TValue]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, dictionary: IDictionary[TKey, TValue]) -> None: ...
    @overload
    def __init__(self, dictionary: IDictionary[TKey, TValue], comparer: IComparer[TKey]) -> None: ...
    @overload
    def __init__(self, comparer: IComparer[TKey]) -> None: ...
    def Add(self, key: TKey, value: TValue) -> None: ...
    def Clear(self) -> None: ...
    def ContainsKey(self, key: TKey) -> bool: ...
    def ContainsValue(self, value: TValue) -> bool: ...
    def CopyTo(self, array: list[KeyValuePair[TKey, TValue]], index: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetEnumerator(self) -> SortedDictionary.Enumerator[TKey, TValue]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Remove(self, key: TKey) -> bool: ...
    def ToString(self) -> str: ...
    def TryGetValue(self, key: TKey, value: TValue) -> bool: ...

    class Enumerator(Generic[TKey, TValue]):
        Current: KeyValuePair[TKey, TValue]
        def Dispose(self) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def MoveNext(self) -> bool: ...
        def ToString(self) -> str: ...

    class KeyCollection(Generic[TKey, TValue]):
        Count: int
        def __init__(self, dictionary: SortedDictionary[TKey, TValue]) -> None: ...
        def Contains(self, item: TKey) -> bool: ...
        def CopyTo(self, array: list[TKey], index: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> SortedDictionary.KeyCollection.Enumerator[TKey, TValue]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

        class Enumerator(Generic[TKey, TValue]):
            Current: TKey
            def Dispose(self) -> None: ...
            def Equals(self, obj: Any) -> bool: ...
            def GetHashCode(self) -> int: ...
            def GetType(self) -> Any: ...
            def MoveNext(self) -> bool: ...
            def ToString(self) -> str: ...

    class KeyValuePairComparer(Comparer[KeyValuePair[TKey, TValue]], Generic[TKey, TValue]):
        def __init__(self, keyComparer: IComparer[TKey]) -> None: ...
        def Compare(self, x: KeyValuePair[TKey, TValue], y: KeyValuePair[TKey, TValue]) -> int: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

    class ValueCollection(Generic[TKey, TValue]):
        Count: int
        def __init__(self, dictionary: SortedDictionary[TKey, TValue]) -> None: ...
        def CopyTo(self, array: list[TValue], index: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> SortedDictionary.ValueCollection.Enumerator[TKey, TValue]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

        class Enumerator(Generic[TKey, TValue]):
            Current: TValue
            def Dispose(self) -> None: ...
            def Equals(self, obj: Any) -> bool: ...
            def GetHashCode(self) -> int: ...
            def GetType(self) -> Any: ...
            def MoveNext(self) -> bool: ...
            def ToString(self) -> str: ...

class SortedList(Generic[TKey, TValue]):
    Capacity: int
    Comparer: IComparer[TKey]
    Count: int
    Keys: IList[TKey]
    Values: IList[TValue]
    @overload
    def __getitem__(self, index: TKey) -> TValue: ...
    def __setitem__(self, index: TKey, value: TValue) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, capacity: int) -> None: ...
    @overload
    def __init__(self, comparer: IComparer[TKey]) -> None: ...
    @overload
    def __init__(self, capacity: int, comparer: IComparer[TKey]) -> None: ...
    @overload
    def __init__(self, dictionary: IDictionary[TKey, TValue]) -> None: ...
    @overload
    def __init__(self, dictionary: IDictionary[TKey, TValue], comparer: IComparer[TKey]) -> None: ...
    def Add(self, key: TKey, value: TValue) -> None: ...
    def Clear(self) -> None: ...
    def ContainsKey(self, key: TKey) -> bool: ...
    def ContainsValue(self, value: TValue) -> bool: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetEnumerator(self) -> IEnumerator[KeyValuePair[TKey, TValue]]: ...
    def GetHashCode(self) -> int: ...
    def GetKeyAtIndex(self, index: int) -> TKey: ...
    def GetType(self) -> Any: ...
    def GetValueAtIndex(self, index: int) -> TValue: ...
    def IndexOfKey(self, key: TKey) -> int: ...
    def IndexOfValue(self, value: TValue) -> int: ...
    def Remove(self, key: TKey) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    def SetValueAtIndex(self, index: int, value: TValue) -> None: ...
    def ToString(self) -> str: ...
    def TrimExcess(self) -> None: ...
    def TryGetValue(self, key: TKey, value: TValue) -> bool: ...

    class KeyList(Generic[TKey, TValue]):
        Count: int
        IsReadOnly: bool
        @overload
        def __getitem__(self, index: int) -> TKey: ...
        def __setitem__(self, index: int, value: TKey) -> None: ...
        def Add(self, key: TKey) -> None: ...
        def Clear(self) -> None: ...
        def Contains(self, key: TKey) -> bool: ...
        def CopyTo(self, array: list[TKey], arrayIndex: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> IEnumerator[TKey]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def IndexOf(self, key: TKey) -> int: ...
        def Insert(self, index: int, value: TKey) -> None: ...
        def Remove(self, key: TKey) -> bool: ...
        def RemoveAt(self, index: int) -> None: ...
        def ToString(self) -> str: ...

    class ValueList(Generic[TKey, TValue]):
        Count: int
        IsReadOnly: bool
        @overload
        def __getitem__(self, index: int) -> TValue: ...
        def __setitem__(self, index: int, value: TValue) -> None: ...
        def Add(self, key: TValue) -> None: ...
        def Clear(self) -> None: ...
        def Contains(self, value: TValue) -> bool: ...
        def CopyTo(self, array: list[TValue], arrayIndex: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> IEnumerator[TValue]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def IndexOf(self, value: TValue) -> int: ...
        def Insert(self, index: int, value: TValue) -> None: ...
        def Remove(self, value: TValue) -> bool: ...
        def RemoveAt(self, index: int) -> None: ...
        def ToString(self) -> str: ...

class SortedSet(Generic[T]):
    Count: int
    Comparer: IComparer[T]
    Min: T
    Max: T
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, comparer: IComparer[T]) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[T]) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[T], comparer: IComparer[T]) -> None: ...
    def Add(self, item: T) -> bool: ...
    def Clear(self) -> None: ...
    def Contains(self, item: T) -> bool: ...
    @overload
    def CopyTo(self, array: list[T]) -> None: ...
    @overload
    def CopyTo(self, array: list[T], index: int) -> None: ...
    @overload
    def CopyTo(self, array: list[T], index: int, count: int) -> None: ...
    @overload
    @staticmethod
    def CreateSetComparer() -> IEqualityComparer[SortedSet[T]]: ...
    @overload
    @staticmethod
    def CreateSetComparer(memberEqualityComparer: IEqualityComparer[T]) -> IEqualityComparer[SortedSet[T]]: ...
    def Equals(self, obj: Any) -> bool: ...
    def ExceptWith(self, other: IEnumerable[T]) -> None: ...
    def GetEnumerator(self) -> SortedSet.Enumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def GetViewBetween(self, lowerValue: T, upperValue: T) -> SortedSet[T]: ...
    def IntersectWith(self, other: IEnumerable[T]) -> None: ...
    def IsProperSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsProperSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def Overlaps(self, other: IEnumerable[T]) -> bool: ...
    def Remove(self, item: T) -> bool: ...
    def RemoveWhere(self, match: Callable[..., bool]) -> int: ...
    def Reverse(self) -> IEnumerable[T]: ...
    def SetEquals(self, other: IEnumerable[T]) -> bool: ...
    def SymmetricExceptWith(self, other: IEnumerable[T]) -> None: ...
    def ToString(self) -> str: ...
    def TryGetValue(self, equalValue: T, actualValue: T) -> bool: ...
    def UnionWith(self, other: IEnumerable[T]) -> None: ...

    class Enumerator(Generic[T]):
        Current: T
        def Dispose(self) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def MoveNext(self) -> bool: ...
        def ToString(self) -> str: ...

class Stack(Generic[T]):
    Count: int
    Capacity: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, capacity: int) -> None: ...
    @overload
    def __init__(self, collection: IEnumerable[T]) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: T) -> bool: ...
    def CopyTo(self, array: list[T], arrayIndex: int) -> None: ...
    def EnsureCapacity(self, capacity: int) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetEnumerator(self) -> Stack.Enumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Peek(self) -> T: ...
    def Pop(self) -> T: ...
    def Push(self, item: T) -> None: ...
    def ToArray(self) -> list[T]: ...
    def ToString(self) -> str: ...
    @overload
    def TrimExcess(self) -> None: ...
    @overload
    def TrimExcess(self, capacity: int) -> None: ...
    def TryPeek(self, result: T) -> bool: ...
    def TryPop(self, result: T) -> bool: ...

    class Enumerator(Generic[T]):
        Current: T
        def Dispose(self) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def MoveNext(self) -> bool: ...
        def ToString(self) -> str: ...

class TreeSet(SortedSet[T], Generic[T]):
    Count: int
    Comparer: IComparer[T]
    Min: T
    Max: T
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, comparer: IComparer[T]) -> None: ...
    def Add(self, item: T) -> bool: ...
    def Clear(self) -> None: ...
    def Contains(self, item: T) -> bool: ...
    @overload
    def CopyTo(self, array: list[T]) -> None: ...
    @overload
    def CopyTo(self, array: list[T], index: int) -> None: ...
    @overload
    def CopyTo(self, array: list[T], index: int, count: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def ExceptWith(self, other: IEnumerable[T]) -> None: ...
    def GetEnumerator(self) -> SortedSet.Enumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def GetViewBetween(self, lowerValue: T, upperValue: T) -> SortedSet[T]: ...
    def IntersectWith(self, other: IEnumerable[T]) -> None: ...
    def IsProperSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsProperSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSubsetOf(self, other: IEnumerable[T]) -> bool: ...
    def IsSupersetOf(self, other: IEnumerable[T]) -> bool: ...
    def Overlaps(self, other: IEnumerable[T]) -> bool: ...
    def Remove(self, item: T) -> bool: ...
    def RemoveWhere(self, match: Callable[..., bool]) -> int: ...
    def Reverse(self) -> IEnumerable[T]: ...
    def SetEquals(self, other: IEnumerable[T]) -> bool: ...
    def SymmetricExceptWith(self, other: IEnumerable[T]) -> None: ...
    def ToString(self) -> str: ...
    def TryGetValue(self, equalValue: T, actualValue: T) -> bool: ...
    def UnionWith(self, other: IEnumerable[T]) -> None: ...
