from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload
import System

T = TypeVar("T")
TKey = TypeVar("TKey")
TValue = TypeVar("TValue")

class Collection(Generic[T]):
    Count: int
    @overload
    def __getitem__(self, index: int) -> T: ...
    def __setitem__(self, index: int, value: T) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, list: System.Collections.Generic.IList[T]) -> None: ...
    def Add(self, item: T) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: T) -> bool: ...
    def CopyTo(self, array: list[T], index: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetEnumerator(self) -> System.Collections.Generic.IEnumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def IndexOf(self, item: T) -> int: ...
    def Insert(self, index: int, item: T) -> None: ...
    def Remove(self, item: T) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToString(self) -> str: ...

class ReadOnlyCollection_:
    @staticmethod
    def CreateCollection(values: Any) -> ReadOnlyCollection[T]: ...
    @staticmethod
    def CreateSet(values: Any) -> ReadOnlySet[T]: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ReadOnlyCollection(Generic[T]):
    Empty: ClassVar[ReadOnlyCollection[T]]
    Count: int
    @overload
    def __getitem__(self, index: int) -> T: ...
    def __init__(self, list: System.Collections.Generic.IList[T]) -> None: ...
    def Contains(self, value: T) -> bool: ...
    def CopyTo(self, array: list[T], index: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetEnumerator(self) -> System.Collections.Generic.IEnumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def IndexOf(self, value: T) -> int: ...
    def ToString(self) -> str: ...

class ReadOnlyDictionary(Generic[TKey, TValue]):
    Empty: ClassVar[ReadOnlyDictionary[TKey, TValue]]
    Keys: ReadOnlyDictionary.KeyCollection[TKey, TValue]
    Values: ReadOnlyDictionary.ValueCollection[TKey, TValue]
    @overload
    def __getitem__(self, index: TKey) -> TValue: ...
    Count: int
    def __init__(self, dictionary: System.Collections.Generic.IDictionary[TKey, TValue]) -> None: ...
    def ContainsKey(self, key: TKey) -> bool: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetEnumerator(self) -> System.Collections.Generic.IEnumerator[System.Collections.Generic.KeyValuePair[TKey, TValue]]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def TryGetValue(self, key: TKey, value: TValue) -> bool: ...

    class KeyCollection(Generic[TKey, TValue]):
        Count: int
        def Contains(self, item: TKey) -> bool: ...
        def CopyTo(self, array: list[TKey], arrayIndex: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> System.Collections.Generic.IEnumerator[TKey]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

    class ValueCollection(Generic[TKey, TValue]):
        Count: int
        def CopyTo(self, array: list[TValue], arrayIndex: int) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetEnumerator(self) -> System.Collections.Generic.IEnumerator[TValue]: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

class ReadOnlySet(Generic[T]):
    Empty: ClassVar[ReadOnlySet[T]]
    Count: int
    def __init__(self, set: System.Collections.Generic.ISet[T]) -> None: ...
    def Contains(self, item: T) -> bool: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetEnumerator(self) -> System.Collections.Generic.IEnumerator[T]: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def IsProperSubsetOf(self, other: System.Collections.Generic.IEnumerable[T]) -> bool: ...
    def IsProperSupersetOf(self, other: System.Collections.Generic.IEnumerable[T]) -> bool: ...
    def IsSubsetOf(self, other: System.Collections.Generic.IEnumerable[T]) -> bool: ...
    def IsSupersetOf(self, other: System.Collections.Generic.IEnumerable[T]) -> bool: ...
    def Overlaps(self, other: System.Collections.Generic.IEnumerable[T]) -> bool: ...
    def SetEquals(self, other: System.Collections.Generic.IEnumerable[T]) -> bool: ...
    def ToString(self) -> str: ...
