from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload
import System

T = TypeVar("T")
TState = TypeVar("TState")

class AbandonedMutexException:
    Mutex: Mutex
    MutexIndex: int
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, inner: Any) -> None: ...
    @overload
    def __init__(self, location: int, handle: WaitHandle) -> None: ...
    @overload
    def __init__(self, message: str, location: int, handle: WaitHandle) -> None: ...
    @overload
    def __init__(self, message: str, inner: Any, location: int, handle: WaitHandle) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ApartmentState(IntEnum):
    STA = 0
    MTA = 1
    Unknown = 2

class AsyncFlowControl:
    def Dispose(self) -> None: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def Equals(self, obj: AsyncFlowControl) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def Undo(self) -> None: ...

class AsyncLocalValueChangedArgs(Generic[T]):
    PreviousValue: T
    CurrentValue: T
    ThreadContextChanged: bool
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class AsyncLocal(Generic[T]):
    Value: T
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, valueChangedHandler: Callable[..., None]) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class AutoResetEvent(EventWaitHandle):
    Handle: Any
    SafeWaitHandle: Any
    def __init__(self, initialState: bool) -> None: ...
    def Close(self) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    def Reset(self) -> bool: ...
    def Set(self) -> bool: ...
    def ToString(self) -> str: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any) -> bool: ...
    @overload
    def WaitOne(self) -> bool: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int, exitContext: bool) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any, exitContext: bool) -> bool: ...

class Barrier:
    ParticipantsRemaining: int
    ParticipantCount: int
    CurrentPhaseNumber: int
    @overload
    def __init__(self, participantCount: int) -> None: ...
    @overload
    def __init__(self, participantCount: int, postPhaseAction: Callable[..., None]) -> None: ...
    def AddParticipant(self) -> int: ...
    def AddParticipants(self, participantCount: int) -> int: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def RemoveParticipant(self) -> None: ...
    def RemoveParticipants(self, participantCount: int) -> None: ...
    @overload
    def SignalAndWait(self) -> None: ...
    @overload
    def SignalAndWait(self, cancellationToken: CancellationToken) -> None: ...
    @overload
    def SignalAndWait(self, timeout: Any) -> bool: ...
    @overload
    def SignalAndWait(self, timeout: Any, cancellationToken: CancellationToken) -> bool: ...
    @overload
    def SignalAndWait(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def SignalAndWait(self, millisecondsTimeout: int, cancellationToken: CancellationToken) -> bool: ...
    def ToString(self) -> str: ...

class BarrierPostPhaseException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, innerException: Any) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class CancellationToken:
    None_: ClassVar[CancellationToken]
    IsCancellationRequested: bool
    CanBeCanceled: bool
    WaitHandle: WaitHandle
    def __init__(self, canceled: bool) -> None: ...
    @overload
    def Equals(self, other: CancellationToken) -> bool: ...
    @overload
    def Equals(self, other: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def Register(self, callback: Callable[..., None]) -> CancellationTokenRegistration: ...
    @overload
    def Register(self, callback: Callable[..., None], useSynchronizationContext: bool) -> CancellationTokenRegistration: ...
    @overload
    def Register(self, callback: Callable[..., None], state: Any) -> CancellationTokenRegistration: ...
    @overload
    def Register(self, callback: Callable[..., None], state: Any) -> CancellationTokenRegistration: ...
    @overload
    def Register(self, callback: Callable[..., None], state: Any, useSynchronizationContext: bool) -> CancellationTokenRegistration: ...
    def ThrowIfCancellationRequested(self) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def UnsafeRegister(self, callback: Callable[..., None], state: Any) -> CancellationTokenRegistration: ...
    @overload
    def UnsafeRegister(self, callback: Callable[..., None], state: Any) -> CancellationTokenRegistration: ...

class CancellationTokenRegistration:
    Token: CancellationToken
    def Dispose(self) -> None: ...
    def DisposeAsync(self) -> System.Threading.Tasks.ValueTask_: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def Equals(self, other: CancellationTokenRegistration) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def Unregister(self) -> bool: ...

class CancellationTokenSource:
    IsCancellationRequested: bool
    Token: CancellationToken
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, delay: Any) -> None: ...
    @overload
    def __init__(self, delay: Any, timeProvider: Any) -> None: ...
    @overload
    def __init__(self, millisecondsDelay: int) -> None: ...
    @overload
    def Cancel(self) -> None: ...
    @overload
    def Cancel(self, throwOnFirstException: bool) -> None: ...
    @overload
    def CancelAfter(self, delay: Any) -> None: ...
    @overload
    def CancelAfter(self, millisecondsDelay: int) -> None: ...
    def CancelAsync(self) -> System.Threading.Tasks.Task_: ...
    @overload
    @staticmethod
    def CreateLinkedTokenSource(token1: CancellationToken, token2: CancellationToken) -> CancellationTokenSource: ...
    @overload
    @staticmethod
    def CreateLinkedTokenSource(token: CancellationToken) -> CancellationTokenSource: ...
    @overload
    @staticmethod
    def CreateLinkedTokenSource(tokens: list[CancellationToken]) -> CancellationTokenSource: ...
    @overload
    @staticmethod
    def CreateLinkedTokenSource(tokens: Any) -> CancellationTokenSource: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def TryReset(self) -> bool: ...

class CompressedStack:
    @staticmethod
    def Capture() -> CompressedStack: ...
    def CreateCopy(self) -> CompressedStack: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def GetCompressedStack() -> CompressedStack: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def Run(compressedStack: CompressedStack, callback: Callable[..., None], state: Any) -> None: ...
    def ToString(self) -> str: ...

ContextCallback = Callable[..., None]

class CountdownEvent:
    CurrentCount: int
    InitialCount: int
    IsSet: bool
    WaitHandle: WaitHandle
    def __init__(self, initialCount: int) -> None: ...
    @overload
    def AddCount(self) -> None: ...
    @overload
    def AddCount(self, signalCount: int) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def Reset(self) -> None: ...
    @overload
    def Reset(self, count: int) -> None: ...
    @overload
    def Signal(self) -> bool: ...
    @overload
    def Signal(self, signalCount: int) -> bool: ...
    def ToString(self) -> str: ...
    @overload
    def TryAddCount(self) -> bool: ...
    @overload
    def TryAddCount(self, signalCount: int) -> bool: ...
    @overload
    def Wait(self) -> None: ...
    @overload
    def Wait(self, cancellationToken: CancellationToken) -> None: ...
    @overload
    def Wait(self, timeout: Any) -> bool: ...
    @overload
    def Wait(self, timeout: Any, cancellationToken: CancellationToken) -> bool: ...
    @overload
    def Wait(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def Wait(self, millisecondsTimeout: int, cancellationToken: CancellationToken) -> bool: ...

class EventResetMode(IntEnum):
    AutoReset = 0
    ManualReset = 1

class EventWaitHandle(WaitHandle):
    Handle: Any
    SafeWaitHandle: Any
    @overload
    def __init__(self, initialState: bool, mode: EventResetMode) -> None: ...
    @overload
    def __init__(self, initialState: bool, mode: EventResetMode, name: str, options: NamedWaitHandleOptions) -> None: ...
    @overload
    def __init__(self, initialState: bool, mode: EventResetMode, name: str) -> None: ...
    @overload
    def __init__(self, initialState: bool, mode: EventResetMode, name: str, options: NamedWaitHandleOptions, createdNew: bool) -> None: ...
    @overload
    def __init__(self, initialState: bool, mode: EventResetMode, name: str, createdNew: bool) -> None: ...
    def Close(self) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    @overload
    @staticmethod
    def OpenExisting(name: str, options: NamedWaitHandleOptions) -> EventWaitHandle: ...
    @overload
    @staticmethod
    def OpenExisting(name: str) -> EventWaitHandle: ...
    def Reset(self) -> bool: ...
    def Set(self) -> bool: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def TryOpenExisting(name: str, options: NamedWaitHandleOptions, result: EventWaitHandle) -> bool: ...
    @overload
    @staticmethod
    def TryOpenExisting(name: str, result: EventWaitHandle) -> bool: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any) -> bool: ...
    @overload
    def WaitOne(self) -> bool: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int, exitContext: bool) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any, exitContext: bool) -> bool: ...

class ExecutionContext:
    @staticmethod
    def Capture() -> ExecutionContext: ...
    def CreateCopy(self) -> ExecutionContext: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def IsFlowSuppressed() -> bool: ...
    @staticmethod
    def Restore(executionContext: ExecutionContext) -> None: ...
    @staticmethod
    def RestoreFlow() -> None: ...
    @staticmethod
    def Run(executionContext: ExecutionContext, callback: Callable[..., None], state: Any) -> None: ...
    @staticmethod
    def SuppressFlow() -> AsyncFlowControl: ...
    def ToString(self) -> str: ...

class HostExecutionContext:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, state: Any) -> None: ...
    def CreateCopy(self) -> HostExecutionContext: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class HostExecutionContextManager:
    def __init__(self) -> None: ...
    def Capture(self) -> HostExecutionContext: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Revert(self, previousState: Any) -> None: ...
    def SetHostExecutionContext(self, hostExecutionContext: HostExecutionContext) -> Any: ...
    def ToString(self) -> str: ...

IOCompletionCallback = Callable[..., None]

class IThreadPoolWorkItem:
    def Execute(self) -> None: ...

class ITimer:
    def Change(self, dueTime: Any, period: Any) -> bool: ...

class Interlocked:
    @overload
    @staticmethod
    def Add(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Add(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Add(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Add(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def And(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def And(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def And(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def And(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def CompareExchange(location1: int, value: int, comparand: int) -> int: ...
    @overload
    @staticmethod
    def CompareExchange(location1: int, value: int, comparand: int) -> int: ...
    @overload
    @staticmethod
    def CompareExchange(location1: Any, value: Any, comparand: Any) -> Any: ...
    @overload
    @staticmethod
    def CompareExchange(location1: int, value: int, comparand: int) -> int: ...
    @overload
    @staticmethod
    def CompareExchange(location1: int, value: int, comparand: int) -> int: ...
    @overload
    @staticmethod
    def CompareExchange(location1: int, value: int, comparand: int) -> int: ...
    @overload
    @staticmethod
    def CompareExchange(location1: int, value: int, comparand: int) -> int: ...
    @overload
    @staticmethod
    def CompareExchange(location1: int, value: int, comparand: int) -> int: ...
    @overload
    @staticmethod
    def CompareExchange(location1: int, value: int, comparand: int) -> int: ...
    @overload
    @staticmethod
    def CompareExchange(location1: float, value: float, comparand: float) -> float: ...
    @overload
    @staticmethod
    def CompareExchange(location1: float, value: float, comparand: float) -> float: ...
    @overload
    @staticmethod
    def CompareExchange(location1: Any, value: Any, comparand: Any) -> Any: ...
    @overload
    @staticmethod
    def CompareExchange(location1: Any, value: Any, comparand: Any) -> Any: ...
    @overload
    @staticmethod
    def CompareExchange(location1: T, value: T, comparand: T) -> T: ...
    @overload
    @staticmethod
    def Decrement(location: int) -> int: ...
    @overload
    @staticmethod
    def Decrement(location: int) -> int: ...
    @overload
    @staticmethod
    def Decrement(location: int) -> int: ...
    @overload
    @staticmethod
    def Decrement(location: int) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    @overload
    @staticmethod
    def Exchange(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Exchange(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Exchange(location1: Any, value: Any) -> Any: ...
    @overload
    @staticmethod
    def Exchange(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Exchange(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Exchange(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Exchange(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Exchange(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Exchange(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Exchange(location1: float, value: float) -> float: ...
    @overload
    @staticmethod
    def Exchange(location1: float, value: float) -> float: ...
    @overload
    @staticmethod
    def Exchange(location1: Any, value: Any) -> Any: ...
    @overload
    @staticmethod
    def Exchange(location1: Any, value: Any) -> Any: ...
    @overload
    @staticmethod
    def Exchange(location1: T, value: T) -> T: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    @staticmethod
    def Increment(location: int) -> int: ...
    @overload
    @staticmethod
    def Increment(location: int) -> int: ...
    @overload
    @staticmethod
    def Increment(location: int) -> int: ...
    @overload
    @staticmethod
    def Increment(location: int) -> int: ...
    @staticmethod
    def MemoryBarrier() -> None: ...
    @staticmethod
    def MemoryBarrierProcessWide() -> None: ...
    @overload
    @staticmethod
    def Or(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Or(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Or(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Or(location1: int, value: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    def ToString(self) -> str: ...

class LazyInitializer:
    @overload
    @staticmethod
    def EnsureInitialized(target: T) -> T: ...
    @overload
    @staticmethod
    def EnsureInitialized(target: T, valueFactory: Callable[..., T]) -> T: ...
    @overload
    @staticmethod
    def EnsureInitialized(target: T, initialized: bool, syncLock: Any) -> T: ...
    @overload
    @staticmethod
    def EnsureInitialized(target: T, initialized: bool, syncLock: Any, valueFactory: Callable[..., T]) -> T: ...
    @overload
    @staticmethod
    def EnsureInitialized(target: T, syncLock: Any, valueFactory: Callable[..., T]) -> T: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class LazyThreadSafetyMode(IntEnum):
    None_ = 0
    PublicationOnly = 1
    ExecutionAndPublication = 2

class Lock:
    IsHeldByCurrentThread: bool
    def __init__(self) -> None: ...
    def Enter(self) -> None: ...
    def EnterScope(self) -> Lock.Scope: ...
    def Equals(self, obj: Any) -> bool: ...
    def Exit(self) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    @overload
    def TryEnter(self) -> bool: ...
    @overload
    def TryEnter(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def TryEnter(self, timeout: Any) -> bool: ...

    class Scope:
        def Dispose(self) -> None: ...
        def Equals(self, obj: Any) -> bool: ...
        def GetHashCode(self) -> int: ...
        def GetType(self) -> Any: ...
        def ToString(self) -> str: ...

class LockCookie:
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def Equals(self, obj: LockCookie) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class LockRecursionException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class LockRecursionPolicy(IntEnum):
    NoRecursion = 0
    SupportsRecursion = 1

class ManualResetEvent(EventWaitHandle):
    Handle: Any
    SafeWaitHandle: Any
    def __init__(self, initialState: bool) -> None: ...
    def Close(self) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    def Reset(self) -> bool: ...
    def Set(self) -> bool: ...
    def ToString(self) -> str: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any) -> bool: ...
    @overload
    def WaitOne(self) -> bool: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int, exitContext: bool) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any, exitContext: bool) -> bool: ...

class ManualResetEventSlim:
    WaitHandle: WaitHandle
    IsSet: bool
    SpinCount: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, initialState: bool) -> None: ...
    @overload
    def __init__(self, initialState: bool, spinCount: int) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Reset(self) -> None: ...
    def Set(self) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Wait(self) -> None: ...
    @overload
    def Wait(self, cancellationToken: CancellationToken) -> None: ...
    @overload
    def Wait(self, timeout: Any) -> bool: ...
    @overload
    def Wait(self, timeout: Any, cancellationToken: CancellationToken) -> bool: ...
    @overload
    def Wait(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def Wait(self, millisecondsTimeout: int, cancellationToken: CancellationToken) -> bool: ...

class Monitor:
    LockContentionCount: ClassVar[int]
    @overload
    @staticmethod
    def Enter(obj: Any) -> None: ...
    @overload
    @staticmethod
    def Enter(obj: Any, lockTaken: bool) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def Exit(obj: Any) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def IsEntered(obj: Any) -> bool: ...
    @staticmethod
    def Pulse(obj: Any) -> None: ...
    @staticmethod
    def PulseAll(obj: Any) -> None: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def TryEnter(obj: Any) -> bool: ...
    @overload
    @staticmethod
    def TryEnter(obj: Any, lockTaken: bool) -> None: ...
    @overload
    @staticmethod
    def TryEnter(obj: Any, millisecondsTimeout: int) -> bool: ...
    @overload
    @staticmethod
    def TryEnter(obj: Any, millisecondsTimeout: int, lockTaken: bool) -> None: ...
    @overload
    @staticmethod
    def TryEnter(obj: Any, timeout: Any) -> bool: ...
    @overload
    @staticmethod
    def TryEnter(obj: Any, timeout: Any, lockTaken: bool) -> None: ...
    @overload
    @staticmethod
    def Wait(obj: Any, millisecondsTimeout: int) -> bool: ...
    @overload
    @staticmethod
    def Wait(obj: Any, timeout: Any) -> bool: ...
    @overload
    @staticmethod
    def Wait(obj: Any) -> bool: ...
    @overload
    @staticmethod
    def Wait(obj: Any, millisecondsTimeout: int, exitContext: bool) -> bool: ...
    @overload
    @staticmethod
    def Wait(obj: Any, timeout: Any, exitContext: bool) -> bool: ...

class Mutex(WaitHandle):
    Handle: Any
    SafeWaitHandle: Any
    @overload
    def __init__(self, initiallyOwned: bool, name: str, options: NamedWaitHandleOptions, createdNew: bool) -> None: ...
    @overload
    def __init__(self, initiallyOwned: bool, name: str, createdNew: bool) -> None: ...
    @overload
    def __init__(self, initiallyOwned: bool, name: str, options: NamedWaitHandleOptions) -> None: ...
    @overload
    def __init__(self, initiallyOwned: bool, name: str) -> None: ...
    @overload
    def __init__(self, name: str, options: NamedWaitHandleOptions) -> None: ...
    @overload
    def __init__(self, initiallyOwned: bool) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def Close(self) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    @overload
    @staticmethod
    def OpenExisting(name: str, options: NamedWaitHandleOptions) -> Mutex: ...
    @overload
    @staticmethod
    def OpenExisting(name: str) -> Mutex: ...
    def ReleaseMutex(self) -> None: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def TryOpenExisting(name: str, options: NamedWaitHandleOptions, result: Mutex) -> bool: ...
    @overload
    @staticmethod
    def TryOpenExisting(name: str, result: Mutex) -> bool: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any) -> bool: ...
    @overload
    def WaitOne(self) -> bool: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int, exitContext: bool) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any, exitContext: bool) -> bool: ...

class NamedWaitHandleOptions:
    CurrentUserOnly: bool
    CurrentSessionOnly: bool
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class NativeOverlapped:
    InternalLow: Any
    InternalHigh: Any
    OffsetLow: int
    OffsetHigh: int
    EventHandle: Any
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class Overlapped:
    AsyncResult: Any
    OffsetLow: int
    OffsetHigh: int
    EventHandle: int
    EventHandleIntPtr: Any
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, offsetLo: int, offsetHi: int, hEvent: Any, ar: Any) -> None: ...
    @overload
    def __init__(self, offsetLo: int, offsetHi: int, hEvent: int, ar: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def Free(nativeOverlappedPtr: Any) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def Pack(self, iocb: Callable[..., None]) -> Any: ...
    @overload
    def Pack(self, iocb: Callable[..., None], userData: Any) -> Any: ...
    def ToString(self) -> str: ...
    @staticmethod
    def Unpack(nativeOverlappedPtr: Any) -> Overlapped: ...
    @overload
    def UnsafePack(self, iocb: Callable[..., None]) -> Any: ...
    @overload
    def UnsafePack(self, iocb: Callable[..., None], userData: Any) -> Any: ...

ParameterizedThreadStart = Callable[..., None]

class PeriodicTimer:
    Period: Any
    @overload
    def __init__(self, period: Any) -> None: ...
    @overload
    def __init__(self, period: Any, timeProvider: Any) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def WaitForNextTickAsync(self, cancellationToken: CancellationToken = ...) -> System.Threading.Tasks.ValueTask[bool]: ...

class PreAllocatedOverlapped:
    def __init__(self, callback: Callable[..., None], state: Any, pinData: Any) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    @staticmethod
    def UnsafeCreate(callback: Callable[..., None], state: Any, pinData: Any) -> PreAllocatedOverlapped: ...

class ReaderWriterLock:
    IsReaderLockHeld: bool
    IsWriterLockHeld: bool
    WriterSeqNum: int
    def __init__(self) -> None: ...
    @overload
    def AcquireReaderLock(self, millisecondsTimeout: int) -> None: ...
    @overload
    def AcquireReaderLock(self, timeout: Any) -> None: ...
    @overload
    def AcquireWriterLock(self, millisecondsTimeout: int) -> None: ...
    @overload
    def AcquireWriterLock(self, timeout: Any) -> None: ...
    def AnyWritersSince(self, seqNum: int) -> bool: ...
    def DowngradeFromWriterLock(self, lockCookie: LockCookie) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ReleaseLock(self) -> LockCookie: ...
    def ReleaseReaderLock(self) -> None: ...
    def ReleaseWriterLock(self) -> None: ...
    def RestoreLock(self, lockCookie: LockCookie) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def UpgradeToWriterLock(self, millisecondsTimeout: int) -> LockCookie: ...
    @overload
    def UpgradeToWriterLock(self, timeout: Any) -> LockCookie: ...

class ReaderWriterLockSlim:
    IsReadLockHeld: bool
    IsUpgradeableReadLockHeld: bool
    IsWriteLockHeld: bool
    RecursionPolicy: LockRecursionPolicy
    CurrentReadCount: int
    RecursiveReadCount: int
    RecursiveUpgradeCount: int
    RecursiveWriteCount: int
    WaitingReadCount: int
    WaitingUpgradeCount: int
    WaitingWriteCount: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, recursionPolicy: LockRecursionPolicy) -> None: ...
    def Dispose(self) -> None: ...
    def EnterReadLock(self) -> None: ...
    def EnterUpgradeableReadLock(self) -> None: ...
    def EnterWriteLock(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def ExitReadLock(self) -> None: ...
    def ExitUpgradeableReadLock(self) -> None: ...
    def ExitWriteLock(self) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    @overload
    def TryEnterReadLock(self, timeout: Any) -> bool: ...
    @overload
    def TryEnterReadLock(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def TryEnterUpgradeableReadLock(self, timeout: Any) -> bool: ...
    @overload
    def TryEnterUpgradeableReadLock(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def TryEnterWriteLock(self, timeout: Any) -> bool: ...
    @overload
    def TryEnterWriteLock(self, millisecondsTimeout: int) -> bool: ...

class RegisteredWaitHandle:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    def ToString(self) -> str: ...
    def Unregister(self, waitObject: WaitHandle) -> bool: ...

class Semaphore(WaitHandle):
    Handle: Any
    SafeWaitHandle: Any
    @overload
    def __init__(self, initialCount: int, maximumCount: int) -> None: ...
    @overload
    def __init__(self, initialCount: int, maximumCount: int, name: str, options: NamedWaitHandleOptions) -> None: ...
    @overload
    def __init__(self, initialCount: int, maximumCount: int, name: str) -> None: ...
    @overload
    def __init__(self, initialCount: int, maximumCount: int, name: str, options: NamedWaitHandleOptions, createdNew: bool) -> None: ...
    @overload
    def __init__(self, initialCount: int, maximumCount: int, name: str, createdNew: bool) -> None: ...
    def Close(self) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    @overload
    @staticmethod
    def OpenExisting(name: str, options: NamedWaitHandleOptions) -> Semaphore: ...
    @overload
    @staticmethod
    def OpenExisting(name: str) -> Semaphore: ...
    @overload
    def Release(self) -> int: ...
    @overload
    def Release(self, releaseCount: int) -> int: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def TryOpenExisting(name: str, options: NamedWaitHandleOptions, result: Semaphore) -> bool: ...
    @overload
    @staticmethod
    def TryOpenExisting(name: str, result: Semaphore) -> bool: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any) -> bool: ...
    @overload
    def WaitOne(self) -> bool: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int, exitContext: bool) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any, exitContext: bool) -> bool: ...

class SemaphoreFullException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class SemaphoreSlim:
    CurrentCount: int
    AvailableWaitHandle: WaitHandle
    @overload
    def __init__(self, initialCount: int) -> None: ...
    @overload
    def __init__(self, initialCount: int, maxCount: int) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    def Release(self) -> int: ...
    @overload
    def Release(self, releaseCount: int) -> int: ...
    def ToString(self) -> str: ...
    @overload
    def Wait(self) -> None: ...
    @overload
    def Wait(self, cancellationToken: CancellationToken) -> None: ...
    @overload
    def Wait(self, timeout: Any) -> bool: ...
    @overload
    def Wait(self, timeout: Any, cancellationToken: CancellationToken) -> bool: ...
    @overload
    def Wait(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def Wait(self, millisecondsTimeout: int, cancellationToken: CancellationToken) -> bool: ...
    @overload
    def WaitAsync(self) -> System.Threading.Tasks.Task_: ...
    @overload
    def WaitAsync(self, cancellationToken: CancellationToken) -> System.Threading.Tasks.Task_: ...
    @overload
    def WaitAsync(self, millisecondsTimeout: int) -> System.Threading.Tasks.Task[bool]: ...
    @overload
    def WaitAsync(self, timeout: Any) -> System.Threading.Tasks.Task[bool]: ...
    @overload
    def WaitAsync(self, timeout: Any, cancellationToken: CancellationToken) -> System.Threading.Tasks.Task[bool]: ...
    @overload
    def WaitAsync(self, millisecondsTimeout: int, cancellationToken: CancellationToken) -> System.Threading.Tasks.Task[bool]: ...

SendOrPostCallback = Callable[..., None]

class SpinLock:
    IsHeld: bool
    IsHeldByCurrentThread: bool
    IsThreadOwnerTrackingEnabled: bool
    def __init__(self, enableThreadOwnerTracking: bool) -> None: ...
    def Enter(self, lockTaken: bool) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def Exit(self) -> None: ...
    @overload
    def Exit(self, useMemoryBarrier: bool) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    @overload
    def TryEnter(self, lockTaken: bool) -> None: ...
    @overload
    def TryEnter(self, timeout: Any, lockTaken: bool) -> None: ...
    @overload
    def TryEnter(self, millisecondsTimeout: int, lockTaken: bool) -> None: ...

class SpinWait:
    Count: int
    NextSpinWillYield: bool
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def Reset(self) -> None: ...
    @overload
    def SpinOnce(self) -> None: ...
    @overload
    def SpinOnce(self, sleep1Threshold: int) -> None: ...
    @overload
    @staticmethod
    def SpinUntil(condition: Callable[..., bool]) -> None: ...
    @overload
    @staticmethod
    def SpinUntil(condition: Callable[..., bool], timeout: Any) -> bool: ...
    @overload
    @staticmethod
    def SpinUntil(condition: Callable[..., bool], millisecondsTimeout: int) -> bool: ...
    def ToString(self) -> str: ...

class SynchronizationContext:
    Current: ClassVar[SynchronizationContext]
    def __init__(self) -> None: ...
    def CreateCopy(self) -> SynchronizationContext: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def IsWaitNotificationRequired(self) -> bool: ...
    def OperationCompleted(self) -> None: ...
    def OperationStarted(self) -> None: ...
    def Post(self, d: Callable[..., None], state: Any) -> None: ...
    def Send(self, d: Callable[..., None], state: Any) -> None: ...
    @staticmethod
    def SetSynchronizationContext(syncContext: SynchronizationContext) -> None: ...
    def ToString(self) -> str: ...
    def Wait(self, waitHandles: list[Any], waitAll: bool, millisecondsTimeout: int) -> int: ...

class SynchronizationLockException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class Thread:
    ManagedThreadId: int
    IsAlive: bool
    IsBackground: bool
    IsThreadPoolThread: bool
    Priority: ThreadPriority
    ThreadState: ThreadState
    CurrentCulture: Any
    CurrentUICulture: Any
    CurrentPrincipal: ClassVar[Any]
    CurrentThread: ClassVar[Thread]
    ExecutionContext: ExecutionContext
    Name: str
    ApartmentState: ApartmentState
    @overload
    def __init__(self, start: Callable[..., None]) -> None: ...
    @overload
    def __init__(self, start: Callable[..., None], maxStackSize: int) -> None: ...
    @overload
    def __init__(self, start: Callable[..., None]) -> None: ...
    @overload
    def __init__(self, start: Callable[..., None], maxStackSize: int) -> None: ...
    @overload
    def Abort(self) -> None: ...
    @overload
    def Abort(self, stateInfo: Any) -> None: ...
    @staticmethod
    def AllocateDataSlot() -> Any: ...
    @staticmethod
    def AllocateNamedDataSlot(name: str) -> Any: ...
    @staticmethod
    def BeginCriticalRegion() -> None: ...
    @staticmethod
    def BeginThreadAffinity() -> None: ...
    def DisableComObjectEagerCleanup(self) -> None: ...
    @staticmethod
    def EndCriticalRegion() -> None: ...
    @staticmethod
    def EndThreadAffinity() -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def FreeNamedDataSlot(name: str) -> None: ...
    def GetApartmentState(self) -> ApartmentState: ...
    def GetCompressedStack(self) -> CompressedStack: ...
    @staticmethod
    def GetCurrentProcessorId() -> int: ...
    @staticmethod
    def GetData(slot: Any) -> Any: ...
    @staticmethod
    def GetDomain() -> Any: ...
    @staticmethod
    def GetDomainID() -> int: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetNamedDataSlot(name: str) -> Any: ...
    def GetType(self) -> Any: ...
    def Interrupt(self) -> None: ...
    @overload
    def Join(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def Join(self) -> None: ...
    @overload
    def Join(self, timeout: Any) -> bool: ...
    @staticmethod
    def MemoryBarrier() -> None: ...
    @staticmethod
    def ResetAbort() -> None: ...
    def Resume(self) -> None: ...
    def SetApartmentState(self, state: ApartmentState) -> None: ...
    def SetCompressedStack(self, stack: CompressedStack) -> None: ...
    @staticmethod
    def SetData(slot: Any, data: Any) -> None: ...
    @overload
    @staticmethod
    def Sleep(millisecondsTimeout: int) -> None: ...
    @overload
    @staticmethod
    def Sleep(timeout: Any) -> None: ...
    @staticmethod
    def SpinWait(iterations: int) -> None: ...
    @overload
    def Start(self, parameter: Any) -> None: ...
    @overload
    def Start(self) -> None: ...
    def Suspend(self) -> None: ...
    def ToString(self) -> str: ...
    def TrySetApartmentState(self, state: ApartmentState) -> bool: ...
    @overload
    def UnsafeStart(self, parameter: Any) -> None: ...
    @overload
    def UnsafeStart(self) -> None: ...
    @overload
    @staticmethod
    def VolatileRead(address: int) -> int: ...
    @overload
    @staticmethod
    def VolatileRead(address: float) -> float: ...
    @overload
    @staticmethod
    def VolatileRead(address: int) -> int: ...
    @overload
    @staticmethod
    def VolatileRead(address: int) -> int: ...
    @overload
    @staticmethod
    def VolatileRead(address: int) -> int: ...
    @overload
    @staticmethod
    def VolatileRead(address: Any) -> Any: ...
    @overload
    @staticmethod
    def VolatileRead(address: Any) -> Any: ...
    @overload
    @staticmethod
    def VolatileRead(address: int) -> int: ...
    @overload
    @staticmethod
    def VolatileRead(address: float) -> float: ...
    @overload
    @staticmethod
    def VolatileRead(address: int) -> int: ...
    @overload
    @staticmethod
    def VolatileRead(address: int) -> int: ...
    @overload
    @staticmethod
    def VolatileRead(address: int) -> int: ...
    @overload
    @staticmethod
    def VolatileRead(address: Any) -> Any: ...
    @overload
    @staticmethod
    def VolatileWrite(address: int, value: int) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: float, value: float) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: int, value: int) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: int, value: int) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: int, value: int) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: Any, value: Any) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: Any, value: Any) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: int, value: int) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: float, value: float) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: int, value: int) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: int, value: int) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: int, value: int) -> None: ...
    @overload
    @staticmethod
    def VolatileWrite(address: Any, value: Any) -> None: ...
    @staticmethod
    def Yield() -> bool: ...

class ThreadAbortException:
    ExceptionState: Any
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ThreadExceptionEventArgs:
    Exception: Any
    def __init__(self, t: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

ThreadExceptionEventHandler = Callable[..., None]

class ThreadInterruptedException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ThreadLocal(Generic[T]):
    Value: T
    Values: System.Collections.Generic.IList[T]
    IsValueCreated: bool
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, trackAllValues: bool) -> None: ...
    @overload
    def __init__(self, valueFactory: Callable[..., T]) -> None: ...
    @overload
    def __init__(self, valueFactory: Callable[..., T], trackAllValues: bool) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ThreadPool:
    PendingWorkItemCount: ClassVar[int]
    ThreadCount: ClassVar[int]
    CompletedWorkItemCount: ClassVar[int]
    @overload
    @staticmethod
    def BindHandle(osHandle: Any) -> bool: ...
    @overload
    @staticmethod
    def BindHandle(osHandle: Any) -> bool: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def GetAvailableThreads(workerThreads: int, completionPortThreads: int) -> None: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetMaxThreads(workerThreads: int, completionPortThreads: int) -> None: ...
    @staticmethod
    def GetMinThreads(workerThreads: int, completionPortThreads: int) -> None: ...
    def GetType(self) -> Any: ...
    @overload
    @staticmethod
    def QueueUserWorkItem(callBack: Callable[..., None]) -> bool: ...
    @overload
    @staticmethod
    def QueueUserWorkItem(callBack: Callable[..., None], state: Any) -> bool: ...
    @overload
    @staticmethod
    def QueueUserWorkItem(callBack: Callable[..., None], state: TState, preferLocal: bool) -> bool: ...
    @overload
    @staticmethod
    def RegisterWaitForSingleObject(waitObject: WaitHandle, callBack: Callable[..., None], state: Any, millisecondsTimeOutInterval: int, executeOnlyOnce: bool) -> RegisteredWaitHandle: ...
    @overload
    @staticmethod
    def RegisterWaitForSingleObject(waitObject: WaitHandle, callBack: Callable[..., None], state: Any, millisecondsTimeOutInterval: int, executeOnlyOnce: bool) -> RegisteredWaitHandle: ...
    @overload
    @staticmethod
    def RegisterWaitForSingleObject(waitObject: WaitHandle, callBack: Callable[..., None], state: Any, millisecondsTimeOutInterval: int, executeOnlyOnce: bool) -> RegisteredWaitHandle: ...
    @overload
    @staticmethod
    def RegisterWaitForSingleObject(waitObject: WaitHandle, callBack: Callable[..., None], state: Any, timeout: Any, executeOnlyOnce: bool) -> RegisteredWaitHandle: ...
    @staticmethod
    def SetMaxThreads(workerThreads: int, completionPortThreads: int) -> bool: ...
    @staticmethod
    def SetMinThreads(workerThreads: int, completionPortThreads: int) -> bool: ...
    def ToString(self) -> str: ...
    @staticmethod
    def UnsafeQueueNativeOverlapped(overlapped: Any) -> bool: ...
    @overload
    @staticmethod
    def UnsafeQueueUserWorkItem(callBack: Callable[..., None], state: TState, preferLocal: bool) -> bool: ...
    @overload
    @staticmethod
    def UnsafeQueueUserWorkItem(callBack: Callable[..., None], state: Any) -> bool: ...
    @overload
    @staticmethod
    def UnsafeQueueUserWorkItem(callBack: IThreadPoolWorkItem, preferLocal: bool) -> bool: ...
    @overload
    @staticmethod
    def UnsafeRegisterWaitForSingleObject(waitObject: WaitHandle, callBack: Callable[..., None], state: Any, millisecondsTimeOutInterval: int, executeOnlyOnce: bool) -> RegisteredWaitHandle: ...
    @overload
    @staticmethod
    def UnsafeRegisterWaitForSingleObject(waitObject: WaitHandle, callBack: Callable[..., None], state: Any, millisecondsTimeOutInterval: int, executeOnlyOnce: bool) -> RegisteredWaitHandle: ...
    @overload
    @staticmethod
    def UnsafeRegisterWaitForSingleObject(waitObject: WaitHandle, callBack: Callable[..., None], state: Any, millisecondsTimeOutInterval: int, executeOnlyOnce: bool) -> RegisteredWaitHandle: ...
    @overload
    @staticmethod
    def UnsafeRegisterWaitForSingleObject(waitObject: WaitHandle, callBack: Callable[..., None], state: Any, timeout: Any, executeOnlyOnce: bool) -> RegisteredWaitHandle: ...

class ThreadPoolBoundHandle:
    Handle: Any
    @overload
    def AllocateNativeOverlapped(self, callback: Callable[..., None], state: Any, pinData: Any) -> Any: ...
    @overload
    def AllocateNativeOverlapped(self, preAllocated: PreAllocatedOverlapped) -> Any: ...
    @staticmethod
    def BindHandle(handle: Any) -> ThreadPoolBoundHandle: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def FreeNativeOverlapped(self, overlapped: Any) -> None: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetNativeOverlappedState(overlapped: Any) -> Any: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
    def UnsafeAllocateNativeOverlapped(self, callback: Callable[..., None], state: Any, pinData: Any) -> Any: ...

class ThreadPriority(IntEnum):
    Lowest = 0
    BelowNormal = 1
    Normal = 2
    AboveNormal = 3
    Highest = 4

ThreadStart = Callable[..., None]

class ThreadStartException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ThreadState(IntFlag):
    Running = 0
    StopRequested = 1
    SuspendRequested = 2
    Background = 4
    Unstarted = 8
    Stopped = 16
    WaitSleepJoin = 32
    Suspended = 64
    AbortRequested = 128
    Aborted = 256

class ThreadStateException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class Timeout:
    InfiniteTimeSpan: ClassVar[Any]
    Infinite: ClassVar[int]
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class Timer:
    ActiveCount: ClassVar[int]
    @overload
    def __init__(self, callback: Callable[..., None], state: Any, dueTime: int, period: int) -> None: ...
    @overload
    def __init__(self, callback: Callable[..., None], state: Any, dueTime: Any, period: Any) -> None: ...
    @overload
    def __init__(self, callback: Callable[..., None], state: Any, dueTime: int, period: int) -> None: ...
    @overload
    def __init__(self, callback: Callable[..., None], state: Any, dueTime: int, period: int) -> None: ...
    @overload
    def __init__(self, callback: Callable[..., None]) -> None: ...
    @overload
    def Change(self, dueTime: int, period: int) -> bool: ...
    @overload
    def Change(self, dueTime: Any, period: Any) -> bool: ...
    @overload
    def Change(self, dueTime: int, period: int) -> bool: ...
    @overload
    def Change(self, dueTime: int, period: int) -> bool: ...
    @overload
    def Dispose(self, notifyObject: WaitHandle) -> bool: ...
    @overload
    def Dispose(self) -> None: ...
    def DisposeAsync(self) -> System.Threading.Tasks.ValueTask_: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    def ToString(self) -> str: ...

TimerCallback = Callable[..., None]

class Volatile:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    @overload
    @staticmethod
    def Read(location: bool) -> bool: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: float) -> float: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: Any) -> Any: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: float) -> float: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: int) -> int: ...
    @overload
    @staticmethod
    def Read(location: Any) -> Any: ...
    @overload
    @staticmethod
    def Read(location: T) -> T: ...
    @staticmethod
    def ReadBarrier() -> None: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def Write(location: bool, value: bool) -> None: ...
    @overload
    @staticmethod
    def Write(location: int, value: int) -> None: ...
    @overload
    @staticmethod
    def Write(location: float, value: float) -> None: ...
    @overload
    @staticmethod
    def Write(location: int, value: int) -> None: ...
    @overload
    @staticmethod
    def Write(location: int, value: int) -> None: ...
    @overload
    @staticmethod
    def Write(location: int, value: int) -> None: ...
    @overload
    @staticmethod
    def Write(location: Any, value: Any) -> None: ...
    @overload
    @staticmethod
    def Write(location: int, value: int) -> None: ...
    @overload
    @staticmethod
    def Write(location: float, value: float) -> None: ...
    @overload
    @staticmethod
    def Write(location: int, value: int) -> None: ...
    @overload
    @staticmethod
    def Write(location: int, value: int) -> None: ...
    @overload
    @staticmethod
    def Write(location: int, value: int) -> None: ...
    @overload
    @staticmethod
    def Write(location: Any, value: Any) -> None: ...
    @overload
    @staticmethod
    def Write(location: T, value: T) -> None: ...
    @staticmethod
    def WriteBarrier() -> None: ...

WaitCallback = Callable[..., None]

class WaitHandle:
    Handle: Any
    SafeWaitHandle: Any
    WaitTimeout: ClassVar[int]
    def Close(self) -> None: ...
    def Dispose(self) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    @overload
    @staticmethod
    def SignalAndWait(toSignal: WaitHandle, toWaitOn: WaitHandle) -> bool: ...
    @overload
    @staticmethod
    def SignalAndWait(toSignal: WaitHandle, toWaitOn: WaitHandle, timeout: Any, exitContext: bool) -> bool: ...
    @overload
    @staticmethod
    def SignalAndWait(toSignal: WaitHandle, toWaitOn: WaitHandle, millisecondsTimeout: int, exitContext: bool) -> bool: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def WaitAll(waitHandles: list[WaitHandle], millisecondsTimeout: int) -> bool: ...
    @overload
    @staticmethod
    def WaitAll(waitHandles: list[WaitHandle], timeout: Any) -> bool: ...
    @overload
    @staticmethod
    def WaitAll(waitHandles: list[WaitHandle]) -> bool: ...
    @overload
    @staticmethod
    def WaitAll(waitHandles: list[WaitHandle], millisecondsTimeout: int, exitContext: bool) -> bool: ...
    @overload
    @staticmethod
    def WaitAll(waitHandles: list[WaitHandle], timeout: Any, exitContext: bool) -> bool: ...
    @overload
    @staticmethod
    def WaitAny(waitHandles: list[WaitHandle], millisecondsTimeout: int) -> int: ...
    @overload
    @staticmethod
    def WaitAny(waitHandles: list[WaitHandle], timeout: Any) -> int: ...
    @overload
    @staticmethod
    def WaitAny(waitHandles: list[WaitHandle]) -> int: ...
    @overload
    @staticmethod
    def WaitAny(waitHandles: list[WaitHandle], millisecondsTimeout: int, exitContext: bool) -> int: ...
    @overload
    @staticmethod
    def WaitAny(waitHandles: list[WaitHandle], timeout: Any, exitContext: bool) -> int: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any) -> bool: ...
    @overload
    def WaitOne(self) -> bool: ...
    @overload
    def WaitOne(self, millisecondsTimeout: int, exitContext: bool) -> bool: ...
    @overload
    def WaitOne(self, timeout: Any, exitContext: bool) -> bool: ...

class WaitHandleCannotBeOpenedException:
    TargetSite: Any
    Message: str
    Data: Any
    InnerException: Any
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetBaseException(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @overload
    def GetType(self) -> Any: ...
    @overload
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class WaitHandleExtensions:
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetSafeWaitHandle(waitHandle: WaitHandle) -> Any: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def SetSafeWaitHandle(waitHandle: WaitHandle, value: Any) -> None: ...
    def ToString(self) -> str: ...

WaitOrTimerCallback = Callable[..., None]

from . import Tasks