from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload
import SharpDX
import System

class ComObjectEventArgs:
    Object: SharpDX.ComObject
    def __init__(self, o: SharpDX.ComObject) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ObjectReference:
    CreationTime: Any
    Object: Any
    StackTrace: str
    IsAlive: bool
    def __init__(self, creationTime: Any, comObject: SharpDX.ComObject, stackTrace: str) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class ObjectTracker:
    StackTraceProvider: ClassVar[Callable[..., str]]
    def Equals(self, obj: Any) -> bool: ...
    @overload
    @staticmethod
    def Find(comObjectPtr: Any) -> System.Collections.Generic.List[ObjectReference]: ...
    @overload
    @staticmethod
    def Find(comObject: SharpDX.ComObject) -> ObjectReference: ...
    @staticmethod
    def FindActiveObjects() -> System.Collections.Generic.List[ObjectReference]: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetStackTrace() -> str: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def ReportActiveObjects() -> str: ...
    def ToString(self) -> str: ...
    @staticmethod
    def Track(comObject: SharpDX.ComObject) -> None: ...
    @staticmethod
    def UnTrack(comObject: SharpDX.ComObject) -> None: ...
