from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, ClassVar, Generic, TypeVar, overload

T = TypeVar("T")
T1 = TypeVar("T1")
T2 = TypeVar("T2")
T3 = TypeVar("T3")
T4 = TypeVar("T4")

class NativeFile:
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def Exists(filePath: str) -> bool: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def GetLastWriteTime(path: str) -> Any: ...
    def GetType(self) -> Any: ...
    @staticmethod
    def ReadAllBytes(path: str) -> list[int]: ...
    @overload
    @staticmethod
    def ReadAllText(path: str) -> str: ...
    @overload
    @staticmethod
    def ReadAllText(path: str, encoding: Any, sharing: NativeFileShare = ...) -> str: ...
    def ToString(self) -> str: ...

class NativeFileAccess(IntFlag):
    All = 268435456
    Execute = 536870912
    Write = 1073741824
    Read = 2147483648
    ReadWrite = 3221225472

class NativeFileMode(IntEnum):
    CreateNew = 1
    Create = 2
    Open = 3
    OpenOrCreate = 4
    Truncate = 5

class NativeFileOptions(IntFlag):
    None_ = 0
    Readonly = 1
    Hidden = 2
    System = 4
    Directory = 16
    Archive = 32
    Device = 64
    Normal = 128
    Temporary = 256
    SparseFile = 512
    ReparsePoint = 1024
    Compressed = 2048
    Offline = 4096
    NotContentIndexed = 8192
    Encrypted = 16384
    FirstPipeInstance = 524288
    OpenNoRecall = 1048576
    OpenReparsePoint = 2097152
    PosixSemantics = 16777216
    BackupSemantics = 33554432
    DeleteOnClose = 67108864
    SequentialScan = 134217728
    RandomAccess = 268435456
    NoBuffering = 536870912
    Overlapped = 1073741824
    Write_Through = 2147483648

class NativeFileShare(IntFlag):
    None_ = 0
    Read = 1
    Write = 2
    ReadWrite = 3
    Delete = 4

class NativeFileStream:
    Handle: Any
    CanRead: bool
    CanSeek: bool
    CanWrite: bool
    Length: int
    Position: int
    CanTimeout: bool
    ReadTimeout: int
    WriteTimeout: int
    def __init__(self, fileName: str, fileMode: NativeFileMode, access: NativeFileAccess, share: NativeFileShare = ...) -> None: ...
    def BeginRead(self, buffer: list[int], offset: int, count: int, callback: Any, state: Any) -> Any: ...
    def BeginWrite(self, buffer: list[int], offset: int, count: int, callback: Any, state: Any) -> Any: ...
    def Close(self) -> None: ...
    @overload
    def CopyTo(self, destination: Any) -> None: ...
    @overload
    def CopyTo(self, destination: Any, bufferSize: int) -> None: ...
    @overload
    def CopyToAsync(self, destination: Any) -> Any: ...
    @overload
    def CopyToAsync(self, destination: Any, bufferSize: int) -> Any: ...
    @overload
    def CopyToAsync(self, destination: Any, cancellationToken: Any) -> Any: ...
    @overload
    def CopyToAsync(self, destination: Any, bufferSize: int, cancellationToken: Any) -> Any: ...
    def Dispose(self) -> None: ...
    def DisposeAsync(self) -> Any: ...
    def EndRead(self, asyncResult: Any) -> int: ...
    def EndWrite(self, asyncResult: Any) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def Flush(self) -> None: ...
    @overload
    def FlushAsync(self) -> Any: ...
    @overload
    def FlushAsync(self, cancellationToken: Any) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> Any: ...
    def GetType(self) -> Any: ...
    def InitializeLifetimeService(self) -> Any: ...
    @overload
    def Read(self, buffer: list[int], offset: int, count: int) -> int: ...
    @overload
    def Read(self, buffer: Any, offset: int, count: int) -> int: ...
    @overload
    def Read(self, buffer: Any) -> int: ...
    @overload
    def ReadAsync(self, buffer: list[int], offset: int, count: int) -> Any: ...
    @overload
    def ReadAsync(self, buffer: list[int], offset: int, count: int, cancellationToken: Any) -> Any: ...
    @overload
    def ReadAsync(self, buffer: Any, cancellationToken: Any = ...) -> Any: ...
    def ReadAtLeast(self, buffer: Any, minimumBytes: int, throwOnEndOfStream: bool = ...) -> int: ...
    def ReadAtLeastAsync(self, buffer: Any, minimumBytes: int, throwOnEndOfStream: bool = ..., cancellationToken: Any = ...) -> Any: ...
    def ReadByte(self) -> int: ...
    @overload
    def ReadExactly(self, buffer: Any) -> None: ...
    @overload
    def ReadExactly(self, buffer: list[int], offset: int, count: int) -> None: ...
    @overload
    def ReadExactlyAsync(self, buffer: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    def ReadExactlyAsync(self, buffer: list[int], offset: int, count: int, cancellationToken: Any = ...) -> Any: ...
    def Seek(self, offset: int, origin: Any) -> int: ...
    def SetLength(self, value: int) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Write(self, buffer: list[int], offset: int, count: int) -> None: ...
    @overload
    def Write(self, buffer: Any, offset: int, count: int) -> None: ...
    @overload
    def Write(self, buffer: Any) -> None: ...
    @overload
    def WriteAsync(self, buffer: list[int], offset: int, count: int) -> Any: ...
    @overload
    def WriteAsync(self, buffer: list[int], offset: int, count: int, cancellationToken: Any) -> Any: ...
    @overload
    def WriteAsync(self, buffer: Any, cancellationToken: Any = ...) -> Any: ...
    def WriteByte(self, value: int) -> None: ...
