from __future__ import annotations
from typing import Any, ClassVar, overload


class ASCIIEncoding:
    Preamble: Any
    BodyName: str
    EncodingName: str
    HeaderName: str
    WebName: str
    WindowsCodePage: int
    IsBrowserDisplay: bool
    IsBrowserSave: bool
    IsMailNewsDisplay: bool
    IsMailNewsSave: bool
    IsSingleByte: bool
    EncoderFallback: Any
    DecoderFallback: Any
    IsReadOnly: bool
    CodePage: int
    def __init__(self) -> None: ...
    def Clone(self) -> Any: ...
    def Equals(self, value: Any) -> bool: ...
    @overload
    def GetByteCount(self, chars: list[Any], index: int, count: int) -> int: ...
    @overload
    def GetByteCount(self, chars: list[Any]) -> int: ...
    @overload
    def GetByteCount(self, s: str) -> int: ...
    @overload
    def GetByteCount(self, s: str, index: int, count: int) -> int: ...
    @overload
    def GetByteCount(self, chars: Any, count: int) -> int: ...
    @overload
    def GetByteCount(self, chars: Any) -> int: ...
    @overload
    def GetBytes(self, chars: list[Any], charIndex: int, charCount: int, bytes: list[int], byteIndex: int) -> int: ...
    @overload
    def GetBytes(self, chars: list[Any]) -> list[int]: ...
    @overload
    def GetBytes(self, chars: list[Any], index: int, count: int) -> list[int]: ...
    @overload
    def GetBytes(self, s: str) -> list[int]: ...
    @overload
    def GetBytes(self, s: str, index: int, count: int) -> list[int]: ...
    @overload
    def GetBytes(self, s: str, charIndex: int, charCount: int, bytes: list[int], byteIndex: int) -> int: ...
    @overload
    def GetBytes(self, chars: Any, charCount: int, bytes: Any, byteCount: int) -> int: ...
    @overload
    def GetBytes(self, chars: Any, bytes: Any) -> int: ...
    @overload
    def GetCharCount(self, bytes: list[int], index: int, count: int) -> int: ...
    @overload
    def GetCharCount(self, bytes: list[int]) -> int: ...
    @overload
    def GetCharCount(self, bytes: Any, count: int) -> int: ...
    @overload
    def GetCharCount(self, bytes: Any) -> int: ...
    @overload
    def GetChars(self, bytes: list[int], byteIndex: int, byteCount: int, chars: list[Any], charIndex: int) -> int: ...
    @overload
    def GetChars(self, bytes: list[int]) -> list[Any]: ...
    @overload
    def GetChars(self, bytes: list[int], index: int, count: int) -> list[Any]: ...
    @overload
    def GetChars(self, bytes: Any, byteCount: int, chars: Any, charCount: int) -> int: ...
    @overload
    def GetChars(self, bytes: Any, chars: Any) -> int: ...
    def GetDecoder(self) -> Any: ...
    def GetEncoder(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetMaxByteCount(self, charCount: int) -> int: ...
    def GetMaxCharCount(self, byteCount: int) -> int: ...
    def GetPreamble(self) -> list[int]: ...
    @overload
    def GetString(self, bytes: list[int]) -> str: ...
    @overload
    def GetString(self, bytes: Any, byteCount: int) -> str: ...
    @overload
    def GetString(self, bytes: Any) -> str: ...
    @overload
    def GetString(self, bytes: list[int]) -> str: ...
    @overload
    def GetString(self, bytes: list[int], index: int, count: int) -> str: ...
    def GetType(self) -> Any: ...
    @overload
    def IsAlwaysNormalized(self) -> bool: ...
    @overload
    def IsAlwaysNormalized(self, form: Any) -> bool: ...
    def ToString(self) -> str: ...
    def TryGetBytes(self, chars: Any, bytes: Any, bytesWritten: int) -> bool: ...
    def TryGetChars(self, bytes: Any, chars: Any, charsWritten: int) -> bool: ...

class Encoding:
    Preamble: Any
    BodyName: str
    EncodingName: str
    HeaderName: str
    WebName: str
    WindowsCodePage: int
    IsBrowserDisplay: bool
    IsBrowserSave: bool
    IsMailNewsDisplay: bool
    IsMailNewsSave: bool
    IsSingleByte: bool
    EncoderFallback: Any
    DecoderFallback: Any
    IsReadOnly: bool
    CodePage: int
    ASCII: ClassVar[Any]
    def Clone(self) -> Any: ...
    def Equals(self, value: Any) -> bool: ...
    @overload
    def GetByteCount(self, chars: list[Any]) -> int: ...
    @overload
    def GetByteCount(self, s: str) -> int: ...
    @overload
    def GetByteCount(self, chars: list[Any], index: int, count: int) -> int: ...
    @overload
    def GetByteCount(self, s: str, index: int, count: int) -> int: ...
    @overload
    def GetByteCount(self, chars: Any, count: int) -> int: ...
    @overload
    def GetByteCount(self, chars: Any) -> int: ...
    @overload
    def GetBytes(self, chars: list[Any]) -> list[int]: ...
    @overload
    def GetBytes(self, chars: list[Any], index: int, count: int) -> list[int]: ...
    @overload
    def GetBytes(self, chars: list[Any], charIndex: int, charCount: int, bytes: list[int], byteIndex: int) -> int: ...
    @overload
    def GetBytes(self, s: str) -> list[int]: ...
    @overload
    def GetBytes(self, s: str, index: int, count: int) -> list[int]: ...
    @overload
    def GetBytes(self, s: str, charIndex: int, charCount: int, bytes: list[int], byteIndex: int) -> int: ...
    @overload
    def GetBytes(self, chars: Any, charCount: int, bytes: Any, byteCount: int) -> int: ...
    @overload
    def GetBytes(self, chars: Any, bytes: Any) -> int: ...
    @overload
    def GetCharCount(self, bytes: list[int]) -> int: ...
    @overload
    def GetCharCount(self, bytes: list[int], index: int, count: int) -> int: ...
    @overload
    def GetCharCount(self, bytes: Any, count: int) -> int: ...
    @overload
    def GetCharCount(self, bytes: Any) -> int: ...
    @overload
    def GetChars(self, bytes: list[int]) -> list[Any]: ...
    @overload
    def GetChars(self, bytes: list[int], index: int, count: int) -> list[Any]: ...
    @overload
    def GetChars(self, bytes: list[int], byteIndex: int, byteCount: int, chars: list[Any], charIndex: int) -> int: ...
    @overload
    def GetChars(self, bytes: Any, byteCount: int, chars: Any, charCount: int) -> int: ...
    @overload
    def GetChars(self, bytes: Any, chars: Any) -> int: ...
    def GetDecoder(self) -> Any: ...
    def GetEncoder(self) -> Any: ...
    def GetHashCode(self) -> int: ...
    def GetMaxByteCount(self, charCount: int) -> int: ...
    def GetMaxCharCount(self, byteCount: int) -> int: ...
    def GetPreamble(self) -> list[int]: ...
    @overload
    def GetString(self, bytes: Any, byteCount: int) -> str: ...
    @overload
    def GetString(self, bytes: Any) -> str: ...
    @overload
    def GetString(self, bytes: list[int]) -> str: ...
    @overload
    def GetString(self, bytes: list[int], index: int, count: int) -> str: ...
    def GetType(self) -> Any: ...
    @overload
    def IsAlwaysNormalized(self) -> bool: ...
    @overload
    def IsAlwaysNormalized(self, form: Any) -> bool: ...
    def ToString(self) -> str: ...
    def TryGetBytes(self, chars: Any, bytes: Any, bytesWritten: int) -> bool: ...
    def TryGetChars(self, bytes: Any, chars: Any, charsWritten: int) -> bool: ...
