from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload

T = TypeVar("T")
TArg0 = TypeVar("TArg0")
TArg1 = TypeVar("TArg1")
TArg2 = TypeVar("TArg2")
TEnum = TypeVar("TEnum")
TOther = TypeVar("TOther")
TState = TypeVar("TState")

Action = Callable[..., None]

class Enum:
    def CompareTo(self, target: Any) -> int: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def Format(enumType: Any, value: Any, format: str) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetName(value: TEnum) -> str: ...
    @overload
    @staticmethod
    def GetName(enumType: Any, value: Any) -> str: ...
    @overload
    @staticmethod
    def GetNames() -> list[str]: ...
    @overload
    @staticmethod
    def GetNames(enumType: Any) -> list[str]: ...
    def GetType(self) -> Any: ...
    def GetTypeCode(self) -> Any: ...
    @staticmethod
    def GetUnderlyingType(enumType: Any) -> Any: ...
    @overload
    @staticmethod
    def GetValues() -> list[TEnum]: ...
    @overload
    @staticmethod
    def GetValues(enumType: Any) -> Any: ...
    @overload
    @staticmethod
    def GetValuesAsUnderlyingType() -> Any: ...
    @overload
    @staticmethod
    def GetValuesAsUnderlyingType(enumType: Any) -> Any: ...
    def HasFlag(self, flag: Enum) -> bool: ...
    @overload
    @staticmethod
    def IsDefined(value: TEnum) -> bool: ...
    @overload
    @staticmethod
    def IsDefined(enumType: Any, value: Any) -> bool: ...
    @overload
    @staticmethod
    def Parse(enumType: Any, value: str) -> Any: ...
    @overload
    @staticmethod
    def Parse(enumType: Any, value: Any) -> Any: ...
    @overload
    @staticmethod
    def Parse(enumType: Any, value: str, ignoreCase: bool) -> Any: ...
    @overload
    @staticmethod
    def Parse(enumType: Any, value: Any, ignoreCase: bool) -> Any: ...
    @overload
    @staticmethod
    def Parse(value: str) -> TEnum: ...
    @overload
    @staticmethod
    def Parse(value: Any) -> TEnum: ...
    @overload
    @staticmethod
    def Parse(value: str, ignoreCase: bool) -> TEnum: ...
    @overload
    @staticmethod
    def Parse(value: Any, ignoreCase: bool) -> TEnum: ...
    @overload
    @staticmethod
    def ToObject(enumType: Any, value: Any) -> Any: ...
    @overload
    @staticmethod
    def ToObject(enumType: Any, value: int) -> Any: ...
    @overload
    @staticmethod
    def ToObject(enumType: Any, value: int) -> Any: ...
    @overload
    @staticmethod
    def ToObject(enumType: Any, value: int) -> Any: ...
    @overload
    @staticmethod
    def ToObject(enumType: Any, value: int) -> Any: ...
    @overload
    @staticmethod
    def ToObject(enumType: Any, value: int) -> Any: ...
    @overload
    @staticmethod
    def ToObject(enumType: Any, value: int) -> Any: ...
    @overload
    @staticmethod
    def ToObject(enumType: Any, value: int) -> Any: ...
    @overload
    @staticmethod
    def ToObject(enumType: Any, value: int) -> Any: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def ToString(self, format: str) -> str: ...
    @overload
    def ToString(self, provider: Any) -> str: ...
    @overload
    def ToString(self, format: str, provider: Any) -> str: ...
    @staticmethod
    def TryFormat(value: TEnum, destination: Any, charsWritten: int, format: Any = ...) -> bool: ...
    @overload
    @staticmethod
    def TryParse(enumType: Any, value: str, result: Any) -> bool: ...
    @overload
    @staticmethod
    def TryParse(enumType: Any, value: Any, result: Any) -> bool: ...
    @overload
    @staticmethod
    def TryParse(enumType: Any, value: str, ignoreCase: bool, result: Any) -> bool: ...
    @overload
    @staticmethod
    def TryParse(enumType: Any, value: Any, ignoreCase: bool, result: Any) -> bool: ...
    @overload
    @staticmethod
    def TryParse(value: str, result: TEnum) -> bool: ...
    @overload
    @staticmethod
    def TryParse(value: Any, result: TEnum) -> bool: ...
    @overload
    @staticmethod
    def TryParse(value: str, ignoreCase: bool, result: TEnum) -> bool: ...
    @overload
    @staticmethod
    def TryParse(value: Any, ignoreCase: bool, result: TEnum) -> bool: ...

class String:
    Length: int
    Empty: ClassVar[str]
    @overload
    def __init__(self, value: list[Any]) -> None: ...
    @overload
    def __init__(self, value: list[Any], startIndex: int, length: int) -> None: ...
    @overload
    def __init__(self, value: Any) -> None: ...
    @overload
    def __init__(self, value: Any, startIndex: int, length: int) -> None: ...
    @overload
    def __init__(self, value: Any) -> None: ...
    @overload
    def __init__(self, value: Any, startIndex: int, length: int) -> None: ...
    @overload
    def __init__(self, value: Any, startIndex: int, length: int, enc: Any) -> None: ...
    @overload
    def __init__(self, c: Any, count: int) -> None: ...
    @overload
    def __init__(self, value: Any) -> None: ...
    def Clone(self) -> Any: ...
    @overload
    @staticmethod
    def Compare(strA: str, strB: str) -> int: ...
    @overload
    @staticmethod
    def Compare(strA: str, strB: str, ignoreCase: bool) -> int: ...
    @overload
    @staticmethod
    def Compare(strA: str, strB: str, comparisonType: Any) -> int: ...
    @overload
    @staticmethod
    def Compare(strA: str, strB: str, culture: Any, options: Any) -> int: ...
    @overload
    @staticmethod
    def Compare(strA: str, strB: str, ignoreCase: bool, culture: Any) -> int: ...
    @overload
    @staticmethod
    def Compare(strA: str, indexA: int, strB: str, indexB: int, length: int) -> int: ...
    @overload
    @staticmethod
    def Compare(strA: str, indexA: int, strB: str, indexB: int, length: int, ignoreCase: bool) -> int: ...
    @overload
    @staticmethod
    def Compare(strA: str, indexA: int, strB: str, indexB: int, length: int, ignoreCase: bool, culture: Any) -> int: ...
    @overload
    @staticmethod
    def Compare(strA: str, indexA: int, strB: str, indexB: int, length: int, culture: Any, options: Any) -> int: ...
    @overload
    @staticmethod
    def Compare(strA: str, indexA: int, strB: str, indexB: int, length: int, comparisonType: Any) -> int: ...
    @overload
    @staticmethod
    def CompareOrdinal(strA: str, strB: str) -> int: ...
    @overload
    @staticmethod
    def CompareOrdinal(strA: str, indexA: int, strB: str, indexB: int, length: int) -> int: ...
    @overload
    def CompareTo(self, value: Any) -> int: ...
    @overload
    def CompareTo(self, strB: str) -> int: ...
    @overload
    @staticmethod
    def Concat(arg0: Any) -> str: ...
    @overload
    @staticmethod
    def Concat(arg0: Any, arg1: Any) -> str: ...
    @overload
    @staticmethod
    def Concat(arg0: Any, arg1: Any, arg2: Any) -> str: ...
    @overload
    @staticmethod
    def Concat(args: list[Any]) -> str: ...
    @overload
    @staticmethod
    def Concat(args: Any) -> str: ...
    @overload
    @staticmethod
    def Concat(values: Any) -> str: ...
    @overload
    @staticmethod
    def Concat(values: Any) -> str: ...
    @overload
    @staticmethod
    def Concat(str0: str, str1: str) -> str: ...
    @overload
    @staticmethod
    def Concat(str0: str, str1: str, str2: str) -> str: ...
    @overload
    @staticmethod
    def Concat(str0: str, str1: str, str2: str, str3: str) -> str: ...
    @overload
    @staticmethod
    def Concat(str0: Any, str1: Any) -> str: ...
    @overload
    @staticmethod
    def Concat(str0: Any, str1: Any, str2: Any) -> str: ...
    @overload
    @staticmethod
    def Concat(str0: Any, str1: Any, str2: Any, str3: Any) -> str: ...
    @overload
    @staticmethod
    def Concat(values: list[str]) -> str: ...
    @overload
    @staticmethod
    def Concat(values: Any) -> str: ...
    @overload
    def Contains(self, value: str) -> bool: ...
    @overload
    def Contains(self, value: str, comparisonType: Any) -> bool: ...
    @overload
    def Contains(self, value: Any) -> bool: ...
    @overload
    def Contains(self, value: Any, comparisonType: Any) -> bool: ...
    @staticmethod
    def Copy(str: str) -> str: ...
    @overload
    def CopyTo(self, sourceIndex: int, destination: list[Any], destinationIndex: int, count: int) -> None: ...
    @overload
    def CopyTo(self, destination: Any) -> None: ...
    @overload
    @staticmethod
    def Create(length: int, state: TState, action: Callable[..., None]) -> str: ...
    @overload
    @staticmethod
    def Create(provider: Any, handler: Any) -> str: ...
    @overload
    @staticmethod
    def Create(provider: Any, initialBuffer: Any, handler: Any) -> str: ...
    @overload
    def EndsWith(self, value: str) -> bool: ...
    @overload
    def EndsWith(self, value: str, comparisonType: Any) -> bool: ...
    @overload
    def EndsWith(self, value: str, ignoreCase: bool, culture: Any) -> bool: ...
    @overload
    def EndsWith(self, value: Any) -> bool: ...
    def EnumerateRunes(self) -> Any: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def Equals(self, value: str) -> bool: ...
    @overload
    def Equals(self, value: str, comparisonType: Any) -> bool: ...
    @overload
    @staticmethod
    def Equals(a: str, b: str) -> bool: ...
    @overload
    @staticmethod
    def Equals(a: str, b: str, comparisonType: Any) -> bool: ...
    @overload
    @staticmethod
    def Format(format: str, arg0: Any) -> str: ...
    @overload
    @staticmethod
    def Format(format: str, arg0: Any, arg1: Any) -> str: ...
    @overload
    @staticmethod
    def Format(format: str, arg0: Any, arg1: Any, arg2: Any) -> str: ...
    @overload
    @staticmethod
    def Format(format: str, args: list[Any]) -> str: ...
    @overload
    @staticmethod
    def Format(format: str, args: Any) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: str, arg0: Any) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: str, arg0: Any, arg1: Any) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: str, arg0: Any, arg1: Any, arg2: Any) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: str, args: list[Any]) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: str, args: Any) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: Any, arg0: TArg0) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: Any, arg0: TArg0, arg1: TArg1) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: Any, arg0: TArg0, arg1: TArg1, arg2: TArg2) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: Any, args: list[Any]) -> str: ...
    @overload
    @staticmethod
    def Format(provider: Any, format: Any, args: Any) -> str: ...
    def GetEnumerator(self) -> Any: ...
    @overload
    def GetHashCode(self) -> int: ...
    @overload
    def GetHashCode(self, comparisonType: Any) -> int: ...
    @overload
    @staticmethod
    def GetHashCode(value: Any) -> int: ...
    @overload
    @staticmethod
    def GetHashCode(value: Any, comparisonType: Any) -> int: ...
    def GetPinnableReference(self) -> Any: ...
    def GetType(self) -> Any: ...
    def GetTypeCode(self) -> Any: ...
    @overload
    def IndexOf(self, value: Any) -> int: ...
    @overload
    def IndexOf(self, value: Any, startIndex: int) -> int: ...
    @overload
    def IndexOf(self, value: Any, comparisonType: Any) -> int: ...
    @overload
    def IndexOf(self, value: Any, startIndex: int, count: int) -> int: ...
    @overload
    def IndexOf(self, value: str) -> int: ...
    @overload
    def IndexOf(self, value: str, startIndex: int) -> int: ...
    @overload
    def IndexOf(self, value: str, startIndex: int, count: int) -> int: ...
    @overload
    def IndexOf(self, value: str, comparisonType: Any) -> int: ...
    @overload
    def IndexOf(self, value: str, startIndex: int, comparisonType: Any) -> int: ...
    @overload
    def IndexOf(self, value: str, startIndex: int, count: int, comparisonType: Any) -> int: ...
    @overload
    def IndexOfAny(self, anyOf: list[Any]) -> int: ...
    @overload
    def IndexOfAny(self, anyOf: list[Any], startIndex: int) -> int: ...
    @overload
    def IndexOfAny(self, anyOf: list[Any], startIndex: int, count: int) -> int: ...
    def Insert(self, startIndex: int, value: str) -> str: ...
    @staticmethod
    def Intern(str: str) -> str: ...
    @staticmethod
    def IsInterned(str: str) -> str: ...
    @overload
    def IsNormalized(self) -> bool: ...
    @overload
    def IsNormalized(self, normalizationForm: Any) -> bool: ...
    @staticmethod
    def IsNullOrEmpty(value: str) -> bool: ...
    @staticmethod
    def IsNullOrWhiteSpace(value: str) -> bool: ...
    @overload
    @staticmethod
    def Join(separator: Any, value: list[str]) -> str: ...
    @overload
    @staticmethod
    def Join(separator: Any, value: Any) -> str: ...
    @overload
    @staticmethod
    def Join(separator: str, value: list[str]) -> str: ...
    @overload
    @staticmethod
    def Join(separator: str, value: Any) -> str: ...
    @overload
    @staticmethod
    def Join(separator: Any, value: list[str], startIndex: int, count: int) -> str: ...
    @overload
    @staticmethod
    def Join(separator: str, value: list[str], startIndex: int, count: int) -> str: ...
    @overload
    @staticmethod
    def Join(separator: str, values: Any) -> str: ...
    @overload
    @staticmethod
    def Join(separator: Any, values: list[Any]) -> str: ...
    @overload
    @staticmethod
    def Join(separator: Any, values: Any) -> str: ...
    @overload
    @staticmethod
    def Join(separator: str, values: list[Any]) -> str: ...
    @overload
    @staticmethod
    def Join(separator: str, values: Any) -> str: ...
    @overload
    @staticmethod
    def Join(separator: Any, values: Any) -> str: ...
    @overload
    @staticmethod
    def Join(separator: str, values: Any) -> str: ...
    @overload
    def LastIndexOf(self, value: Any) -> int: ...
    @overload
    def LastIndexOf(self, value: Any, startIndex: int) -> int: ...
    @overload
    def LastIndexOf(self, value: Any, startIndex: int, count: int) -> int: ...
    @overload
    def LastIndexOf(self, value: str) -> int: ...
    @overload
    def LastIndexOf(self, value: str, startIndex: int) -> int: ...
    @overload
    def LastIndexOf(self, value: str, startIndex: int, count: int) -> int: ...
    @overload
    def LastIndexOf(self, value: str, comparisonType: Any) -> int: ...
    @overload
    def LastIndexOf(self, value: str, startIndex: int, comparisonType: Any) -> int: ...
    @overload
    def LastIndexOf(self, value: str, startIndex: int, count: int, comparisonType: Any) -> int: ...
    @overload
    def LastIndexOfAny(self, anyOf: list[Any]) -> int: ...
    @overload
    def LastIndexOfAny(self, anyOf: list[Any], startIndex: int) -> int: ...
    @overload
    def LastIndexOfAny(self, anyOf: list[Any], startIndex: int, count: int) -> int: ...
    @overload
    def Normalize(self) -> str: ...
    @overload
    def Normalize(self, normalizationForm: Any) -> str: ...
    @overload
    def PadLeft(self, totalWidth: int) -> str: ...
    @overload
    def PadLeft(self, totalWidth: int, paddingChar: Any) -> str: ...
    @overload
    def PadRight(self, totalWidth: int) -> str: ...
    @overload
    def PadRight(self, totalWidth: int, paddingChar: Any) -> str: ...
    @overload
    def Remove(self, startIndex: int, count: int) -> str: ...
    @overload
    def Remove(self, startIndex: int) -> str: ...
    @overload
    def Replace(self, oldValue: str, newValue: str, ignoreCase: bool, culture: Any) -> str: ...
    @overload
    def Replace(self, oldValue: str, newValue: str, comparisonType: Any) -> str: ...
    @overload
    def Replace(self, oldChar: Any, newChar: Any) -> str: ...
    @overload
    def Replace(self, oldValue: str, newValue: str) -> str: ...
    @overload
    def ReplaceLineEndings(self) -> str: ...
    @overload
    def ReplaceLineEndings(self, replacementText: str) -> str: ...
    @overload
    def Split(self, separator: Any, options: Any = ...) -> list[str]: ...
    @overload
    def Split(self, separator: Any, count: int, options: Any = ...) -> list[str]: ...
    @overload
    def Split(self, separator: list[Any]) -> list[str]: ...
    @overload
    def Split(self, separator: Any) -> list[str]: ...
    @overload
    def Split(self, separator: list[Any], count: int) -> list[str]: ...
    @overload
    def Split(self, separator: list[Any], options: Any) -> list[str]: ...
    @overload
    def Split(self, separator: list[Any], count: int, options: Any) -> list[str]: ...
    @overload
    def Split(self, separator: str, options: Any = ...) -> list[str]: ...
    @overload
    def Split(self, separator: str, count: int, options: Any = ...) -> list[str]: ...
    @overload
    def Split(self, separator: list[str], options: Any) -> list[str]: ...
    @overload
    def Split(self, separator: list[str], count: int, options: Any) -> list[str]: ...
    @overload
    def StartsWith(self, value: str) -> bool: ...
    @overload
    def StartsWith(self, value: str, comparisonType: Any) -> bool: ...
    @overload
    def StartsWith(self, value: str, ignoreCase: bool, culture: Any) -> bool: ...
    @overload
    def StartsWith(self, value: Any) -> bool: ...
    @overload
    def Substring(self, startIndex: int) -> str: ...
    @overload
    def Substring(self, startIndex: int, length: int) -> str: ...
    @overload
    def ToCharArray(self) -> list[Any]: ...
    @overload
    def ToCharArray(self, startIndex: int, length: int) -> list[Any]: ...
    @overload
    def ToLower(self) -> str: ...
    @overload
    def ToLower(self, culture: Any) -> str: ...
    def ToLowerInvariant(self) -> str: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def ToString(self, provider: Any) -> str: ...
    @overload
    def ToUpper(self) -> str: ...
    @overload
    def ToUpper(self, culture: Any) -> str: ...
    def ToUpperInvariant(self) -> str: ...
    @overload
    def Trim(self) -> str: ...
    @overload
    def Trim(self, trimChar: Any) -> str: ...
    @overload
    def Trim(self, trimChars: list[Any]) -> str: ...
    @overload
    def Trim(self, trimChars: Any) -> str: ...
    @overload
    def TrimEnd(self) -> str: ...
    @overload
    def TrimEnd(self, trimChar: Any) -> str: ...
    @overload
    def TrimEnd(self, trimChars: list[Any]) -> str: ...
    @overload
    def TrimEnd(self, trimChars: Any) -> str: ...
    @overload
    def TrimStart(self) -> str: ...
    @overload
    def TrimStart(self, trimChar: Any) -> str: ...
    @overload
    def TrimStart(self, trimChars: list[Any]) -> str: ...
    @overload
    def TrimStart(self, trimChars: Any) -> str: ...
    def TryCopyTo(self, destination: Any) -> bool: ...

class UInt32:
    MaxValue: ClassVar[int]
    MinValue: ClassVar[int]
    @staticmethod
    def BigMul(left: int, right: int) -> int: ...
    @staticmethod
    def Clamp(value: int, min: int, max: int) -> int: ...
    @overload
    def CompareTo(self, value: Any) -> int: ...
    @overload
    def CompareTo(self, value: int) -> int: ...
    @staticmethod
    def CreateChecked(value: TOther) -> int: ...
    @staticmethod
    def CreateSaturating(value: TOther) -> int: ...
    @staticmethod
    def CreateTruncating(value: TOther) -> int: ...
    @staticmethod
    def DivRem(left: int, right: int) -> Any: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    @overload
    def Equals(self, obj: int) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def GetTypeCode(self) -> Any: ...
    @staticmethod
    def IsEvenInteger(value: int) -> bool: ...
    @staticmethod
    def IsOddInteger(value: int) -> bool: ...
    @staticmethod
    def IsPow2(value: int) -> bool: ...
    @staticmethod
    def LeadingZeroCount(value: int) -> int: ...
    @staticmethod
    def Log2(value: int) -> int: ...
    @staticmethod
    def Max(x: int, y: int) -> int: ...
    @staticmethod
    def Min(x: int, y: int) -> int: ...
    @overload
    @staticmethod
    def Parse(s: str) -> int: ...
    @overload
    @staticmethod
    def Parse(s: str, style: Any) -> int: ...
    @overload
    @staticmethod
    def Parse(s: str, provider: Any) -> int: ...
    @overload
    @staticmethod
    def Parse(s: str, style: Any, provider: Any) -> int: ...
    @overload
    @staticmethod
    def Parse(s: Any, style: Any = ..., provider: Any = ...) -> int: ...
    @overload
    @staticmethod
    def Parse(s: Any, provider: Any) -> int: ...
    @overload
    @staticmethod
    def Parse(utf8Text: Any, style: Any = ..., provider: Any = ...) -> int: ...
    @overload
    @staticmethod
    def Parse(utf8Text: Any, provider: Any) -> int: ...
    @staticmethod
    def PopCount(value: int) -> int: ...
    @staticmethod
    def RotateLeft(value: int, rotateAmount: int) -> int: ...
    @staticmethod
    def RotateRight(value: int, rotateAmount: int) -> int: ...
    @staticmethod
    def Sign(value: int) -> int: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def ToString(self, provider: Any) -> str: ...
    @overload
    def ToString(self, format: str) -> str: ...
    @overload
    def ToString(self, format: str, provider: Any) -> str: ...
    @staticmethod
    def TrailingZeroCount(value: int) -> int: ...
    @overload
    def TryFormat(self, destination: Any, charsWritten: int, format: Any = ..., provider: Any = ...) -> bool: ...
    @overload
    def TryFormat(self, utf8Destination: Any, bytesWritten: int, format: Any = ..., provider: Any = ...) -> bool: ...
    @overload
    @staticmethod
    def TryParse(s: str, result: int) -> bool: ...
    @overload
    @staticmethod
    def TryParse(s: Any, result: int) -> bool: ...
    @overload
    @staticmethod
    def TryParse(utf8Text: Any, result: int) -> bool: ...
    @overload
    @staticmethod
    def TryParse(s: str, style: Any, provider: Any, result: int) -> bool: ...
    @overload
    @staticmethod
    def TryParse(s: Any, style: Any, provider: Any, result: int) -> bool: ...
    @overload
    @staticmethod
    def TryParse(s: str, provider: Any, result: int) -> bool: ...
    @overload
    @staticmethod
    def TryParse(s: Any, provider: Any, result: int) -> bool: ...
    @overload
    @staticmethod
    def TryParse(utf8Text: Any, style: Any, provider: Any, result: int) -> bool: ...
    @overload
    @staticmethod
    def TryParse(utf8Text: Any, provider: Any, result: int) -> bool: ...

from . import IO