from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, Callable, ClassVar, Generic, TypeVar, overload

class File:
    @overload
    @staticmethod
    def AppendAllBytes(path: str, bytes: list[int]) -> None: ...
    @overload
    @staticmethod
    def AppendAllBytes(path: str, bytes: Any) -> None: ...
    @overload
    @staticmethod
    def AppendAllBytesAsync(path: str, bytes: list[int], cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def AppendAllBytesAsync(path: str, bytes: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def AppendAllLines(path: str, contents: Any) -> None: ...
    @overload
    @staticmethod
    def AppendAllLines(path: str, contents: Any, encoding: Any) -> None: ...
    @overload
    @staticmethod
    def AppendAllLinesAsync(path: str, contents: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def AppendAllLinesAsync(path: str, contents: Any, encoding: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def AppendAllText(path: str, contents: str) -> None: ...
    @overload
    @staticmethod
    def AppendAllText(path: str, contents: Any) -> None: ...
    @overload
    @staticmethod
    def AppendAllText(path: str, contents: str, encoding: Any) -> None: ...
    @overload
    @staticmethod
    def AppendAllText(path: str, contents: Any, encoding: Any) -> None: ...
    @overload
    @staticmethod
    def AppendAllTextAsync(path: str, contents: str, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def AppendAllTextAsync(path: str, contents: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def AppendAllTextAsync(path: str, contents: str, encoding: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def AppendAllTextAsync(path: str, contents: Any, encoding: Any, cancellationToken: Any = ...) -> Any: ...
    @staticmethod
    def AppendText(path: str) -> Any: ...
    @overload
    @staticmethod
    def Copy(sourceFileName: str, destFileName: str) -> None: ...
    @overload
    @staticmethod
    def Copy(sourceFileName: str, destFileName: str, overwrite: bool) -> None: ...
    @overload
    @staticmethod
    def Create(path: str) -> Any: ...
    @overload
    @staticmethod
    def Create(path: str, bufferSize: int) -> Any: ...
    @overload
    @staticmethod
    def Create(path: str, bufferSize: int, options: Any) -> Any: ...
    @staticmethod
    def CreateSymbolicLink(path: str, pathToTarget: str) -> Any: ...
    @staticmethod
    def CreateText(path: str) -> Any: ...
    @staticmethod
    def Decrypt(path: str) -> None: ...
    @staticmethod
    def Delete(path: str) -> None: ...
    @staticmethod
    def Encrypt(path: str) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    @staticmethod
    def Exists(path: str) -> bool: ...
    @overload
    @staticmethod
    def GetAttributes(path: str) -> Any: ...
    @overload
    @staticmethod
    def GetAttributes(fileHandle: Any) -> Any: ...
    @overload
    @staticmethod
    def GetCreationTime(path: str) -> Any: ...
    @overload
    @staticmethod
    def GetCreationTime(fileHandle: Any) -> Any: ...
    @overload
    @staticmethod
    def GetCreationTimeUtc(path: str) -> Any: ...
    @overload
    @staticmethod
    def GetCreationTimeUtc(fileHandle: Any) -> Any: ...
    def GetHashCode(self) -> int: ...
    @overload
    @staticmethod
    def GetLastAccessTime(path: str) -> Any: ...
    @overload
    @staticmethod
    def GetLastAccessTime(fileHandle: Any) -> Any: ...
    @overload
    @staticmethod
    def GetLastAccessTimeUtc(path: str) -> Any: ...
    @overload
    @staticmethod
    def GetLastAccessTimeUtc(fileHandle: Any) -> Any: ...
    @overload
    @staticmethod
    def GetLastWriteTime(path: str) -> Any: ...
    @overload
    @staticmethod
    def GetLastWriteTime(fileHandle: Any) -> Any: ...
    @overload
    @staticmethod
    def GetLastWriteTimeUtc(path: str) -> Any: ...
    @overload
    @staticmethod
    def GetLastWriteTimeUtc(fileHandle: Any) -> Any: ...
    def GetType(self) -> Any: ...
    @overload
    @staticmethod
    def GetUnixFileMode(path: str) -> Any: ...
    @overload
    @staticmethod
    def GetUnixFileMode(fileHandle: Any) -> Any: ...
    @overload
    @staticmethod
    def Move(sourceFileName: str, destFileName: str) -> None: ...
    @overload
    @staticmethod
    def Move(sourceFileName: str, destFileName: str, overwrite: bool) -> None: ...
    @overload
    @staticmethod
    def Open(path: str, options: Any) -> Any: ...
    @overload
    @staticmethod
    def Open(path: str, mode: Any) -> Any: ...
    @overload
    @staticmethod
    def Open(path: str, mode: Any, access: Any) -> Any: ...
    @overload
    @staticmethod
    def Open(path: str, mode: Any, access: Any, share: Any) -> Any: ...
    @staticmethod
    def OpenHandle(path: str, mode: Any = ..., access: Any = ..., share: Any = ..., options: Any = ..., preallocationSize: int = ...) -> Any: ...
    @staticmethod
    def OpenRead(path: str) -> Any: ...
    @staticmethod
    def OpenText(path: str) -> Any: ...
    @staticmethod
    def OpenWrite(path: str) -> Any: ...
    @staticmethod
    def ReadAllBytes(path: str) -> list[int]: ...
    @staticmethod
    def ReadAllBytesAsync(path: str, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def ReadAllLines(path: str) -> list[str]: ...
    @overload
    @staticmethod
    def ReadAllLines(path: str, encoding: Any) -> list[str]: ...
    @overload
    @staticmethod
    def ReadAllLinesAsync(path: str, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def ReadAllLinesAsync(path: str, encoding: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def ReadAllText(path: str) -> str: ...
    @overload
    @staticmethod
    def ReadAllText(path: str, encoding: Any) -> str: ...
    @overload
    @staticmethod
    def ReadAllTextAsync(path: str, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def ReadAllTextAsync(path: str, encoding: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def ReadLines(path: str) -> Any: ...
    @overload
    @staticmethod
    def ReadLines(path: str, encoding: Any) -> Any: ...
    @overload
    @staticmethod
    def ReadLinesAsync(path: str, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def ReadLinesAsync(path: str, encoding: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def Replace(sourceFileName: str, destinationFileName: str, destinationBackupFileName: str) -> None: ...
    @overload
    @staticmethod
    def Replace(sourceFileName: str, destinationFileName: str, destinationBackupFileName: str, ignoreMetadataErrors: bool) -> None: ...
    @staticmethod
    def ResolveLinkTarget(linkPath: str, returnFinalTarget: bool) -> Any: ...
    @overload
    @staticmethod
    def SetAttributes(path: str, fileAttributes: Any) -> None: ...
    @overload
    @staticmethod
    def SetAttributes(fileHandle: Any, fileAttributes: Any) -> None: ...
    @overload
    @staticmethod
    def SetCreationTime(path: str, creationTime: Any) -> None: ...
    @overload
    @staticmethod
    def SetCreationTime(fileHandle: Any, creationTime: Any) -> None: ...
    @overload
    @staticmethod
    def SetCreationTimeUtc(path: str, creationTimeUtc: Any) -> None: ...
    @overload
    @staticmethod
    def SetCreationTimeUtc(fileHandle: Any, creationTimeUtc: Any) -> None: ...
    @overload
    @staticmethod
    def SetLastAccessTime(path: str, lastAccessTime: Any) -> None: ...
    @overload
    @staticmethod
    def SetLastAccessTime(fileHandle: Any, lastAccessTime: Any) -> None: ...
    @overload
    @staticmethod
    def SetLastAccessTimeUtc(path: str, lastAccessTimeUtc: Any) -> None: ...
    @overload
    @staticmethod
    def SetLastAccessTimeUtc(fileHandle: Any, lastAccessTimeUtc: Any) -> None: ...
    @overload
    @staticmethod
    def SetLastWriteTime(path: str, lastWriteTime: Any) -> None: ...
    @overload
    @staticmethod
    def SetLastWriteTime(fileHandle: Any, lastWriteTime: Any) -> None: ...
    @overload
    @staticmethod
    def SetLastWriteTimeUtc(path: str, lastWriteTimeUtc: Any) -> None: ...
    @overload
    @staticmethod
    def SetLastWriteTimeUtc(fileHandle: Any, lastWriteTimeUtc: Any) -> None: ...
    @overload
    @staticmethod
    def SetUnixFileMode(path: str, mode: Any) -> None: ...
    @overload
    @staticmethod
    def SetUnixFileMode(fileHandle: Any, mode: Any) -> None: ...
    def ToString(self) -> str: ...
    @overload
    @staticmethod
    def WriteAllBytes(path: str, bytes: list[int]) -> None: ...
    @overload
    @staticmethod
    def WriteAllBytes(path: str, bytes: Any) -> None: ...
    @overload
    @staticmethod
    def WriteAllBytesAsync(path: str, bytes: list[int], cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def WriteAllBytesAsync(path: str, bytes: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def WriteAllLines(path: str, contents: list[str]) -> None: ...
    @overload
    @staticmethod
    def WriteAllLines(path: str, contents: Any) -> None: ...
    @overload
    @staticmethod
    def WriteAllLines(path: str, contents: list[str], encoding: Any) -> None: ...
    @overload
    @staticmethod
    def WriteAllLines(path: str, contents: Any, encoding: Any) -> None: ...
    @overload
    @staticmethod
    def WriteAllLinesAsync(path: str, contents: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def WriteAllLinesAsync(path: str, contents: Any, encoding: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def WriteAllText(path: str, contents: str) -> None: ...
    @overload
    @staticmethod
    def WriteAllText(path: str, contents: Any) -> None: ...
    @overload
    @staticmethod
    def WriteAllText(path: str, contents: str, encoding: Any) -> None: ...
    @overload
    @staticmethod
    def WriteAllText(path: str, contents: Any, encoding: Any) -> None: ...
    @overload
    @staticmethod
    def WriteAllTextAsync(path: str, contents: str, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def WriteAllTextAsync(path: str, contents: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def WriteAllTextAsync(path: str, contents: str, encoding: Any, cancellationToken: Any = ...) -> Any: ...
    @overload
    @staticmethod
    def WriteAllTextAsync(path: str, contents: Any, encoding: Any, cancellationToken: Any = ...) -> Any: ...
