from typing import Generic, Iterable, Iterator, TypeVar, overload

T = TypeVar("T")

class List(Generic[T]):
    def __init__(self, iterable: Iterable[T] = ...) -> None: ...

    def Add(self, item: T) -> None: ...
    def AddRange(self, items: Iterable[T]) -> None: ...
    def Clear(self) -> None: ...

    def Contains(self, item: T) -> bool: ...
    def Remove(self, item: T) -> bool: ...

    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> list[T]: ...

    def __setitem__(self, index: int, value: T) -> None: ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
