from __future__ import annotations
from enum import IntEnum, IntFlag
from typing import Any, ClassVar, Generic, TypeVar, overload

T = TypeVar("T")
T1 = TypeVar("T1")
T2 = TypeVar("T2")
T3 = TypeVar("T3")
T4 = TypeVar("T4")

class RawBool:
    def __init__(self, boolValue: bool) -> None: ...
    @overload
    def Equals(self, other: RawBool) -> bool: ...
    @overload
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawBool4:
    X: int
    Y: int
    Z: int
    W: int
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawBox:
    X: int
    Y: int
    Width: int
    Height: int
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawColor3:
    R: float
    G: float
    B: float
    def __init__(self, r: float, g: float, b: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawColor4:
    R: float
    G: float
    B: float
    A: float
    def __init__(self, r: float, g: float, b: float, a: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawColorBGRA:
    B: int
    G: int
    R: int
    A: int
    def __init__(self, b: int, g: int, r: int, a: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawInt3:
    X: int
    Y: int
    Z: int
    def __init__(self, x: int, y: int, z: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawInt4:
    X: int
    Y: int
    Z: int
    W: int
    def __init__(self, x: int, y: int, z: int, w: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawMatrix:
    M11: float
    M12: float
    M13: float
    M14: float
    M21: float
    M22: float
    M23: float
    M24: float
    M31: float
    M32: float
    M33: float
    M34: float
    M41: float
    M42: float
    M43: float
    M44: float
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawMatrix3x2:
    M11: float
    M12: float
    M21: float
    M22: float
    M31: float
    M32: float
    def __init__(self, m11: float, m12: float, m21: float, m22: float, m31: float, m32: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawMatrix4x3:
    M11: float
    M12: float
    M13: float
    M21: float
    M22: float
    M23: float
    M31: float
    M32: float
    M33: float
    M41: float
    M42: float
    M43: float
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawMatrix5x4:
    M11: float
    M12: float
    M13: float
    M14: float
    M21: float
    M22: float
    M23: float
    M24: float
    M31: float
    M32: float
    M33: float
    M34: float
    M41: float
    M42: float
    M43: float
    M44: float
    M51: float
    M52: float
    M53: float
    M54: float
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawPlane:
    Normal: RawVector3
    D: float
    def __init__(self, normal: RawVector3, d: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawPoint:
    X: int
    Y: int
    def __init__(self, x: int, y: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawQuaternion:
    X: float
    Y: float
    Z: float
    W: float
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawRectangle:
    IsEmpty: bool
    Left: int
    Top: int
    Right: int
    Bottom: int
    def __init__(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawRectangleF:
    Left: float
    Top: float
    Right: float
    Bottom: float
    def __init__(self, left: float, top: float, right: float, bottom: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawVector2:
    X: float
    Y: float
    def __init__(self, x: float, y: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawVector3:
    X: float
    Y: float
    Z: float
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawVector4:
    X: float
    Y: float
    Z: float
    W: float
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawViewport:
    X: int
    Y: int
    Width: int
    Height: int
    MinDepth: float
    MaxDepth: float
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...

class RawViewportF:
    X: float
    Y: float
    Width: float
    Height: float
    MinDepth: float
    MaxDepth: float
    def Equals(self, obj: Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Any: ...
    def ToString(self) -> str: ...
